#
# Make file for blk_io_hierarchy_stats
#

obj-$(CONFIG_BLK_IO_HIERARCHY_STATS) += blk_io_hierarchy_stats.o

blk_io_hierarchy_stats-y := stats.o debugfs.o
obj-$(CONFIG_HIERARCHY_IO_DUMP) += iodump.o
