# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the Linkdata network device drivers.
#
obj-$(CONFIG_SXE) += sxe/
obj-$(CONFIG_SXE_VF) += sxevf/
obj-$(CONFIG_SXE2) += sxe2/
obj-$(CONFIG_SXE2_VF) += sxe2vf/
