/* SPDX-License-Identifier: GPL-2.0 */
/* Copyright (c) 2023 - 2024 ZTE Corporation */

#ifndef __ZXIC_SLT_H__
#define __ZXIC_SLT_H__
#define ZXIC_SLT_CASE_PASS (0U)
#define ZXIC_SLT_CASE_FAILURE (1U)

#define ZXIC_SLT_ERR_INFO_LEN (255U)
#define ZXIC_SLT_CASE_MAX_NUM (255U)
#define ZXIC_SLT_DEV_ID_MAX_NUM (4U)
#define ZXIC_SLT_CHIP_ID_LEN (3U)

#define ZXIC_SLT_MAX_ENCAP (5U)

#define ZXIC_SLT_BIN_CODE_PASS ZXIC_SLT_CASE_PASS
#define ZXIC_SLT_BIN_CODE_SERDES_FAIL (1U)
#define ZXIC_SLT_BIN_CODE_FLOW_FAIL (2U)
#define ZXIC_SLT_BIN_CODE_RAM_FAIL (3U)
#define ZXIC_SLT_BIN_CODE_HBM_DDR_FAIL (4U)
#define ZXIC_SLT_BIN_CODE_OTHER_FAIL (5U) /* PLL EFUSE PCIE RISCV */
#define ZXIC_SLT_BIN_CODE_MIX_FAIL (6U)

enum zxic_slt_case_no_e {
	ZXIC_SLT_CASE_PLL_LOCK_STATUS_CHECK = (0x08U),

	ZXIC_SLT_CASE_EFUSE_CHECK = (0x09U),

	ZXIC_SLT_CASE_SERDES_LIFX_PRBS_1G = (0x10U),
	ZXIC_SLT_CASE_SERDES_LIFX_PRBS_3G = (0x11U),
	ZXIC_SLT_CASE_SERDES_LIFX_PRBS_5G = (0x12U),
	ZXIC_SLT_CASE_SERDES_LIFX_PRBS_6G = (0x13U),
	ZXIC_SLT_CASE_SERDES_LIFX_PRBS_9G = (0x14U),
	ZXIC_SLT_CASE_SERDES_LIFX_PRBS_10G = (0x15U),
	ZXIC_SLT_CASE_SERDES_LIFX_PRBS_12G = (0x16U),
	ZXIC_SLT_CASE_SERDES_LIFX_PRBS_15G = (0x17U),
	ZXIC_SLT_CASE_SERDES_LIFX_PRBS_20G = (0x18U),
	ZXIC_SLT_CASE_SERDES_LIFX_PRBS_25G = (0x19U),
	ZXIC_SLT_CASE_SERDES_LIFX_PRBS_26G = (0x1aU),
	ZXIC_SLT_CASE_SERDES_LIFX_PRBS_27G = (0x1bU),
	ZXIC_SLT_CASE_SERDES_LIFX_PRBS_28G = (0x1cU),
	ZXIC_SLT_CASE_SERDES_LIFX_PRBS_30G = (0x1dU),
	ZXIC_SLT_CASE_SERDES_LIFX_PRBS_50G = (0x1fU),
	ZXIC_SLT_CASE_SERDES_LIFX_PRBS_51G = (0x20U),
	ZXIC_SLT_CASE_SERDES_LIFX_PRBS_53G = (0x21U),
	ZXIC_SLT_CASE_SERDES_LIFX_PRBS_55G = (0x22U),
	ZXIC_SLT_CASE_SERDES_LIFX_PRBS_56G = (0x23U),
	ZXIC_SLT_CASE_SERDES_LIFX_PRBS_57G = (0x24U),
	ZXIC_SLT_CASE_SERDES_LIFX_PRBS_98G = (0x25U),
	ZXIC_SLT_CASE_SERDES_LIFX_PRBS_106G = (0x26U),
	ZXIC_SLT_CASE_SERDES_LIFX_PRBS_111G = (0x27U),
	ZXIC_SLT_CASE_SERDES_LIFX_PRBS_112G = (0x28U),

	ZXIC_SLT_CASE_SERDES_LIFC_PRBS_1G = (0x30U),
	ZXIC_SLT_CASE_SERDES_LIFC_PRBS_10G = (0x31U),
	ZXIC_SLT_CASE_SERDES_LIFC_PRBS_25G = (0x32U),
	ZXIC_SLT_CASE_SERDES_LIFC_PRBS_53G = (0x33U),

	ZXIC_SLT_CASE_PORT_LIFC_SD_1G = (0x38U),
	ZXIC_SLT_CASE_PORT_LIFC_SD_10G = (0x39U),
	ZXIC_SLT_CASE_PORT_LIFC_SD_25G = (0x3aU),
	ZXIC_SLT_CASE_PORT_LIFC_SD_53G = (0x3bU),

	ZXIC_SLT_CASE_SERDES_INTERLAKEN_LA = (0x3fU),

	ZXIC_SLT_CASE_PORT_LIFO_SD_1G = (0x40U),
	ZXIC_SLT_CASE_PORT_LIFO_SD_5G = (0x41U),
	ZXIC_SLT_CASE_PORT_LIFO_SD_10G = (0x42U),
	ZXIC_SLT_CASE_PORT_LIFO_SD_12G = (0x43U),
	ZXIC_SLT_CASE_PORT_LIFO_SD_25G = (0x44U),
	ZXIC_SLT_CASE_PORT_LIFO_SD_26G = (0x45U),
	ZXIC_SLT_CASE_PORT_LIFO_SD_51G = (0x46U),
	ZXIC_SLT_CASE_PORT_LIFO_SD_53G = (0x47U),
	ZXIC_SLT_CASE_PORT_LIFO_SD_106G = (0x48U),
	ZXIC_SLT_CASE_PORT_LIFO_SD_112G = (0x49U),
	ZXIC_SLT_CASE_PORT_LIFO_SD_20G = (0x4AU),

	ZXIC_SLT_CASE_PORT_LIFO_SD_ILK_3G = (0x60U),
	ZXIC_SLT_CASE_PORT_LIFO_SD_ILK_6G = (0x61U),
	ZXIC_SLT_CASE_PORT_LIFO_SD_ILK_10G = (0x62U),
	ZXIC_SLT_CASE_PORT_LIFO_SD_ILK_12G = (0x63U),
	ZXIC_SLT_CASE_PORT_LIFO_SD_ILK_25G = (0x64U),
	ZXIC_SLT_CASE_PORT_LIFO_SD_ILK_28G = (0x65U),
	ZXIC_SLT_CASE_PORT_LIFO_SD_ILK_30G = (0x66U),
	ZXIC_SLT_CASE_PORT_LIFO_SD_ILK_50G = (0x67U),
	ZXIC_SLT_CASE_PORT_LIFO_SD_ILK_51G = (0x68U),
	ZXIC_SLT_CASE_PORT_LIFO_SD_ILK_53G = (0x69U),
	ZXIC_SLT_CASE_PORT_LIFO_SD_ILK_56G = (0x6aU),
	ZXIC_SLT_CASE_PORT_LIFO_SD_ILK_106G = (0x6bU),
	ZXIC_SLT_CASE_PORT_LIFO_SD_ILK_112G = (0x6cU),

	ZXIC_SLT_CASE_SERDES_LIF1_FEC_25G = (0x70U),
	ZXIC_SLT_CASE_SERDES_LIF1_FEC_26G = (0x71U),
	ZXIC_SLT_CASE_SERDES_LIF1_FEC_28G = (0x72U),
	ZXIC_SLT_CASE_SERDES_LIF1_FEC_50G = (0x73U),
	ZXIC_SLT_CASE_SERDES_LIF1_FEC_53G = (0x74U),
	ZXIC_SLT_CASE_SERDES_LIF1_FEC_56G = (0x75U),
	ZXIC_SLT_CASE_SERDES_LIF1_FEC_98G = (0x76U),
	ZXIC_SLT_CASE_SERDES_LIF1_FEC_106G = (0x77U),
	ZXIC_SLT_CASE_SERDES_LIF1_FEC_112G = (0x78U),

	ZXIC_SLT_CASE_REG_CPU_W_R = (0x80U),

	ZXIC_SLT_CASE_RAM_CPU_W_R = (0x81U),

	ZXIC_SLT_CASE_RAM_MC_W_R = (0x82U),

	ZXIC_SLT_CASE_RAM_MC_MEMTEST86 = (0x83U),

	ZXIC_SLT_CASE_HBM_DDR_CTRL_BIST = (0x90U),

	ZXIC_SLT_CASE_HBM_DDR_CPU_W_R = (0x91U),

	ZXIC_SLT_CASE_HBM_DDR_MC_W_R = (0x92U),

	ZXIC_SLT_CASE_HBM_DDR_MC_MEMTEST86 = (0x93U),

	ZXIC_SLT_CASE_HBM_DDR_TM_TEST = (0x94U),

	ZXIC_SLT_CASE_PKT_FLOW_NOM = (0xA0U),

	ZXIC_SLT_CASE_OAM_SEND_PKT = (0xA1U),

	ZXIC_SLT_CASE_PKT_FLOW_SE_FULL = (0xA2U),

	ZXIC_SLT_CASE_PKT_FLOW_TM_FULL = (0xA3U),

	ZXIC_SLT_CASE_PKT_FLOW_LIFC = (0xA4U),

	ZXIC_SLT_CASE_PVT_EXCEED_POWER_TEST = (0xA8U),
	ZXIC_SLT_CASE_PVT_EXCEED_TEM_VOLT_TEST = (0xA9U),
	ZXIC_SLT_CASE_PVT_EXCEED_HBM_TEMPER_TEST = (0xAaU),

	ZXIC_SLT_CASE_VOLT_TEST = (0xB0U),

	ZXIC_SLT_CASE_CLK_TEST = (0xB1U),

	ZXIC_SLT_CASE_PCIE_W_R_TEST = (0xB2U),

	ZXIC_SLT_CASE_PCIE_TEST = (0xB3U),

	ZXIC_SLT_CASE_RISCV_W_R_TEST = (0xB4U),

	ZXIC_SLT_CASE_MAX,
};

#if ZXIC_REAL("ERR_CODE")
#define ZXIC_SLT_RC_BASE (0x100U)

#define ZXIC_SLT_TEST_CASE_FNC_POINT_NULL (ZXIC_SLT_RC_BASE | 0x1)
#define ZXIC_SLT_CASE_PLL_LOCK_STATUS_CHECK_FAIL \
	(ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_PLL_LOCK_STATUS_CHECK)
#define ZXIC_SLT_CASE_EFUSE_CHECK_FAIL (ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_EFUSE_CHECK)

/* lifx*/
#define ZXIC_SLT_CASE_SERDES_LIFX_PRBS_1G_FAIL \
	(ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_SERDES_LIFX_PRBS_1G)
#define ZXIC_SLT_CASE_SERDES_LIFX_PRBS_3G_FAIL \
	(ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_SERDES_LIFX_PRBS_3G)
#define ZXIC_SLT_CASE_SERDES_LIFX_PRBS_5G_FAIL \
	(ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_SERDES_LIFX_PRBS_5G)
#define ZXIC_SLT_CASE_SERDES_LIFX_PRBS_6G_FAIL \
	(ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_SERDES_LIFX_PRBS_6G)
#define ZXIC_SLT_CASE_SERDES_LIFX_PRBS_9G_FAIL \
	(ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_SERDES_LIFX_PRBS_9G)
#define ZXIC_SLT_CASE_SERDES_LIFX_PRBS_10G_FAIL \
	(ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_SERDES_LIFX_PRBS_10G)
#define ZXIC_SLT_CASE_SERDES_LIFX_PRBS_12G_FAIL \
	(ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_SERDES_LIFX_PRBS_12G)
#define ZXIC_SLT_CASE_SERDES_LIFX_PRBS_15G_FAIL \
	(ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_SERDES_LIFX_PRBS_15G)
#define ZXIC_SLT_CASE_SERDES_LIFX_PRBS_20G_FAIL \
	(ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_SERDES_LIFX_PRBS_20G)
#define ZXIC_SLT_CASE_SERDES_LIFX_PRBS_25G_FAIL \
	(ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_SERDES_LIFX_PRBS_25G)
#define ZXIC_SLT_CASE_SERDES_LIFX_PRBS_26G_FAIL \
	(ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_SERDES_LIFX_PRBS_26G)
#define ZXIC_SLT_CASE_SERDES_LIFX_PRBS_27G_FAIL \
	(ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_SERDES_LIFX_PRBS_27G)
#define ZXIC_SLT_CASE_SERDES_LIFX_PRBS_28G_FAIL \
	(ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_SERDES_LIFX_PRBS_28G)
#define ZXIC_SLT_CASE_SERDES_LIFX_PRBS_30G_FAIL \
	(ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_SERDES_LIFX_PRBS_30G)
#define ZXIC_SLT_CASE_SERDES_LIFX_PRBS_50G_FAIL \
	(ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_SERDES_LIFX_PRBS_50G)
#define ZXIC_SLT_CASE_SERDES_LIFX_PRBS_51G_FAIL \
	(ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_SERDES_LIFX_PRBS_51G)
#define ZXIC_SLT_CASE_SERDES_LIFX_PRBS_53G_FAIL \
	(ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_SERDES_LIFX_PRBS_53G)
#define ZXIC_SLT_CASE_SERDES_LIFX_PRBS_55G_FAIL \
	(ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_SERDES_LIFX_PRBS_55G)
#define ZXIC_SLT_CASE_SERDES_LIFX_PRBS_56G_FAIL \
	(ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_SERDES_LIFX_PRBS_56G)
#define ZXIC_SLT_CASE_SERDES_LIFX_PRBS_57G_FAIL \
	(ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_SERDES_LIFX_PRBS_57G)
#define ZXIC_SLT_CASE_SERDES_LIFX_PRBS_98G_FAIL \
	(ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_SERDES_LIFX_PRBS_98G)
#define ZXIC_SLT_CASE_SERDES_LIFX_PRBS_106G_FAIL \
	(ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_SERDES_LIFX_PRBS_106G)
#define ZXIC_SLT_CASE_SERDES_LIFX_PRBS_111G_FAIL \
	(ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_SERDES_LIFX_PRBS_111G)
#define ZXIC_SLT_CASE_SERDES_LIFX_PRBS_112G_FAIL \
	(ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_SERDES_LIFX_PRBS_112G)

/* lifc*/
#define ZXIC_SLT_CASE_SERDES_LIFC_PRBS_1G_FAIL \
	(ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_SERDES_LIFC_PRBS_1G)
#define ZXIC_SLT_CASE_SERDES_LIFC_PRBS_10G_FAIL \
	(ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_SERDES_LIFC_PRBS_10G)
#define ZXIC_SLT_CASE_SERDES_LIFC_PRBS_25G_FAIL \
	(ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_SERDES_LIFC_PRBS_25G)
#define ZXIC_SLT_CASE_SERDES_LIFC_PRBS_53G_FAIL \
	(ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_SERDES_LIFC_PRBS_53G)

/* lifc */
#define ZXIC_SLT_CASE_PORT_LIFC_SD_1G_FAIL (ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_PORT_LIFC_SD_1G)
#define ZXIC_SLT_CASE_PORT_LIFC_SD_10G_FAIL (ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_PORT_LIFC_SD_10G)
#define ZXIC_SLT_CASE_PORT_LIFC_SD_25G_FAIL (ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_PORT_LIFC_SD_25G)
#define ZXIC_SLT_CASE_PORT_LIFC_SD_53G_FAIL (ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_PORT_LIFC_SD_53G)

/* lif0 ETH*/
#define ZXIC_SLT_CASE_PORT_LIFO_SD_1G_FAIL (ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_PORT_LIFO_SD_1G)
#define ZXIC_SLT_CASE_PORT_LIFO_SD_5G_FAIL (ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_PORT_LIFO_SD_5G)
#define ZXIC_SLT_CASE_PORT_LIFO_SD_10G_FAIL (ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_PORT_LIFO_SD_10G)
#define ZXIC_SLT_CASE_PORT_LIFO_SD_12G_FAIL (ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_PORT_LIFO_SD_12G)
#define ZXIC_SLT_CASE_PORT_LIFO_SD_25G_FAIL (ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_PORT_LIFO_SD_25G)
#define ZXIC_SLT_CASE_PORT_LIFO_SD_26G_FAIL (ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_PORT_LIFO_SD_26G)
#define ZXIC_SLT_CASE_PORT_LIFO_SD_51G_FAIL (ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_PORT_LIFO_SD_51G)
#define ZXIC_SLT_CASE_PORT_LIFO_SD_53G_FAIL (ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_PORT_LIFO_SD_53G)
#define ZXIC_SLT_CASE_PORT_LIFO_SD_106G_FAIL (ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_PORT_LIFO_SD_106G)
#define ZXIC_SLT_CASE_PORT_LIFO_SD_112G_FAIL (ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_PORT_LIFO_SD_112G)
#define ZXIC_SLT_CASE_PORT_LIFO_SD_20G_FAIL (ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_PORT_LIFO_SD_20G)

/* lif0 intlk*/
#define ZXIC_SLT_CASE_PORT_LIFO_SD_ILK_3G_FAIL \
	(ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_PORT_LIFO_SD_ILK_3G)
#define ZXIC_SLT_CASE_PORT_LIFO_SD_ILK_6G_FAIL \
	(ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_PORT_LIFO_SD_ILK_6G)
#define ZXIC_SLT_CASE_PORT_LIFO_SD_ILK_10G_FAIL \
	(ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_PORT_LIFO_SD_ILK_10G)
#define ZXIC_SLT_CASE_PORT_LIFO_SD_ILK_12G_FAIL \
	(ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_PORT_LIFO_SD_ILK_12G)
#define ZXIC_SLT_CASE_PORT_LIFO_SD_ILK_25G_FAIL \
	(ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_PORT_LIFO_SD_ILK_25G)
#define ZXIC_SLT_CASE_PORT_LIFO_SD_ILK_28G_FAIL \
	(ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_PORT_LIFO_SD_ILK_28G)
#define ZXIC_SLT_CASE_PORT_LIFO_SD_ILK_30G_FAIL \
	(ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_PORT_LIFO_SD_ILK_30G)
#define ZXIC_SLT_CASE_PORT_LIFO_SD_ILK_50G_FAIL \
	(ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_PORT_LIFO_SD_ILK_50G)
#define ZXIC_SLT_CASE_PORT_LIFO_SD_ILK_51G_FAIL \
	(ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_PORT_LIFO_SD_ILK_51G)
#define ZXIC_SLT_CASE_PORT_LIFO_SD_ILK_53G_FAIL \
	(ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_PORT_LIFO_SD_ILK_53G)
#define ZXIC_SLT_CASE_PORT_LIFO_SD_ILK_56G_FAIL \
	(ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_PORT_LIFO_SD_ILK_56G)
#define ZXIC_SLT_CASE_PORT_LIFO_SD_ILK_106G_FAIL \
	(ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_PORT_LIFO_SD_ILK_106G)
#define ZXIC_SLT_CASE_PORT_LIFO_SD_ILK_112G_FAIL \
	(ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_PORT_LIFO_SD_ILK_112G)

/* lif1*/
#define ZXIC_SLT_CASE_SERDES_LIF1_FEC_25G_FAIL \
	(ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_SERDES_LIF1_FEC_25G)
#define ZXIC_SLT_CASE_SERDES_LIF1_FEC_26G_FAIL \
	(ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_SERDES_LIF1_FEC_26G)
#define ZXIC_SLT_CASE_SERDES_LIF1_FEC_28G_FAIL \
	(ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_SERDES_LIF1_FEC_28G)
#define ZXIC_SLT_CASE_SERDES_LIF1_FEC_50G_FAIL \
	(ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_SERDES_LIF1_FEC_50G)
#define ZXIC_SLT_CASE_SERDES_LIF1_FEC_53G_FAIL \
	(ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_SERDES_LIF1_FEC_53G)
#define ZXIC_SLT_CASE_SERDES_LIF1_FEC_56G_FAIL \
	(ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_SERDES_LIF1_FEC_56G)
#define ZXIC_SLT_CASE_SERDES_LIF1_FEC_98G_FAIL \
	(ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_SERDES_LIF1_FEC_98G)
#define ZXIC_SLT_CASE_SERDES_LIF1_FEC_106G_FAIL \
	(ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_SERDES_LIF1_FEC_106G)
#define ZXIC_SLT_CASE_SERDES_LIF1_FEC_112G_FAIL \
	(ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_SERDES_LIF1_FEC_112G)

#define ZXIC_SLT_CASE_SERDES_INTELAKEN_LA_FAIL \
	(ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_SERDES_INTELAKEN_LA)

#define ZXIC_SLT_CASE_RAM_CPU_W_R_FAIL (ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_RAM_CPU_W_R)
#define ZXIC_SLT_CASE_REG_CPU_W_R_FAIL (ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_REG_CPU_W_R)
#define ZXIC_SLT_CASE_RAM_MC_W_R_FAIL (ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_RAM_MC_W_R)
#define ZXIC_SLT_CASE_RAM_MC_MEMTEST86_FAIL (ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_RAM_MC_MEMTEST86)

/* HBM/DDR */
#define ZXIC_SLT_CASE_HBM_DDR_CTRL_BIST_FAIL (ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_HBM_DDR_CTRL_BIST)
#define ZXIC_SLT_CASE_HBM_DDR_MC_W_R_FAIL (ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_HBM_DDR_MC_W_R)
#define ZXIC_SLT_CASE_HBM_DDR_MC_MEMTEST86_FAIL \
	(ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_HBM_DDR_MC_MEMTEST86)
#define ZXIC_SLT_CASE_HBM_DDR_CPU_W_R_FAIL (ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_HBM_DDR_CPU_W_R)
#define ZXIC_SLT_CASE_HBM_DDR_TM_TEST_FAIL (ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_HBM_DDR_TM_TEST)

#define ZXIC_SLT_CASE_PKT_FLOW_NOM_FAIL (ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_PKT_FLOW_NOM)
#define ZXIC_SLT_CASE_OAM_SEND_PKT_FAIL (ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_OAM_SEND_PKT)
#define ZXIC_SLT_CASE_PKT_FLOW_SE_FULL_FAIL (ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_PKT_FLOW_SE_FULL)
#define ZXIC_SLT_CASE_PKT_FLOW_TM_FULL_FAIL (ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_PKT_FLOW_TM_FULL)
#define ZXIC_SLT_CASE_PKT_FLOW_LIFC_FAIL (ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_PKT_FLOW_LIFC)

#define ZXIC_SLT_CASE_PVT_EXCEED_POWER_TEST_FAIL \
	(ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_PVT_EXCEED_POWER_TEST)
#define ZXIC_SLT_CASE_PVT_EXCEED_TEM_VOLT_TEST_FAIL \
	(ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_PVT_EXCEED_TEM_VOLT_TEST)
#define ZXIC_SLT_CASE_PVT_EXCEED_HBM_TEMPER_TEST_FAIL \
	(ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_PVT_EXCEED_HBM_TEMPER_TEST)

#define ZXIC_SLT_CASE_PCIE_TEST_FAIL (ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_PCIE_TEST)
#define ZXIC_SLT_CASE_PCIE_W_R_TEST_FAIL (ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_PCIE_W_R_TEST)
#define ZXIC_SLT_CASE_RISCV_W_R_TEST_FAIL (ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_RISCV_W_R_TEST)
#define ZXIC_SLT_CASE_VOLT_TEST_FAIL (ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_VOLT_TEST)
#define ZXIC_SLT_CASE_CLK_TEST_FAIL (ZXIC_SLT_RC_BASE | ZXIC_SLT_CASE_CLK_TEST)

#endif

struct zxic_slt_err_info_mng_t {
	u32 err_code;
	const char *err_info;
};

struct zxic_slt_init_ctrl_t {
	ZXIC_ADDR_T pcie_vir_baddr;
	ZXIC_ADDR_T riscv_vir_baddr;
	ZXIC_ADDR_T dma_vir_baddr;
	ZXIC_ADDR_T dma_phy_baddr;
};

struct zxic_slt_case_para_t

{
	u32 chip_id[ZXIC_SLT_CHIP_ID_LEN];
	u32 case_num;
	u32 case_no[ZXIC_SLT_CASE_MAX_NUM];
	u32 case_result[ZXIC_SLT_CASE_MAX_NUM];
	u32 bin_code;
	long temp;
	long volt;
};

typedef u32 (*ZXIC_SLT_INST_CASE_FN)(u32 device_id);

struct zxic_slt_case_mng_t {
	const char *case_name;
	u32 case_no;
	ZXIC_SLT_INST_CASE_FN inst_case_fn;
};

enum zxic_slt_power_type_t {
	ZXIC_SLT_POWER_VCC_SSP4_CORE = (0x0U),
	ZXIC_SLT_POWER_VCC0V75_SSP4_SERDES_DVDD = (0x1U),
	ZXIC_SLT_POWER_VCC0V75_SSP4_SERDES_AVDDL = (0x2U),
	ZXIC_SLT_POWER_VCC1V2_SSP4_SERDES_AVDDH = (0x3U),
	ZXIC_SLT_POWER_VCC1V2_SSP4_HBM_VDDQ = (0x4U),

	ZXIC_SLT_POWER_VCC0V75_SSP4_AVDD = (0x5U),
	ZXIC_SLT_POWER_VCC1V2_SSP4_AVDD = (0x6U),
	ZXIC_SLT_POWER_VCC1V2_SSP4_GPIO_DVDD = (0x7U),
	ZXIC_SLT_POWER_VCC2V5_SSP4_VPP = (0x8U),

	ZXIC_SLT_POWER_TYPE_MAX,

};

struct zxic_slt_power_t {
	long volt;
	long cur;
	u32 type;
};

struct zxic_slt_power_para_t {
	struct zxic_slt_power_t *p_para;
	u32 num;
};

enum zxic_slt_volt_type_t {
	ZXIC_SLT_VOLT_VCC_SSP4_CORE = (0x0U),
	ZXIC_SLT_VOLT_VCC0V75_SSP4_SERDES_DVDD = (0x1U),
	ZXIC_SLT_VOLT_VCC0V75_SSP4_SERDES_AVDDL = (0x2U),
	ZXIC_SLT_VOLT_VCC1V2_SSP4_SERDES_AVDDH = (0x3U),
	ZXIC_SLT_VOLT_VCC1V2_SSP4_HBM_VDDQ = (0x4U),

	ZXIC_SLT_VOLT_TYPE_MAX,

};

struct zxic_slt_volt_t {
	u32 percent;
	u32 flag;
	u32 vol_type;
};

struct zxic_slt_volt_para_t {
	struct zxic_slt_volt_t *p_para;
	u32 num;
};

enum zxic_slt_clk_type_t {
	ZXIC_SLT_CLK_AU5327_A = (0x0U),
	ZXIC_SLT_CLK_AU5327_B = (0x1U),
	ZXIC_SLT_CLK_AU5327_C = (0x2U),
	ZXIC_SLT_CLK_AU5327_D = (0x3U),

	ZXIC_SLT_CLK_TYPE_MAX,

};

struct zxic_slt_clk_t {
	u32 value;
	u32 flag;
	u32 clk_type;
};

struct zxic_slt_clk_para_t {
	struct zxic_slt_clk_t *p_para;
	u32 num;
};

#if ZXIC_REAL("define_for_bsp")
typedef u32 (*ZXIC_SLT_CASE_GETPOWER_FN)(u32 device_id, struct zxic_slt_power_para_t *p_para);
typedef u32 (*ZXIC_SLT_CASE_RISCV_FN)(u32 device_id, u32 reg_addr, u32 wr_data, u32 rd_data);
typedef u32 (*ZXIC_SLT_CASE_PCIE_FN)(u32 device_id, u32 times);
typedef u32 (*ZXIC_SLT_CASE_ADJUST_VOLT_FN)(u32 device_id, struct zxic_slt_volt_para_t *p_para);
typedef u32 (*ZXIC_SLT_CASE_ADJUST_CLK_FN)(u32 device_id, struct zxic_slt_clk_para_t *p_para);

struct zxic_slt_bsp_register_fn_t {
	ZXIC_SLT_CASE_GETPOWER_FN zxic_slt_power_fn;
	ZXIC_SLT_CASE_RISCV_FN zxic_slt_riscv_fn;
	ZXIC_SLT_CASE_PCIE_FN zxic_slt_pcie_fn;
	ZXIC_SLT_CASE_ADJUST_VOLT_FN zxic_slt_volt_fn;
	ZXIC_SLT_CASE_ADJUST_CLK_FN zxic_slt_clk_fn;
};

#endif

#if ZXIC_REAL("define_for_sdk")
typedef u32 (*ZXIC_SLT_INIT_FN)(u32 device_id, u32 chip_type,
				struct zxic_slt_init_ctrl_t *p_init_ctrl);

/* Chip_ID
 ** Chip_ID = efusewafer+wafer+x+Y
 ** wafer: 48bit lot_id5~0
 ** wafer:   5bit  wafer_no
 ** x:           8bit  x_addr
 ** Y:           8bit  y_addr
 ** chip_id2 = lot_id5[7:3]
 ** chip_id1 = lot_id5[2:0] + lot_id4 + lot_id3 + lot_id2 + lot_id1[7:3]
 ** chip_id0 = lot_id1[2:0] + lot_id0 + wafer_no[4:0] + x_addr + y_addr
 */
typedef u32 (*ZXIC_SLT_PRE_FN)(u32 device_id, u32 chip_type, u32 *p_chip_id, long *p_temp,
			       long *p_volt);
typedef u32 (*ZXIC_SLT_ALL_CASE_FN)(u32 device_id, u32 chip_type, u32 *p_case_num, u32 *p_case_no,
				    u32 *p_case_result);

struct zxic_slt_register_fn_t {
	ZXIC_SLT_INIT_FN zxic_slt_init_fn;
	ZXIC_SLT_PRE_FN zxic_slt_pre_fn;
	ZXIC_SLT_ALL_CASE_FN zxic_slt_all_case_fn;
};

#endif

#if ZXIC_REAL("fn for sdk")
u32 zxic_slt_register_fn_set(struct zxic_slt_register_fn_t *pExcCall);
u32 zxic_slt_callback_getpower(void *pExcCall);
u32 zxic_slt_callback_riscv(void *pExcCall);
u32 zxic_slt_callback_pcie(void *pExcCall);
u32 zxic_slt_callback_adjust_volt(void *pExcCall);
u32 zxic_slt_callback_adjust_clk(void *pExcCall);

#endif

#if ZXIC_REAL("fn for bsp")
u32 zxic_slt_bsp_register_fn_set(struct zxic_slt_bsp_register_fn_t *pExcCall);
void zxic_slt_log_rm_flag_set(u32 log_rm_flag);
u32 zxic_slt_all_case_test(u32 dev_id, u32 chip_type, struct zxic_slt_init_ctrl_t *p_init_ctrl,
			   struct zxic_slt_case_para_t *p_case_para);

#endif

#endif /* end __ZXIC_SLT_H__ */
