# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for the Huawei device drivers.
#

obj-$(CONFIG_HINIC) += hinic/
obj-$(CONFIG_HINIC3) += hinic3/
obj-$(CONFIG_HINIC5) += hinic5/src/dpu_platform_library/host/service/nic/linux/
obj-$(CONFIG_BMA) += bma/
obj-$(CONFIG_HIBIFUR) += hibifur/
