/* SPDX-License-Identifier: GPL-2.0 */
/**
 * Copyright (C), 2020, sxe2rdma Technologies Co., Ltd.
 *
 * @file: sxe2_drv_hw.h
 * @author: sxe2rdma
 * @date: 2025.02.16
 * @brief:
 * @note:
 */

#ifndef SXE2_DRV_HW_H
#define SXE2_DRV_HW_H
#include "sxe2_drv_rdma_common.h"

#define SXE2_FIRST_VF_FPM_ID 8
#define SXE2_MAX_STATS_COUNT   0
#define SXE2_HW_STAT_MAX_INDEX 0

#define SXE2_TOP_REG_COMPAT_OFFSET   0x0029220c

#define PF_RDMA_FEATURE_HW_VERSION_LOW_OFFSET                                  \
	(PF_SXE2_RCMS_MAN_BAR_OFFSET + 0x98)
#define PF_RDMA_FEATURE_HW_VERSION_HIGH_OFFSET                                 \
	(PF_SXE2_RCMS_MAN_BAR_OFFSET + 0x9C)
#define PF_RDMA_FEATURE_ENDPT_TRK_OFFSET  (PF_SXE2_RCMS_MAN_BAR_OFFSET + 0xA0)
#define PF_RDMA_FEATURE_QSETS_MAX_OFFSET  (PF_SXE2_RCMS_MAN_BAR_OFFSET + 0xA4)
#define PF_RDMA_FEATURE_FW_VERSION_OFFSET (PF_SXE2_RCMS_MAN_BAR_OFFSET + 0xA8)

#define VF_RDMA_FEATURE_HW_VERSION_LOW_OFFSET                                  \
	(VF_SXE2_RCMS_MAN_BAR_OFFSET + 0x98)
#define VF_RDMA_FEATURE_HW_VERSION_HIGH_OFFSET                                 \
	(VF_SXE2_RCMS_MAN_BAR_OFFSET + 0x9C)
#define VF_RDMA_FEATURE_ENDPT_TRK_OFFSET  (VF_SXE2_RCMS_MAN_BAR_OFFSET + 0xA0)
#define VF_RDMA_FEATURE_QSETS_MAX_OFFSET  (VF_SXE2_RCMS_MAN_BAR_OFFSET + 0xA4)
#define VF_RDMA_FEATURE_FW_VERSION_OFFSET (VF_SXE2_RCMS_MAN_BAR_OFFSET + 0xA8)

enum sxe2_vf_bar_regs_idx {
	QSET_APPLY_REQ,
	QSET_APPLY_RESP,
	QSET_QUERY_REQ,
	QSET_QUERY_RESP,
	QSET_RELEASE_REQ,
	QSET_RELEASE_RESP,
	QSET_QP_BIND_REQ,
	QSET_QP_BIND_RESP,
	IRQ_DYN_CTL,
	MQC_ADDR_HIGH,
	MQC_ADDR_LOW,
	MQC_ADDR_VLD,
	MQ_STATUS,
	MQ_DB,
	MQ_WQE_DONE,
	MQ_ERRCODES,
	RCMS_SPT_CACHE_FAST_INVALID_MASK,
	RCMS_SPT_CACHE_FAST_INVALID_IDX,
	RDMA_FEATURE_HW_VERSION_LOW,
	RDMA_FEATURE_HW_VERSION_HIGH,
	RDMA_FEATURE_ENDPT_TRK,
	RDMA_FEATURE_QSETS_MAX,
	RDMA_FEATURE_FW_VERSION,
	RDMA_CONFIG_PKEY,
	SXE2_VF_MAX_BAR_REGS,
};

enum sxe2_pf_bar_regs_idx {
	PF_INT_AEQCTL = SXE2_VF_MAX_BAR_REGS,
	PF_INT_CEQCTL,
	PF_INT_RATE,
	SXE2_PF_MAX_BAR_REGS,
};

enum sxe2_rdma_dyn_idx_t {
	SXE2_RDMA_IDX_ITR0  = 0,
	SXE2_RDMA_IDX_ITR1  = 1,
	SXE2_RDMA_IDX_ITR2  = 2,
	SXE2_RDMA_IDX_NOITR = 3,
};

#define SXE2_PFINT_AEQCTL_MSIX_INDEX_S 0
#define SXE2_PFINT_AEQCTL_MSIX_INDEX   GENMASK(10, 0)
#define SXE2_PFINT_AEQCTL_ITR_INDEX_S  11
#define SXE2_PFINT_AEQCTL_ITR_INDEX    GENMASK(12, 11)
#define SXE2_PFINT_AEQCTL_CAUSE_ENA_S  30
#define SXE2_PFINT_AEQCTL_CAUSE_ENA    BIT(30)

#define SXE2_GLINT_CEQCTL_MSIX_INDEX_S 0
#define SXE2_GLINT_CEQCTL_MSIX_INDEX   GENMASK(10, 0)
#define SXE2_GLINT_CEQCTL_ITR_INDEX_S  11
#define SXE2_GLINT_CEQCTL_ITR_INDEX    GENMASK(12, 11)
#define SXE2_GLINT_CEQCTL_CAUSE_ENA_S  30
#define SXE2_GLINT_CEQCTL_CAUSE_ENA    BIT(30)

#define SXE2_GLINT_DYN_CTL_INTENA_S    0
#define SXE2_GLINT_DYN_CTL_INTENA      BIT(0)
#define SXE2_GLINT_DYN_CTL_CLEARPBA_S  1
#define SXE2_GLINT_DYN_CTL_CLEARPBA    BIT(1)
#define SXE2_GLINT_DYN_CTL_ITR_INDEX_S 3
#define SXE2_GLINT_DYN_CTL_ITR_INDEX   GENMASK(4, 3)
#define SXE2_GLINT_DYN_CTL_INTERVAL_S  5
#define SXE2_GLINT_DYN_CTL_INTERVAL    GENMASK(16, 5)

enum sxe2_rdma_hw_stats_index {
	SXE2_RDMA_HW_STAT_INDEX_IP4TXOCTS = 0,
	SXE2_RDMA_HW_STAT_INDEX_IP4TXPKTS = 1,
	SXE2_RDMA_HW_STAT_INDEX_IP4TXMCOCTS =
		2,
	SXE2_RDMA_HW_STAT_INDEX_IP4TXMCPKTS =
		3,
	SXE2_RDMA_HW_STAT_INDEX_IP6TXOCTS = 4,
	SXE2_RDMA_HW_STAT_INDEX_IP6TXPKTS = 5,
	SXE2_RDMA_HW_STAT_INDEX_IP6TXMCOCTS =
		6,
	SXE2_RDMA_HW_STAT_INDEX_IP6TXMCPKTS =
		7,
	SXE2_RDMA_HW_STAT_INDEX_RDMATXWRS  = 8,
	SXE2_RDMA_HW_STAT_INDEX_RDMATXRDS  = 9,
	SXE2_RDMA_HW_STAT_INDEX_RDMATXSNDS = 10,
	SXE2_RDMA_HW_STAT_INDEX_RDMATXBND  = 11,
	SXE2_RDMA_HW_STAT_INDEX_RDMATXINV  = 12,
	SXE2_RDMA_HW_STAT_INDEX_TXCNPSENT  = 13,
	SXE2_RDMA_HW_STAT_INDEX_IP4RXOCTS = 14,
	SXE2_RDMA_HW_STAT_INDEX_IP4RXPKTS = 15,
	SXE2_RDMA_HW_STAT_INDEX_IP4RXDISCARD = 16,
	SXE2_RDMA_HW_STAT_INDEX_IP4RXMCOCTS = 17,
	SXE2_RDMA_HW_STAT_INDEX_IP4RXMCPKTS = 18,
	SXE2_RDMA_HW_STAT_INDEX_IP6RXOCTS = 19,
	SXE2_RDMA_HW_STAT_INDEX_IP6RXPKTS = 20,
	SXE2_RDMA_HW_STAT_INDEX_IP6RXDISCARD = 21,
	SXE2_RDMA_HW_STAT_INDEX_IP6RXMCOCTS = 22,
	SXE2_RDMA_HW_STAT_INDEX_IP6RXMCPKTS = 23,
	SXE2_RDMA_HW_STAT_INDEX_RDMARXWRS  = 24,
	SXE2_RDMA_HW_STAT_INDEX_RDMARXRDS  = 25,
	SXE2_RDMA_HW_STAT_INDEX_RDMARXSNDS = 26,
	SXE2_RDMA_HW_STAT_INDEX_RDMARXINV =
		27,
	SXE2_RDMA_HW_STAT_INDEX_RXECNMARKEDPKTS =
		28,
	SXE2_RDMA_HW_STAT_INDEX_RXCNPHANDLED = 29,
	SXE2_RDMA_HW_STAT_INDEX_RXCNPIGNORED = 30,
	SXE2_RDMA_HW_STAT_INDEX_RXNAKPKTS = 31,
	SXE2_RDMA_HW_STAT_INDEX_RXSEQERR = 32,
	SXE2_RDMA_HW_STAT_INDEX_RXRNRNAKPKTS = 33,
	SXE2_RDMA_HW_STAT_INDEX_RXRETRANS = 34,
	SXE2_RDMA_HW_STAT_INDEX_MAX	  = 35,
};

void sxe2_rdma_init_hw(struct sxe2_rdma_ctx_dev *dev);
void sxe2_hw_ena_irq(struct sxe2_rdma_ctx_dev *dev, u32 idx);
void sxe2_hw_disable_irq(struct sxe2_rdma_ctx_dev *dev, u32 idx);

void sxe2_hw_cfg_aeq(struct sxe2_rdma_ctx_dev *dev, u32 idx, bool enable);

void sxe2_hw_cfg_ceq(struct sxe2_rdma_ctx_dev *dev, u32 ceq_id, u32 idx,
		     bool enable);

#endif
