// SPDX-License-Identifier: GPL-2.0
/* Copyright (c) 2023 - 2024 ZTE Corporation */

#include <linux/dinghai/driver.h>
#include <linux/netdevice.h>
#include <linux/kref.h>
#include <linux/dinghai/lag.h>
#include <net/bonding.h>
#include "lag.h"
#include "en_pf.h"
#include "dpp_tbl_api.h"
#include "../en_aux.h"

static DEFINE_SPINLOCK(lag_lock);
static DEFINE_MUTEX(zxdh_intf_mutex);

void zxdh_dev_list_lock(void)
{
	mutex_lock(&zxdh_intf_mutex);
}

void zxdh_dev_list_unlock(void)
{
	mutex_unlock(&zxdh_intf_mutex);
}

int zxdh_dev_list_trylock(void)
{
	return mutex_trylock(&zxdh_intf_mutex);
}

struct zxdh_lag *lag_get_ldev(struct dh_core_dev *dh_dev)
{
	struct zxdh_pf_device *pf_dev = dh_core_priv(dh_dev);

	return pf_dev->ldev;
}

void lag_set_ldev(struct dh_core_dev *dh_dev, struct zxdh_lag *ldev)
{
	struct zxdh_pf_device *pf_dev = dh_core_priv(dh_dev);

	pf_dev->ldev = ldev;
}

void ldev_kref_free(struct kref *ref)
{
	struct zxdh_lag *ldev = container_of(ref, struct zxdh_lag, ref);

	if (ldev->nb.notifier_call)
		unregister_netdevice_notifier_net(&init_net, &ldev->nb);

	cancel_delayed_work_sync(&ldev->bond_work);
	destroy_workqueue(ldev->wq);

	lag_set_ldev(ldev->parent, NULL);
	kfree(ldev);

	LAG_LOG_INFO("pf lag device alloced memory free\n");
}

static void zxdh_queue_bond_work(struct zxdh_lag *ldev, unsigned long delay)
{
	queue_delayed_work(ldev->wq, &ldev->bond_work, delay);
}

void lag_dev_release(struct dh_core_dev *dh_dev, struct zxdh_lag *ldev)
{
	int i;
	struct dh_core_dev *parent;

	for (i = 0; i < ZXDH_MAX_PORTS; i++) {
		if (!ldev->lagfunc[i].dev)
			continue;

		parent = ldev->lagfunc[i].dev->parent;
		if (parent == dh_dev)
			ldev->lagfunc[i].dev = NULL;
	}
}

/**
 * lag_get_netdev_idx - get the index of netdev generated by en_aux
 * @ldev: zxdh lag dev
 * @ndev: netdev to search for
 */
s32 lag_get_netdev_idx(struct zxdh_lag *ldev, struct net_device *ndev)
{
	int i;

	for (i = 0; i < ZXDH_MAX_PORTS; i++) {
		if (ldev->lagfunc[i].netdev == ndev)
			return i;
	}

	return -ENOENT;
}

void ldev_remove_netdev(struct dh_core_dev *dh_dev, struct net_device *netdev)
{
	s32 index = 0;
	struct zxdh_lag *ldev;

	ldev = lag_get_ldev(dh_dev->parent);
	if (!ldev)
		return;

	spin_lock(&lag_lock);

	index = lag_get_netdev_idx(ldev, netdev);
	if (index < 0)
		goto out;

	ldev->lagfunc[index].netdev = NULL;
out:
	spin_unlock(&lag_lock);
}

/**
 * ldev_add_netdev - add net_device to lag dev
 * @dev: zxdh core device
 * @id: the index that joined to ldev
 * @netdev: netdev to adding for
 * @attr: some configs info from aux
 */
static void ldev_add_netdev(struct dh_core_dev *dh_dev, u16 id, struct net_device *netdev,
			    struct zxdh_lag_attrs *attr)
{
	struct zxdh_lag *ldev;

	if (id >= ZXDH_MAX_PORTS) {
		LAG_LOG_ERR("%s: index[%hu] out of range.\n", netdev_name(netdev), id);
		return;
	}

	ldev = lag_get_ldev(dh_dev->parent);

	spin_lock(&lag_lock);
	ldev->lagfunc[id].dev = dh_dev;
	ldev->lagfunc[id].netdev = netdev;
	ldev->lagfunc[id].attrs = *attr;
	ldev->lagfunc[id].valid = true;
	ldev->tracker.netdev_state[id].link_up = 0;
	ldev->tracker.netdev_state[id].tx_enabled = 0;
	ldev->lag_func_index++;
	spin_unlock(&lag_lock);

	zxdh_queue_bond_work(ldev, 0);
}

static bool zxdh_netdev_belongs(struct zxdh_lag *ldev, struct net_device *netdev)
{
	s32 idx = 0;

	idx = lag_get_netdev_idx(ldev, netdev);
	if (idx < 0)
		return false;

	return true;
}

/**
 * handle_changeupper_event - handle change upper device event
 * @ldev: zxdh lag dev
 * @tracker: the tracker of zxdh lag dev
 * @ndev: upper netdev
 * @info: upper dev attribute passed from bonding
 */
static int handle_changeupper_event(struct zxdh_lag *ldev, struct lag_tracker *tracker,
				    struct net_device *ndev,
				    struct netdev_notifier_changeupper_info *info)
{
	struct net_device *upper = info->upper_dev, *ndev_tmp, *slave_dev;
	struct netdev_lag_upper_info *lag_upper_info = NULL;
	bool is_bonded = false;
	bool mode_supported = false;
	int changed = 0;
	int bond_status = 0;
	int num_slaves = 0;
	int idx = 0;

	if (!netif_is_lag_master(upper)) {
		LAG_LOG_INFO("changeupper received, but not master.\n");
		return 0;
	}

	slave_dev = netdev_notifier_info_to_dev((void *)info);
	if (!zxdh_netdev_belongs(ldev, slave_dev)) {
		LAG_LOG_INFO("%s is not dinghai bond, ignore.\n", upper->name);
		return 0;
	}

	if (info->linking)
		lag_upper_info = info->upper_info;

	rcu_read_lock();
	for_each_netdev_in_bond_rcu(upper, ndev_tmp) {
		idx = lag_get_netdev_idx(ldev, ndev_tmp);
		if (idx >= 0)
			bond_status |= (1 << idx);

		num_slaves++;
	}
	rcu_read_unlock();

	ldev->slaves = bond_status;

	/* None of this lagdev's netdevs are slaves of this master. */
	if (!bond_status) {
		is_bonded = false;
		goto out;
	}

	if (lag_upper_info) {
		tracker->tx_type = lag_upper_info->tx_type;
		tracker->hash_type = lag_upper_info->hash_type;
	}

	LAG_LOG_INFO("lag tx type: %d [%d-active-backup %d-hash], hash type %d.\n",
		     tracker->tx_type, NETDEV_LAG_TX_TYPE_ACTIVEBACKUP, NETDEV_LAG_TX_TYPE_HASH,
		     tracker->hash_type);

	/* Lag mode must be activebackup or hash. */
	mode_supported = (tracker->tx_type == NETDEV_LAG_TX_TYPE_ACTIVEBACKUP) ||
			 (tracker->tx_type == NETDEV_LAG_TX_TYPE_HASH);

	/* if slaves exist */
	is_bonded = !!bond_status && mode_supported;

out:
	if (tracker->is_bonded != is_bonded) {
		tracker->is_bonded = is_bonded;
		changed = 1;
	}

	LAG_LOG_INFO("master: %s slaves num: %d, mask: 0x%x, changed: %d, mode supported: %s\n",
		     upper->name, num_slaves, bond_status, changed,
		     mode_supported ? "true" : "false");

	return changed;
}

/**
 * handle_changelowerstate_event - handle changed lower device state event
 * @ldev: zxdh lag dev
 * @tracker: the tracker of zxdh lag dev
 * @ndev: lower netdev
 * @info: lower dev attribute passed from bonding
 */
static int handle_changelowerstate_event(struct zxdh_lag *ldev, struct lag_tracker *tracker,
					 struct net_device *ndev,
					 struct netdev_notifier_changelowerstate_info *info)
{
	struct netdev_lag_lower_state_info *lag_lower_info;
	int idx;

	if (!netif_is_lag_port(ndev))
		return 0;

	idx = lag_get_netdev_idx(ldev, ndev);
	if (idx < 0)
		return 0;

	lag_lower_info = info->lower_state_info;
	if (!lag_lower_info)
		return 0;

	/* update netdev state from bonding */
	tracker->netdev_state[idx] = *lag_lower_info;

	LAG_LOG_INFO("%s: link up %u tx enable %u\n", ndev->name, (u32)lag_lower_info->link_up,
		     (u32)lag_lower_info->tx_enabled);

	return 1;
}

bool lag_check_aux_netdev_ready(struct zxdh_lag *ldev)
{
	int ix = 0;
	int lag_netdev_cnt = 0;
	int lag_pannel_num = zxdh_pf_get_pannel_port_num(ldev->parent);

	for (ix = 0; ix < ZXDH_MAX_PORTS; ix++) {
		if (ldev->lagfunc[ix].netdev)
			lag_netdev_cnt++;
	}

	return (lag_pannel_num == lag_netdev_cnt) ? true : false;
}

static int lag_netdev_event(struct notifier_block *this, unsigned long event, void *ptr)
{
	struct net_device *ndev = netdev_notifier_info_to_dev(ptr);
	struct lag_tracker tracker;
	struct zxdh_lag *ldev = NULL;
	int changed = 0;

	if (event != NETDEV_CHANGEUPPER && event != NETDEV_CHANGELOWERSTATE)
		return NOTIFY_DONE;

	ldev = container_of(this, struct zxdh_lag, nb);
	if (!lag_check_aux_netdev_ready(ldev))
		return NOTIFY_DONE;

	LAG_LOG_INFO("received %s\n", netdev_cmd_to_name(event));

	tracker = ldev->tracker;

	switch (event) {
	case NETDEV_CHANGEUPPER: {
		changed = handle_changeupper_event(ldev, &tracker, ndev, ptr);
		break;
	}
	case NETDEV_CHANGELOWERSTATE: {
		changed = handle_changelowerstate_event(ldev, &tracker, ndev, ptr);
		break;
	}
	}

	ldev->tracker = tracker;

	if (changed)
		zxdh_queue_bond_work(ldev, 0);

	return NOTIFY_DONE;
}

static s32 lag_find_first_netdev_pf_info(struct zxdh_lag *ldev, struct dpp_pf_info_t *pf_info)
{
	int i;
	struct lag_func *func;

	for (i = 0; i < ZXDH_MAX_PORTS; i++) {
		func = &ldev->lagfunc[i];

		if (func->netdev) {
			pf_info->vport = func->attrs.vport;
			pf_info->slot = func->attrs.slot_id;
			return 0;
		}
	}

	return -EOPNOTSUPP;
}

static s32 zxdh_disable_lag(struct zxdh_lag *ldev)
{
	int i;
	u8 phy_port = 0;
	struct lag_func *func;
	struct dpp_pf_info_t pf_info = { 0 };

	for (i = 0; i < ZXDH_MAX_PORTS; i++) {
		func = &ldev->lagfunc[i];

		if (!func->netdev)
			continue;

		pf_info.slot = func->attrs.slot_id;
		pf_info.vport = func->attrs.vport;
		phy_port = func->attrs.phy_port;

		dpp_lag_group_member_del(&pf_info, ldev->lag_id, phy_port);
		dpp_uplink_phy_attr_set(&pf_info, phy_port, UPLINK_PHY_PORT_BOND_LINK_UP,
					LAG_FLAGS_DISABLE);
	}

	ldev->flags &= ~ZXDH_LAG_MODE_FLAGS;
	LAG_LOG_INFO("zxdh lag disabled. vport 0x%hx lag id %d.\n", pf_info.vport, ldev->lag_id);

	return 0;
}

static s32 zxdh_lag_active_backup(struct zxdh_lag *ldev)
{
	int i;
	bool porten = false;
	u8 phy_port = ZXDH_ACTIVE_PHY_PORT_NA;
	u8 active_phy_port = ZXDH_ACTIVE_PHY_PORT_NA;
	s32 err = 0;
	struct lag_func *func;
	struct lag_tracker *tracker = &ldev->tracker;
	struct dpp_pf_info_t pf_info = { 0 };

	err = lag_find_first_netdev_pf_info(ldev, &pf_info);
	if (err != 0) {
		LAG_LOG_ERR("vport %d is incorrect\n", pf_info.vport);
		return -EOPNOTSUPP;
	}

	dpp_lag_mode_set(&pf_info, ldev->lag_id, LAG_MODE_ACTIVE_BACKUP);

	for (i = ZXDH_MAX_PORTS - 1; i >= 0; i--) {
		func = &ldev->lagfunc[i];

		if (!func->netdev)
			continue;

		phy_port = func->attrs.phy_port;
		pf_info.slot = func->attrs.slot_id;
		pf_info.vport = func->attrs.vport;

		dpp_lag_group_member_del(&pf_info, ldev->lag_id, phy_port);
		dpp_uplink_phy_attr_set(&pf_info, phy_port, UPLINK_PHY_PORT_BOND_LINK_UP,
					LAG_FLAGS_DISABLE);

		porten = tracker->netdev_state[i].tx_enabled && tracker->netdev_state[i].link_up;
		if (porten && (ldev->slaves & (1 << i))) {
			active_phy_port = phy_port;
			LAG_LOG_INFO("lag_id %u: select active phyport %hu pannel port %hu\n",
				     ldev->lag_id, active_phy_port, func->attrs.pannel_id);
		}

		LAG_LOG_INFO("lag_id %u: phyport %hhu pannel port %hhu tx enable %d link up %d\n",
			     ldev->lag_id, phy_port, func->attrs.pannel_id,
			     (s32)tracker->netdev_state[i].tx_enabled,
			     (s32)tracker->netdev_state[i].link_up);
	}

	if (active_phy_port != ZXDH_ACTIVE_PHY_PORT_NA) {
		dpp_lag_group_member_add(&pf_info, ldev->lag_id, active_phy_port);
		dpp_uplink_phy_attr_set(&pf_info, active_phy_port, UPLINK_PHY_PORT_BOND_LINK_UP,
					LAG_FLAGS_ENABLE);
	}

	ldev->flags |= ZXDH_LAG_FLAG_BACKUP;

	return 0;
}

u32 zxdh_covert_hash_type_2_np(u32 hash_type)
{
	u32 np_hash_type = 0;

	switch (hash_type) {
	case NETDEV_LAG_HASH_L2: {
		np_hash_type = ZXDH_NP_HASH_TYPE_L2;
		break;
	}
	case NETDEV_LAG_HASH_L23: {
		np_hash_type = ZXDH_NP_HASH_TYPE_L23;
		break;
	}
	case NETDEV_LAG_HASH_L34: {
		np_hash_type = ZXDH_NP_HASH_TYPE_L34;
		break;
	}
	default: {
		np_hash_type = ZXDH_NP_HASH_TYPE_DEFAULT;
		break;
	}
	}

	return np_hash_type;
}

static s32 zxdh_lag_hash(struct zxdh_lag *ldev)
{
	int i;
	bool porten = false;
	u8 phy_port = 0;
	u8 flags = 0;
	u32 np_hash_type = 0;
	s32 err = 0;
	struct lag_func *func;
	struct lag_tracker *tracker = &ldev->tracker;
	struct dpp_pf_info_t pf_info = { 0 };

	err = lag_find_first_netdev_pf_info(ldev, &pf_info);
	if (err != 0) {
		LAG_LOG_ERR("vport %d is incorrect\n", pf_info.vport);
		return -EOPNOTSUPP;
	}

	np_hash_type = ZXDH_NP_HASH_TYPE_L34;

	dpp_lag_group_hash_factor_set(&pf_info, ldev->lag_id, (u8)np_hash_type);
	dpp_lag_mode_set(&pf_info, ldev->lag_id, LAG_MODE_802_3AD);

	for (i = 0; i < ZXDH_MAX_PORTS; i++) {
		func = &ldev->lagfunc[i];

		if (!func->netdev)
			continue;

		phy_port = func->attrs.phy_port;
		pf_info.slot = func->attrs.slot_id;
		pf_info.vport = func->attrs.vport;

		porten = tracker->netdev_state[i].tx_enabled && tracker->netdev_state[i].link_up;
		if (porten && (ldev->slaves & (1 << i))) {
			dpp_lag_group_member_add(&pf_info, ldev->lag_id, phy_port);
			dpp_uplink_phy_attr_set(&pf_info, phy_port, UPLINK_PHY_PORT_BOND_LINK_UP,
						LAG_FLAGS_ENABLE);
			flags = LAG_FLAGS_ENABLE;
		} else {
			dpp_lag_group_member_del(&pf_info, ldev->lag_id, phy_port);
			dpp_uplink_phy_attr_set(&pf_info, phy_port, UPLINK_PHY_PORT_BOND_LINK_UP,
						LAG_FLAGS_DISABLE);
			flags = LAG_FLAGS_DISABLE;
		}

		LAG_LOG_INFO(
			"lag_id %u,hash:%s,vport:%hu,pan_port %hu,phy_port %hu,mask:0x%x,enable:%d,up:%d\n",
			ldev->lag_id, (flags == LAG_FLAGS_ENABLE) ? "enable" : "disable",
			pf_info.vport, func->attrs.pannel_id, phy_port, ldev->slaves,
			(s32)tracker->netdev_state[i].tx_enabled,
			(s32)tracker->netdev_state[i].link_up);
	}

	ldev->flags |= ZXDH_LAG_FLAG_HASH;

	return 0;
}

static void zxdh_lagtracker_info(struct lag_tracker *tracker)
{
	const char *bond_tx_mode, *bonded, *hash_type;

	bonded = tracker->is_bonded ? "BONDED" : "UNBONDED";

	switch (tracker->tx_type) {
	case NETDEV_LAG_TX_TYPE_HASH: {
		bond_tx_mode = "HASH";
		break;
	}
	case NETDEV_LAG_TX_TYPE_ACTIVEBACKUP: {
		bond_tx_mode = "ACTIVE-BACKUP";
		break;
	}
	default: {
		bond_tx_mode = "UNKNOWN";
	}
	}

	switch (tracker->hash_type) {
	case ZXDH_NP_HASH_TYPE_L2: {
		hash_type = "layer2";
		break;
	}
	case ZXDH_NP_HASH_TYPE_L23: {
		hash_type = "layer2+3";
		break;
	}
	case ZXDH_NP_HASH_TYPE_L34: {
		hash_type = "layer2+3";
		break;
	}
	default: {
		hash_type = "layer2";
	}
	}

	LAG_LOG_INFO("%s: tx type: %s, hash type %s.\n", bonded, bond_tx_mode, hash_type);
}

static void do_bond(struct zxdh_lag *ldev)
{
	bool do_bond;
	struct lag_tracker *tracker = &ldev->tracker;
	struct lag_func *func;
	struct zxdh_en_priv *en_priv = NULL;
	struct zxdh_en_device *en_dev = NULL;
	s32 i = 0;

	for (i = 0; i < ZXDH_MAX_PORTS; i++) {
		func = &ldev->lagfunc[i];

		if (func->netdev) {
			en_priv = netdev_priv(func->netdev);
			en_dev = &en_priv->edev;
			if (en_dev->device_state == ZXDH_DEVICE_STATE_INTERNAL_ERROR)
				return;
		}
	}

	zxdh_lagtracker_info(tracker);

	do_bond = tracker->is_bonded;

	if (do_bond && lag_is_backup(ldev))
		zxdh_lag_active_backup(ldev);
	else if (do_bond && lag_is_hash(ldev))
		zxdh_lag_hash(ldev);
	else
		zxdh_disable_lag(ldev);
}

static void zxdh_do_bond_work(struct work_struct *work)
{
	struct delayed_work *delayed_work = to_delayed_work(work);
	struct zxdh_lag *ldev = container_of(delayed_work, struct zxdh_lag, bond_work);
	int status;

	status = zxdh_dev_list_trylock();
	if (!status) {
		zxdh_queue_bond_work(ldev, HZ);
		return;
	}

	do_bond(ldev);
	zxdh_dev_list_unlock();
}

static struct zxdh_lag *lag_dev_alloc(struct dh_core_dev *dev)
{
	struct zxdh_pf_device *pf_dev = dh_core_priv(dev);
	struct zxdh_lag *ldev = NULL;
	char name[ETH_GSTRING_LEN];

	ldev = kzalloc(sizeof(*ldev), GFP_KERNEL);
	if (!ldev) {
		LAG_LOG_ERR("Failed to alloc ldev\n");
		return NULL;
	}

	ldev->parent = dev;
	ldev->lag_id = pf_dev->port_resource.bond_idx;
	if (snprintf(name, ETH_GSTRING_LEN, "zxdh_lag%d", ldev->lag_id) < 0) {
		LAG_LOG_ERR("Failed to snprintf ldev name!\n");
		kfree(ldev);
		return NULL;
	}

	ldev->wq = create_singlethread_workqueue(name);
	if (!ldev->wq) {
		kfree(ldev);
		return NULL;
	}

	kref_init(&ldev->ref);
	INIT_DELAYED_WORK(&ldev->bond_work, zxdh_do_bond_work);

	ldev->nb.notifier_call = lag_netdev_event;
	if (register_netdevice_notifier_net(&init_net, &ldev->nb)) {
		ldev->nb.notifier_call = NULL;
		LAG_LOG_ERR("Failed to register LAG netdev notifier\n");
	}

	return ldev;
}

static int lag_dev_create(struct dh_core_dev *dh_dev)
{
	struct zxdh_lag *ldev = NULL;

	ldev = lag_get_ldev(dh_dev);
	if (!ldev) {
		ldev = lag_dev_alloc(dh_dev);
		if (!ldev) {
			LAG_LOG_ERR("Failed to alloc lag dev.\n");
			return 0;
		}
	} else {
		get_ldev_kref(ldev);
	}

	lag_set_ldev(dh_dev, ldev);

	return 0;
}

s32 lag_dpp_pannel_init(struct dh_core_dev *dh_dev, struct zxdh_lag_attrs *attr)
{
	struct zxdh_lag *ldev = lag_get_ldev(dh_dev->parent);
	u16 pannel_id = attr->pannel_id;
	u16 pf_id = (attr->pcie_id >> 8) & PCIE_ID_PF_INDEX_MASK;
	u16 ep_id = (attr->pcie_id >> 12) & PCIE_ID_EP_INDEX_MASK;
	u16 bond_vfid = ZXDH_PF_VFID(ep_id, pf_id);
	u16 ovs_vfid = ZXDH_PF_VFID(ep_id, (pf_id + 1));
	u8 phy_port = attr->phy_port;
	struct dpp_pf_info_t pf_info = { 0 };
	s32 ret = 0;

	pf_info.slot = attr->slot_id;
	pf_info.vport = attr->vport;
	dpp_uplink_phy_bond_vport(&pf_info, phy_port);
	dpp_uplink_phy_lacp_pf_vqm_vfid_set(&pf_info, phy_port, bond_vfid);
	dpp_uplink_phy_lacp_pf_memport_qid_set(&pf_info, phy_port, attr->qid[0]);
	dpp_uplink_phy_attr_set(&pf_info, phy_port, UPLINK_PHY_PORT_PF_VQM_VFID, ovs_vfid);

	dpp_uplink_phy_hardware_bond_set(&pf_info, phy_port, LAG_FLAGS_ENABLE);
	ret = dpp_vport_attr_set(&pf_info, SRIOV_VPORT_HW_BOND_EN_OFF, LAG_FLAGS_ENABLE);
	if (ret != 0) {
		LOG_ERR("dpp_vport_attr_set SRIOV_VPORT_HW_BOND_EN_OFF LAG_FLAGS_ENABLE failed\n");
		return ret;
	}

	dpp_lag_group_create(&pf_info, ldev->lag_id);

	LAG_LOG_INFO(
		"vport 0x%hx, pannel id %hu, phy port %hu, rx qid %hu tx qid %hu bond vfid %d, ovs vfid %d, lag_id %d\n",
		pf_info.vport, pannel_id, phy_port, attr->qid[0], attr->qid[1], bond_vfid, ovs_vfid,
		ldev->lag_id);

	return 0;
}

s32 lag_dpp_pannel_release(struct zxdh_lag_attrs *attr)
{
	u8 phy_port = attr->phy_port;
	struct dpp_pf_info_t pf_info = { 0 };
	s32 ret = 0;

	pf_info.slot = attr->slot_id;
	pf_info.vport = attr->vport;
	dpp_uplink_phy_hardware_bond_set(&pf_info, phy_port, LAG_FLAGS_DISABLE);
	ret = dpp_vport_attr_set(&pf_info, SRIOV_VPORT_HW_BOND_EN_OFF, LAG_FLAGS_DISABLE);
	if (ret != 0) {
		LOG_ERR("dpp_vport_attr_set SRIOV_VPORT_HW_BOND_EN_OFF LAG_FLAGS_DISABLE failed\n");
		return ret;
	}

	return 0;
}

s32 lag_netdev_input_check(struct dh_core_dev *dh_dev, struct zxdh_lag_attrs *attr)
{
	struct zxdh_lag *ldev;

	if (!dh_core_is_pf(dh_dev->parent)) {
		LAG_LOG_ERR("dh_core_dev type PF needs to be used\n");
		return -EINVAL;
	}

	ldev = lag_get_ldev(dh_dev->parent);
	if (!ldev) {
		LAG_LOG_ERR("ldev can not be null\n");
		return -EINVAL;
	}

	if (attr->pannel_id >= ZXDH_MAX_PORTS) {
		LAG_LOG_ERR("pannel id %hu out of range.\n", attr->pannel_id);
		return -EINVAL;
	}

	return 0;
}

/**
 * zxdh_regitster_ldev - create lagdev and add to dh core dev
 * @dh_dev: zxdh lag dev
 * the function called by pf driver
 */
void zxdh_regitster_ldev(struct dh_core_dev *dh_dev)
{
	zxdh_dev_list_lock();
	lag_dev_create(dh_dev);
	zxdh_dev_list_unlock();
}

void zxdh_unregitster_ldev(struct dh_core_dev *dh_dev)
{
	struct zxdh_lag *ldev;

	zxdh_dev_list_lock();
	ldev = lag_get_ldev(dh_dev);
	if (!ldev) {
		zxdh_dev_list_unlock();
		return;
	}

	lag_dev_release(dh_dev, ldev);
	put_ldev_kref(ldev);

	zxdh_dev_list_unlock();
}

/**
 * zxdh_ldev_add_netdev - add net device to lag device
 * @dh_dev: sf core dev
 * @ida: netdev idx
 * @netdev: the net device which en aux created
 * @attr: netdev info
 * this function may called by en aux
 */
s32 zxdh_ldev_add_netdev(struct dh_core_dev *dh_dev, u16 ida, struct net_device *netdev,
			 struct zxdh_lag_attrs *attr)
{
	s32 ret = 0;

	zxdh_dev_list_lock();
	ret = lag_netdev_input_check(dh_dev, attr);
	if (ret != 0) {
		zxdh_dev_list_unlock();
		return -EINVAL;
	}

	lag_dpp_pannel_init(dh_dev, attr);
	ldev_add_netdev(dh_dev, ida, netdev, attr);
	zxdh_dev_list_unlock();

	return 0;
}
EXPORT_SYMBOL(zxdh_ldev_add_netdev);

void zxdh_ldev_remove_netdev(struct dh_core_dev *dh_dev, struct net_device *netdev,
			     struct zxdh_lag_attrs *attr)
{
	zxdh_dev_list_lock();

	lag_dpp_pannel_release(attr);
	ldev_remove_netdev(dh_dev, netdev);
	zxdh_dev_list_unlock();
}
EXPORT_SYMBOL(zxdh_ldev_remove_netdev);
