/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2023-2025. All rights reserved.
 *
 * Description: ubcore opcode header file
 * Author: Qian Guoxin, Ouyang Changchun
 * Create: 2023-2-28
 * Note:
 * History: 2023-2-28: Create file
 */

#ifndef UBCORE_OPCODE_H
#define UBCORE_OPCODE_H

/* Indicates the verification policy of the key. */
#define UBCORE_TOKEN_NONE 0
#define UBCORE_TOKEN_PLAIN_TEXT 1
#define UBCORE_TOKEN_SIGNED 2
#define UBCORE_TOKEN_ALL_ENCRYPTED 3
#define UBCORE_TOKEN_RESERVED 4

#define UBCORE_TOKEN_ID_INVALID 0
#define UBCORE_TOKEN_ID_VALID 1

/* Indicates whether the segment can be cached by multiple hosts. */
#define UBCORE_NON_CACHEABLE 0
#define UBCORE_CACHEABLE 1

/* Indicates that the current process has mapped this segment */
#define UBCORE_SEG_NOMAP 0
#define UBCORE_SEG_MAPPED 1

/* Notify the source after the task is completed. */
#define UBCORE_COMPLETE_ENABLE 1
/* Do not notify the source after the task is complete. */
#define UBCORE_COMPLETE_DISABLE 0

/* There is no interruption when notifying through JFC. */
#define UBCORE_SOLICITED_DISABLE 0
/* Interrupt occurred while notifying via JFC. */
#define UBCORE_SOLICITED_ENABLE 1

/* There is no fence. */
#define UBCORE_FENCE_DISABLE 0
/* Fence with previous WRs. */
#define UBCORE_FENCE_ENABLE 1

/* The data is generated by source_address assignment. */
#define UBCORE_INLINE_DISABLE 0
/* The data is carried in the command. */
#define UBCORE_INLINE_ENABLE 1

#define UBCORE_NO_SHARE_JFR 0
#define UBCORE_SHARE_JFR 1

/* opcode definition */
/* Must be consistent with urma_opcode_t */
enum ubcore_opcode {
	UBCORE_OPC_WRITE = 0x00,
	UBCORE_OPC_WRITE_IMM = 0x01,
	UBCORE_OPC_WRITE_NOTIFY = 0x02,
	UBCORE_OPC_READ = 0x10,
	UBCORE_OPC_CAS = 0x20,
	UBCORE_OPC_SWAP = 0x21,
	UBCORE_OPC_FADD = 0x22,
	UBCORE_OPC_FSUB = 0x23,
	UBCORE_OPC_FAND = 0x24,
	UBCORE_OPC_FOR = 0x25,
	UBCORE_OPC_FXOR = 0x26,
	UBCORE_OPC_SEND = 0x40, // remote JFR/jetty ID
	UBCORE_OPC_SEND_IMM = 0x41, // remote JFR/jetty ID
	UBCORE_OPC_SEND_INVALIDATE =
		0x42, // remote JFR/jetty ID and seg token id
	UBCORE_OPC_NOP = 0x51,
	UBCORE_OPC_WRITE_ATOMIC = 0x60,
	UBCORE_OPC_FLUSH_DMA = 0x80,
	UBCORE_OPC_LAST
};

/* completion information */
/* Must be consistent with urma_cr_status_t */
enum ubcore_cr_status { // completion record status
	UBCORE_CR_SUCCESS = 0,
	UBCORE_CR_UNSUPPORTED_OPCODE_ERR,
	UBCORE_CR_LOC_LEN_ERR, // Local data too long error
	UBCORE_CR_LOC_OPERATION_ERR, // Local operation err
	UBCORE_CR_LOC_ACCESS_ERR, // Access to local memory error when WRITE_WITH_IMM
	UBCORE_CR_REM_RESP_LEN_ERR,
	UBCORE_CR_REM_UNSUPPORTED_REQ_ERR,
	UBCORE_CR_REM_OPERATION_ERR,
	/* Memory access protection error occurred in the remote node */
	UBCORE_CR_REM_ACCESS_ABORT_ERR,
	UBCORE_CR_ACK_TIMEOUT_ERR,
	/* RNR retries exceeded the maximum number: remote jfr has no buffer */
	UBCORE_CR_RNR_RETRY_CNT_EXC_ERR,
	UBCORE_CR_FLUSH_ERR,
	UBCORE_CR_WR_SUSPEND_DONE,
	UBCORE_CR_WR_FLUSH_ERR_DONE,
	UBCORE_CR_WR_UNHANDLED,
	UBCORE_CR_LOC_DATA_POISON,
	UBCORE_CR_REM_DATA_POISON
};

/* Must be consistent with urma_cr_opcode_t */
enum ubcore_cr_opcode {
	UBCORE_CR_OPC_SEND = 0x00,
	UBCORE_CR_OPC_SEND_WITH_IMM,
	UBCORE_CR_OPC_SEND_WITH_INV,
	UBCORE_CR_OPC_WRITE_WITH_IMM,
	UBCORE_CR_OPC_FLUSH_WRITE
};

enum ubcore_slice {
	UBCORE_SLICE_32K = 1 << 15,
	UBCORE_SLICE_64K = 1 << 16,
	UBCORE_SLICE_128K = 1 << 17,
	UBCORE_SLICE_256K = 1 << 18
};

/* JFS Options */
#define UBCORE_JFS_OPT            (0x0000)
#define UBCORE_JFS_DEPTH          (0x0001)
#define UBCORE_JFS_FLAG           (0x0002)
#define UBCORE_JFS_TRANS_MODE     (0x0003)
#define UBCORE_JFS_PRIORITY       (0x0004)
#define UBCORE_JFS_MAX_SGE        (0x0005)
#define UBCORE_JFS_MAX_RSGE       (0x0006)
#define UBCORE_JFS_MAX_INLINE_DATA (0x0007)
#define UBCORE_JFS_RNR_RETRY      (0x0008)
#define UBCORE_JFS_ERR_TIMEOUT    (0x0009)
#define UBCORE_JFS_BIND_JFC       (0x000a)
#define UBCORE_JFS_USER_CTX       (0x000b)
#define UBCORE_JFS_SQE_BASE_ADDR  (0x000c)
#define UBCORE_JFS_ID             (0x000d)
#define UBCORE_JFS_DB_ADDR        (0x000e)
#define UBCORE_JFS_DB_STATUS      (0x000f)
#define UBCORE_JFS_PI             (0x0010)
#define UBCORE_JFS_PI_TYPE        (0x0011)
#define UBCORE_JFS_CI             (0x0012)
#define UBCORE_JFS_FULL_CTX       (0x0013)

/* JFR Options */
#define UBCORE_JFR_OPT            (0x1000)
#define UBCORE_JFR_DEPTH          (0x1001)
#define UBCORE_JFR_FLAG           (0x1002)
#define UBCORE_JFR_TRANS_MODE     (0x1003)
#define UBCORE_JFR_MAX_SGE        (0x1004)
#define UBCORE_JFR_MIN_RNR_TIMER  (0x1005)
#define UBCORE_JFR_BIND_JFC       (0x1006)
#define UBCORE_JFR_TOKEN_VALUE    (0x1007)
#define UBCORE_JFR_USER_CTX       (0x1008)
#define UBCORE_JFR_RQE_BASE_ADDR  (0x1009)
#define UBCORE_JFR_ID             (0x100a)
#define UBCORE_JFR_DB_ADDR        (0x100b)
#define UBCORE_JFR_DB_STATUS      (0x100c)
#define UBCORE_JFR_PI             (0x100d)
#define UBCORE_JFR_PI_TYPE        (0x100e)
#define UBCORE_JFR_CI             (0x100f)
#define UBCORE_JFR_FULL_CTX       (0x1010)

/* JFC Options */
#define UBCORE_JFC_OPT            (0x2000)
#define UBCORE_JFC_DEPTH          (0x2001)
#define UBCORE_JFC_CEQN           (0x2002)
#define UBCORE_JFC_FLAG           (0x2003)
#define UBCORE_JFC_BIND_JFCE      (0x2004)
#define UBCORE_JFC_USER_CTX       (0x2005)
#define UBCORE_JFC_CQE_BASE_ADDR  (0x2006)
#define UBCORE_JFC_ID             (0x2007)
#define UBCORE_JFC_DB_ADDR        (0x2008)
#define UBCORE_JFC_DB_STATUS      (0x2009)
#define UBCORE_JFC_PI             (0x200a)
#define UBCORE_JFC_PI_TYPE        (0x200b)
#define UBCORE_JFC_CI             (0x200c)
#define UBCORE_JFC_FULL_CTX       (0x200d)

/* JETTY Options */
#define UBCORE_JETTY_OPT          (0x3000)
#define UBCORE_JETTY_ID           (0x3001)
#define UBCORE_JETTY_FLAG         (0x3002)
#define UBCORE_JETTY_BIND_JFR     (0x3003)
#define UBCORE_JETTY_BIND_RX_JFC  (0x3004)
#define UBCORE_JETTY_BIND_JTG     (0x3005)
#define UBCORE_JETTY_FULL_CTX     (0x3007)

#endif
