# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the Linux kernel UB device drivers.
#

uburma-objs := uburma_main.o \
			uburma_dev_ops.o \
			uburma_cmd.o \
			uburma_cdev_file.o \
			uburma_uobj.o

obj-$(CONFIG_UB) += uburma.o
