# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the Linux kernel UB device drivers.
#

uburma-objs := uburma_main.o \
			uburma_dev_ops.o \
			uburma_cmd.o \
			uburma_event.o \
			uburma_uobj.o \
			uburma_log.o \
			uburma_mmap.o

obj-$(CONFIG_UB_URMA) += uburma.o
