/* SPDX-License-Identifier: GPL-2.0+ WITH Linux-syscall-note */
/*
 * Copyright (c) HiSilicon Technologies Co., Ltd. 2026. All rights reserved.
 */

#ifndef _UAPI_UB_UBUS_UB_MEMORY_EVENT_H_
#define _UAPI_UB_UBUS_UB_MEMORY_EVENT_H_

enum ras_err_type {
	UB_MEM_ATOMIC_DATA_ERR = 0,
	UB_MEM_READ_DATA_ERR,
	UB_MEM_FLOW_POISON,
	UB_MEM_FLOW_READ_AUTH_POISON,
	UB_MEM_FLOW_READ_AUTH_RESPERR,
	UB_MEM_TIMEOUT_POISON,
	UB_MEM_TIMEOUT_RESPERR,
	UB_MEM_READ_DATA_POISON,
	UB_MEM_READ_DATA_RESPERR,
	MAR_NOPORT_VLD_INT_ERR,
	MAR_FLUX_INT_ERR,
	MAR_WITHOUT_CXT_ERR,
	RSP_BKPRE_OVER_TIMEOUT_ERR,
	MAR_NEAR_AUTH_FAIL_ERR,
	MAR_FAR_AUTH_FAIL_ERR,
	MAR_TIMEOUT_ERR,
	MAR_ILLEGAL_ACCESS_ERR,
	REMOTE_READ_DATA_ERR_OR_WRITE_RESPONSE_ERR,
#ifndef __GENKSYMS__
	UB_MEM_PORT_WARNING,
	UB_MEM_PORT_RECOVERY,
#endif
};

#endif /* _UAPI_UB_UBUS_UB_MEMORY_EVENT_H_ */
