#*******************************************************************************
#*******************************************************************************

include_directories(${CMAKE_CURRENT_SOURCE_DIR})

#*******************************************************************************
#*******************************************************************************

aux_source_directory(.          LOADER_SRC)

#*******************************************************************************
#*******************************************************************************

add_library(loader ${LOADER_SRC})
target_link_libraries(loader infra
                             numa
                             securec)

