# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_PSWIOTLB)			+= pswiotlb.o
obj-$(CONFIG_PSWIOTLB)			+= pswiotlb-mapping.o
obj-$(CONFIG_PSWIOTLB)			+= pswiotlb-direct.o
obj-$(CONFIG_PSWIOTLB)			+= pswiotlb-iommu.o
