/* SPDX-License-Identifier: GPL-2.0 */
/* Copyright (C) 2021 - 2023, Shanghai Yunsilicon Technology Co., Ltd.
 * All rights reserved.
 */

#ifndef XSC_REG_H
#define XSC_REG_H
#define CMDQM_HOST_REQ_BUF_BASE_H_ADDR_MEM_ADDR 0x0
#define CMDQM_HOST_REQ_BUF_BASE_L_ADDR_MEM_ADDR 0x4
#define CMDQM_HOST_REQ_PID_MEM_ADDR 0x8
#define CMDQM_HOST_REQ_CID_MEM_ADDR 0xc
#define CMDQM_HOST_RSP_BUF_BASE_H_ADDR_MEM_ADDR 0x10
#define CMDQM_HOST_RSP_BUF_BASE_L_ADDR_MEM_ADDR 0x14
#define CMDQM_HOST_RSP_PID_MEM_ADDR 0x18
#define CMDQM_HOST_RSP_CID_MEM_ADDR 0x1c
#define CMDQM_HOST_VF_ERR_STS_MEM_ADDR 0x20
#define CMDQM_VECTOR_ID_MEM_ADDR 0x24
#define CMDQM_Q_ELEMENT_SZ_REG_ADDR 0x28
#define CMDQM_HOST_Q_DEPTH_REG_ADDR 0x2c

#define CPM_LOCK_GET_REG_ADDR 0x30
#define CPM_LOCK_PUT_REG_ADDR 0x34
#define CPM_LOCK_AVAIL_REG_ADDR 0x38
#define CPM_IDA_DATA_MEM_ADDR 0x3c
#define CPM_IDA_CMD_REG_ADDR 0x83c
#define CPM_IDA_ADDR_REG_ADDR 0x840
#define CPM_IDA_BUSY_REG_ADDR 0x8c0

#define DB_CQ_FUNC_MEM_ADDR 0x8c4
#define DB_EQ_FUNC_MEM_ADDR 0x8c8
#define DB_CQ_CID_DIRECT_MEM_ADDR 0x8cc
#define TX_DB_FUNC_MEM_ADDR 0x8d0
#define RX_DB_FUNC_MEM_ADDR 0x8d4

#endif
