/* SPDX-License-Identifier: GPL-2.0 */
/* Copyright (C) 2021 - 2023, Shanghai Yunsilicon Technology Co., Ltd.
 * All rights reserved.
 */

#ifndef XSC_PP_H
#define XSC_PP_H

enum {
	XSC_HASH_FIELD_SEL_SRC_IP	= 1 << 0,
	XSC_HASH_FIELD_SEL_PROTO	= 1 << 1,
	XSC_HASH_FIELD_SEL_DST_IP	= 1 << 2,
	XSC_HASH_FIELD_SEL_SPORT	= 1 << 3,
	XSC_HASH_FIELD_SEL_DPORT	= 1 << 4,
	XSC_HASH_FIELD_SEL_SRC_IPV6	= 1 << 5,
	XSC_HASH_FIELD_SEL_DST_IPV6	= 1 << 6,
	XSC_HASH_FIELD_SEL_SPORT_V6	= 1 << 7,
	XSC_HASH_FIELD_SEL_DPORT_V6	= 1 << 8,
};

#define XSC_HASH_IP		(XSC_HASH_FIELD_SEL_SRC_IP	|\
				XSC_HASH_FIELD_SEL_DST_IP	|\
				XSC_HASH_FIELD_SEL_PROTO)
#define XSC_HASH_IP_PORTS	(XSC_HASH_FIELD_SEL_SRC_IP	|\
				XSC_HASH_FIELD_SEL_DST_IP	|\
				XSC_HASH_FIELD_SEL_SPORT	|\
				XSC_HASH_FIELD_SEL_DPORT	|\
				XSC_HASH_FIELD_SEL_PROTO)
#define XSC_HASH_IP6		(XSC_HASH_FIELD_SEL_SRC_IPV6	|\
				XSC_HASH_FIELD_SEL_DST_IPV6	|\
				XSC_HASH_FIELD_SEL_PROTO)
#define XSC_HASH_IP6_PORTS	(XSC_HASH_FIELD_SEL_SRC_IPV6	|\
				XSC_HASH_FIELD_SEL_DST_IPV6	|\
				XSC_HASH_FIELD_SEL_SPORT_V6	|\
				XSC_HASH_FIELD_SEL_DPORT_V6	|\
				XSC_HASH_FIELD_SEL_PROTO)

enum {
	XSC_HASH_TMPL_IDX_IP_PORTS_IP6_PORTS = 0,
	XSC_HASH_TMPL_IDX_IP_IP6,
	XSC_HASH_TMPL_IDX_IP_PORTS_IP6,
	XSC_HASH_TMPL_IDX_IP_IP6_PORTS,
	XSC_HASH_TMPL_IDX_MAX,
};


#endif /* XSC_PP_H */

