# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the Linux kernel UB device drivers.
#

ubcore-objs := ubcore_main.o \
			ubcore_device.o	\
			ubcore_jetty.o \
			ubcore_segment.o \
			ubcore_umem.o \
			ubcore_hash_table.o \
			ubcore_tp.o \
			ubcore_tp_table.o \
			ubcore_netlink.o \
			ubcore_dp.o \
			ubcore_ctp.o \
			ubcore_msg.o \
			ubcore_netdev.o \
			ubcore_tpg.o \
			ubcore_utp.o \
			ubcore_uvs_cmd.o \
			ubcore_vtp.o \
			ubcore_cgroup.o \
			ubcore_cdev_file.o \
			ubcore_genl_admin.o \
			ubcore_genl.o \
			ubcore_log.o \
			ubcore_workqueue.o
obj-$(CONFIG_UB) += ubcore.o
