# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the Linux kernel UB device drivers.
#

ubcore-objs := ubcore_main.o \
			ubcore_device.o	\
			ubcore_umem.o \
			ubcore_netlink.o

obj-$(CONFIG_UB) += ubcore.o
