/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2024-2025. All rights reserved.
 *
 * Description: ubcore GENERIC NETLINK
 * Author: Zhao yanchao
 * Create: 2024-01-25
 * Note:
 * History: 2024-01-25  Zhao yanchao  Add base code
 */

#ifndef UBCORE_GENERIC_NETLINK_DEFINE_H
#define UBCORE_GENERIC_NETLINK_DEFINE_H

/* NETLINK_GENERIC related info */
#define UBCORE_GENL_FAMILY_NAME "UBCORE_GENL"
#define UBCORE_GENL_FAMILY_VERSION 1

enum {
	UBCORE_ATTR_UNSPEC,
	UBCORE_HDR_COMMAND,
	UBCORE_HDR_ARGS_LEN,
	UBCORE_HDR_ARGS_ADDR,
	UBCORE_ATTR_DEV_NS_MODE,
	UBCORE_ATTR_DEV_NAME,
	UBCORE_ATTR_NS_FD,
	UBCORE_ATTR_EID_IDX,
	UBCORE_MSG_SEQ,
	UBCORE_MSG_TYPE,
	UBCORE_TRANSPORT_TYPE,
	UBORE_SRC_ID,
	UBORE_DST_ID,
	UBCORE_PAYLOAD_DATA,
	UBCORE_UPDATE_EID_RET,
	UBCORE_ATTR_EID,
	UBCORE_ATTR_MAIN_UE_EID,
	UBCORE_ATTR_EID_NUM,
	UBCORE_ATTR_EID_LIST,
	UBCORE_ATTR_STATUS,
	UBCORE_ATTR_EID_NS_MODE,
	UBCORE_ATTR_SL,
	UBCORE_ATTR_PRIORITY,
	UBCORE_ATTR_PERF_STAT,
	UBCORE_ATTR_TOOL_QUERY_KEY,
	UBCORE_ATTR_TOOL_QUERY_KEY_TYPE,
	UBCORE_ATTR_TOOL_QUERY_KEY_EXT,
	UBCORE_ATTR_TOOL_QUERY_KEY_CNT,
	UBCORE_ATTR_STATS,
	UBCORE_ATTR_TPID_QUERY_FLAG,
	UBCORE_ATTR_TPID,
	UBCORE_ATTR_AFTER_LAST,
	NUM_UBCORE_ATTR = UBCORE_ATTR_AFTER_LAST,
	UBCORE_ATTR_MAX = UBCORE_ATTR_AFTER_LAST - 1
};

#endif // UBCORE_GENERIC_NETLINK_DEFINE_H
