PDX-License-Identifier: GPL-2.0
#
# Makefile for the linux kernel.
#

obj-y                    += pci.o
obj-y                    += pci-legacy.o
obj-y                    += pci-sysfs.o
obj-$(CONFIG_ACPI)       += acpi.o
obj-$(CONFIG_PCI_MSI)    += msi.o

