/* SPDX-License-Identifier: GPL-2.0 */
/* Copyright (c) 2023 - 2024 ZTE Corporation */

#ifndef DPP_DRV_SDT_H
#define DPP_DRV_SDT_H

#include "zxic_common.h"

#define ZXDH_SDT_VXLAN_ATTR_TABLE ((u32)(0))
#define ZXDH_SDT_SRIOV_VPORT_ATTR_TABLE ((u32)(1))
#define ZXDH_SDT_UPLINK_PHY_PORT_ATTR_TABLE ((u32)(2))
#define ZXDH_SDT_RSS_TO_VQID_TABLE ((u32)(3))
#define ZXDH_SDT_VLAN_FILTER_TABLE ((u32)(4))
#define ZXDH_SDT_LAG_TABLE ((u32)(5))
#define ZXDH_SDT_BC_TABLE ((u32)(6))
#define ZXDH_SDT_DSCP_TO_UP_TABLE ((u32)(7))
#define ZXDH_SDT_UP_TO_TC_TABLE ((u32)(8))
#define ZXDH_SDT_UC_PROMISC_TABLE ((u32)(10))
#define ZXDH_SDT_MC_PROMISC_TABLE ((u32)(11))
#define ZXDH_SDT_FLOW_ID_TABLE ((u32)(12))
#define ZXDH_SDT_MAINTAIN_TABLE ((u32)(13))
#define ZXDH_SDT_NETWORK_ATTR_TABLE ((u32)(14))
#define ZXDH_SDT_VPORT_TRAFFIC_ATTR_TABLE ((u32)(15))
#define ZXDH_SDT_VQM_VFID_VLAN_ATTR_TABLE ((u32)(16))
#define ZXDH_SDT_CAP_KEYWORD_ATTR_TABLE ((u32)(17))
#define ZXDH_SDT_MAINTAIN_DIAG_TABLE ((u32)(18))
#define ZXDH_SDT_PSN_ARN_ATTR_TABLE ((u32)(19))
#define ZXDH_SDT_STAT_ATTR_TABLE ((u32)(20))
#define ZXDH_SDT_TUNNEL_ENCAP0_TABLE ((u32)(28))
#define ZXDH_SDT_TUNNEL_ENCAP1_TABLE ((u32)(29))
#define ZXDH_SDT_ACL_INDEX_MNG_TABLE ((u32)(30))
#define ZXDH_SDT_VHCA_TABLE ((u32)(50))

#define ZXDH_SDT_L2_ENTRY_TABLE_PHYPORT0 ((u32)(64))
#define ZXDH_SDT_L2_ENTRY_TABLE_PHYPORT1 ((u32)(65))
#define ZXDH_SDT_L2_ENTRY_TABLE_PHYPORT2 ((u32)(66))
#define ZXDH_SDT_L2_ENTRY_TABLE_PHYPORT3 ((u32)(67))
#define ZXDH_SDT_L2_ENTRY_TABLE_PHYPORT4 ((u32)(68))
#define ZXDH_SDT_L2_ENTRY_TABLE_PHYPORT5 ((u32)(69))

#define ZXDH_SDT_MC_TABLE_PHYPORT0 ((u32)(76))
#define ZXDH_SDT_MC_TABLE_PHYPORT1 ((u32)(77))
#define ZXDH_SDT_MC_TABLE_PHYPORT2 ((u32)(78))
#define ZXDH_SDT_MC_TABLE_PHYPORT3 ((u32)(79))
#define ZXDH_SDT_MC_TABLE_PHYPORT4 ((u32)(80))
#define ZXDH_SDT_MC_TABLE_PHYPORT5 ((u32)(81))
#define ZXDH_SDT_LOGIC_GROUP_TABLE ((u32)(87))
#define ZXDH_SDT_RDMA_ENTRY_TABLE ((u32)(90))

#define ZXDH_SDT_FD_CFG_TABLE ((u32)(130))
#define ZXDH_SDT_IPSEC_ENC_TABLE ((u32)(131))
#define ZXDH_SDT_CAPTURE_PKT_TABLE ((u32)(132))

#endif
