/* SPDX-License-Identifier: GPL-2.0 */
/* Copyright(c) 2024 Huawei Technologies Co., Ltd */

#ifndef ROCE_PUB_CMD_H
#define ROCE_PUB_CMD_H

#ifndef CQM_AEQ_BASE_T_ROCE
#define CQM_AEQ_BASE_T_ROCE 16
#endif

/* RoCE EVENT */
enum {
	ROCE_EVENT_TYPE_OFED_NO_DEF = (CQM_AEQ_BASE_T_ROCE + 0x00),
	ROCE_EVENT_TYPE_PATH_MIG = (CQM_AEQ_BASE_T_ROCE + 0x01), /* RSVD */
	ROCE_EVENT_TYPE_COMM_EST = (CQM_AEQ_BASE_T_ROCE + 0x02),
	ROCE_EVENT_TYPE_SQ_DRAINED = (CQM_AEQ_BASE_T_ROCE + 0x03),
	ROCE_EVENT_TYPE_SRQ_QP_LAST_WQE = (CQM_AEQ_BASE_T_ROCE + 0x04),

	/* 5 */
	ROCE_EVENT_TYPE_WQ_CATAS_ERROR = (CQM_AEQ_BASE_T_ROCE + 0x05),
	ROCE_EVENT_TYPE_PATH_MIG_FAILED = (CQM_AEQ_BASE_T_ROCE + 0x06),
	ROCE_EVENT_TYPE_WQ_INVAL_REQ_ERROR = (CQM_AEQ_BASE_T_ROCE + 0x07),
	ROCE_EVENT_TYPE_WQ_ACCESS_ERROR = (CQM_AEQ_BASE_T_ROCE + 0x08),
	ROCE_EVENT_TYPE_CQ_ERROR = (CQM_AEQ_BASE_T_ROCE + 0x09),

	/* 10 */
	ROCE_EVENT_TYPE_SRQ_LIMIT = (CQM_AEQ_BASE_T_ROCE + 0x0a),
	ROCE_EVENT_TYPE_SRQ_CATAS_ERROR = (CQM_AEQ_BASE_T_ROCE + 0x0b),
	ROCE_EVENT_TYPE_LOCAL_CATAS_ERROR = (CQM_AEQ_BASE_T_ROCE + 0x0c), /* RSVD */
	ROCE_EVENT_TYPE_MR_SIG_ERR = (CQM_AEQ_BASE_T_ROCE + 0x0e),

	ROCE_EVENT_TYPE_ODP_PAGE_FAULT = (CQM_AEQ_BASE_T_ROCE + 0x0f),
	/* ROCE NOF AA */
	ROCE_EVENT_TYPE_SWITCH_HOST = (CQM_AEQ_BASE_T_ROCE + 0x10),
	ROCE_EVENT_TYPE_HOST_FAILOVER = (CQM_AEQ_BASE_T_ROCE + 0x11),
	ROCE_EVENT_NOFAA_STUB = (CQM_AEQ_BASE_T_ROCE + 0x12),

	/* * RSVE */
	ROCE_EVENT_TYPE_EEC_CATAS_ERROR = (CQM_AEQ_BASE_T_ROCE + 0x30),
	ROCE_EVENT_TYPE_PORT_CHANGE = (CQM_AEQ_BASE_T_ROCE + 0x31),
	ROCE_EVENT_TYPE_ECC_DETECT = (CQM_AEQ_BASE_T_ROCE + 0x32),
	ROCE_EVENT_TYPE_VEP_UPDATE = (CQM_AEQ_BASE_T_ROCE + 0x33),
	ROCE_EVENT_TYPE_FATAL_WARNING = (CQM_AEQ_BASE_T_ROCE + 0x34),
	ROCE_EVENT_TYPE_FLR_EVENT = (CQM_AEQ_BASE_T_ROCE + 0x35),
	ROCE_EVENT_TYPE_PORT_MNG_CHG_EVENT = (CQM_AEQ_BASE_T_ROCE + 0x36),
	ROCE_EVENT_TYPE_XRC_DOMAIN_VIOLATION_ERROR = (CQM_AEQ_BASE_T_ROCE + 0x37),
	ROCE_EVENT_TYPE_INVALID_XRCETH_ERROR = (CQM_AEQ_BASE_T_ROCE + 0x38),
	ROCE_EVENT_TYPE_FLUSH_WQE_ERROR = (CQM_AEQ_BASE_T_ROCE + 0x39),

	ROCE_EVENT_TYPE_EQ_OVERFLOW = (CQM_AEQ_BASE_T_ROCE + 0x40),
	ROCE_EVENT_TYPE_CMD = (CQM_AEQ_BASE_T_ROCE + 0x41),
	ROCE_EVENT_TYPE_COMM_CHANNEL = (CQM_AEQ_BASE_T_ROCE + 0x42),
	ROCE_EVENT_TYPE_OP_REQUIRED = (CQM_AEQ_BASE_T_ROCE + 0x43),

	ROCE_EVENT_TYPE_NONE = (CQM_AEQ_BASE_T_ROCE + 0x50)
};


enum {
	/* GID CMD */
	ROCE_CMD_UPDATE_GID = 0x60,
	ROCE_CMD_QUERY_GID = 0x61,
	ROCE_CMD_CLEAR_GID = 0x62,

	/* IP CMD */
	ROCE_CMD_ADD_IP_ENTRY = 0x68,
	ROCE_CMD_DEL_IP_ENTRY = 0x69,
	ROCE_CMD_LOOKUP_IP_ENTRY = 0x6a,
	ROCE_CMD_UPDATE_IP_ENTRY = 0x6b,

	/* TPT CMD */
	ROCE_CMD_SW2HW_MPT = 0x70,
	ROCE_CMD_HW2SW_MPT = 0x71,
	ROCE_CMD_MODIFY_MPT = 0x72,
	ROCE_CMD_QUERY_MPT = 0x73,
	ROCE_CMD_FLUSH_TPT = 0x74,
	ROCE_CMD_SYNC_TPT = 0x75,

	/* CQ CMD */
	ROCE_CMD_SW2HW_CQ = 0x80,
	ROCE_CMD_RESIZE_CQ = 0x81,
	ROCE_CMD_MODIFY_CQ = 0x82,
	ROCE_CMD_HW2SW_CQ = 0x83,
	ROCE_CMD_QUERY_CQ = 0x84,

	/* SRQ CMD */
	ROCE_CMD_SW2HW_SRQ = 0x90,
	ROCE_CMD_ARM_SRQ = 0x91,
	ROCE_CMD_HW2SW_SRQ = 0x92,
	ROCE_CMD_QUERY_SRQ = 0x93,

	/* QP CMD */
	ROCE_CMD_QP_BASE = 0xa0,
	ROCE_CMD_RST2INIT_QP = 0xa0,
	ROCE_CMD_INIT2INIT_QP = 0xa1,
	ROCE_CMD_INIT2RTR_QP = 0xa2,
	ROCE_CMD_RTR2RTS_QP = 0xa3,
	ROCE_CMD_RTS2RTS_QP = 0xa4,
	ROCE_CMD_SQERR2RTS_QP = 0xa5,
	ROCE_CMD_2ERR_QP = 0xa6,
	ROCE_CMD_RTS2SQD_QP = 0xa7,
	ROCE_CMD_SQD2SQD_QP = 0xa8,
	ROCE_CMD_SQD2RTS_QP = 0xa9,
	ROCE_CMD_2RST_QP = 0xaa,
	ROCE_CMD_QUERY_QP = 0xab,
	ROCE_CMD_MIRROR_QP = 0xac, /* DFX RoCE +/- packet mirroring */
	ROCE_CMD_MODIFY_HASH_VALUE_QP = 0xad,
	ROCE_CMD_GET_QP_RX_PORT = 0xae,
	ROCE_CMD_MODIFY_UDP_SRC_PORT_QP = 0xaf,
	ROCE_CMD_GET_UDP_SRC_PORT_QP = 0xb0,
	ROCE_CMD_GET_QP_FUNC_TABLE = 0xb1,
	ROCE_CMD_QP_MAX = 0xb1,
	/* Miscellaneous CMD */
	// ROCE_CMD_NOP			= 0xb0,

	/* MTT commands */
	ROCE_CMD_QUERY_MTT = 0xc0,

	ROCE_CMD_MODIFY_CONTEXT = 0xd0,
	ROCE_CMD_EN_QP_CAP_PKT = 0xd1,
	ROCE_CMD_DIS_QP_CAP_PKT = 0xd2,

	ROCE_CMD_MISC_CACHE_INVLD = 0xe0,

	ROCE_CMD_MISC_CQ_CACHE_INVLD = 0xf0,

	ROCE_CMD_CREAT_SLAVE_QP = 0xf1,
	ROCE_CMD_QUERY_MASTER_QP_BITMAP = 0xf2,
	ROCE_CMD_GET_MASTER_QPN = 0xf3,
	ROCE_CMD_SET_CONN_STAT = 0xf4,
	ROCE_CMD_DISCONNECT_QP = 0xf5,
	ROCE_CMD_SET_SHARD_CFG = 0xf6
};

enum roce3_cmd_type {
	COMMON_CMD_TX_INFO = 1,
	COMMON_CMD_Q_NUM,
	COMMON_CMD_TX_WQE_INFO,
	COMMON_CMD_TX_MAPPING,
	COMMON_CMD_RX_INFO,
	COMMON_CMD_RX_WQE_INFO,
	COMMON_CMD_RX_CQE_INFO,
	COMMON_CMD_UPRINT_FUNC_EN,
	COMMON_CMD_UPRINT_FUNC_RESET,
	COMMON_CMD_UPRINT_SET_PATH,
	COMMON_CMD_UPRINT_GET_STATISTICS,
	COMMON_CMD_FUNC_TYPE,
	COMMON_CMD_GET_FUNC_IDX,
	COMMON_CMD_GET_INTER_NUM,
	COMMON_CMD_CLOSE_TX_STREAM,
	COMMON_CMD_GET_DRV_VERSION,
	COMMON_CMD_CLEAR_FUNC_STASTIC,
	COMMON_CMD_GET_HW_STATS,
	COMMON_CMD_CLEAR_HW_STATS,
	COMMON_CMD_GET_SELF_TEST_RES,
	COMMON_CMD_GET_CHIP_FAULT_STATS,
	COMMON_CMD_NIC_RSVD1,
	COMMON_CMD_NIC_RSVD2,
	COMMON_CMD_NIC_RSVD3,
	COMMON_CMD_GET_CHIP_ID,
	COMMON_CMD_GET_SINGLE_CARD_INFO,
	COMMON_CMD_GET_FIRMWARE_ACTIVE_STATUS,
	COMMON_CMD_ROCE_DFX_FUNC,
	COMMON_CMD_GET_DEVICE_ID,
	COMMON_CMD_GET_PF_DEV_INFO,
	COMMON_CMD_CMD_FREE_MEM,
	COMMON_CMD_GET_LOOPBACK_MODE = 32,
	COMMON_CMD_SET_LOOPBACK_MODE,
	COMMON_CMD_SET_LINK_MODE,
	COMMON_CMD_SET_PF_BW_LIMIT,
	COMMON_CMD_GET_PF_BW_LIMIT,
	COMMON_CMD_ROCE_CMD,
	COMMON_CMD_GET_POLL_WEIGHT,
	COMMON_CMD_SET_POLL_WEIGHT,
	COMMON_CMD_GET_HOMOLOGUE,
	COMMON_CMD_SET_HOMOLOGUE,
	COMMON_CMD_GET_SSET_COUNT,
	COMMON_CMD_GET_SSET_ITEMS,
	COMMON_CMD_IS_DRV_IN_VM,
	COMMON_CMD_LRO_ADPT_MGMT,
	COMMON_CMD_SET_INTER_COAL_PARAM,
	COMMON_CMD_GET_INTER_COAL_PARAM,
	COMMON_CMD_GET_CHIP_INFO,
	COMMON_CMD_GET_NIC_STATS_LEN,
	COMMON_CMD_GET_NIC_STATS_STRING,
	COMMON_CMD_GET_NIC_STATS_INFO,
	COMMON_CMD_GET_PF_ID,
	COMMON_CMD_NIC_RSVD4,
	COMMON_CMD_NIC_RSVD5,
	COMMON_CMD_DCB_QOS_INFO,
	COMMON_CMD_DCB_PFC_STATE,
	COMMON_CMD_DCB_ETS_STATE,
	COMMON_CMD_DCB_STATE,
	COMMON_CMD_QOS_DEV,
	COMMON_CMD_NIC_RSVD7,
	COMMON_CMD_GET_ULD_DEV_NAME,

	COMMON_CMD_RSS_CFG = 0x40,
	COMMON_CMD_RSS_INDIR,
	COMMON_CMD_PORT_ID,

	COMMON_CMD_GET_FUNC_CAP = 0x50,

	COMMON_CMD_GET_WIN_STAT = 0x60,
	COMMON_CMD_WIN_CSR_READ = 0x61,
	COMMON_CMD_WIN_CSR_WRITE = 0x62,
	COMMON_CMD_WIN_API_CMD_RD = 0x63,

	ROCE_CMD_GET_QPC_FROM_CACHE = 0x80,
	ROCE_CMD_GET_QPC_FROM_HOST = 0x81,
	ROCE_CMD_GET_CQC_FROM_CACHE = 0x82,
	ROCE_CMD_GET_CQC_FROM_HOST = 0x83,
	ROCE_CMD_GET_SRQC_FROM_CACHE = 0x84,
	ROCE_CMD_GET_SRQC_FROM_HOST = 0x85,
	ROCE_CMD_GET_MPT_FROM_CACHE = 0x86,
	ROCE_CMD_GET_MPT_FROM_HOST = 0x87,
	ROCE_CMD_GET_GID_FROM_CACHE = 0x88,
	ROCE_CMD_GET_QPC_CQC_PI_CI = 0x89,
	ROCE_CMD_GET_QP_COUNT = 0x8a,
	ROCE_CMD_GET_DEV_ALGO = 0x8b,

	ROCE_CMD_START_CAP_PACKET = 0x90,
	ROCE_CMD_STOP_CAP_PACKET = 0x91,
	ROCE_CMD_QUERY_CAP_INFO = 0x92,
	ROCE_CMD_ENABLE_QP_CAP_PACKET = 0x93,
	ROCE_CMD_DISABLE_QP_CAP_PACKET = 0x94,
	ROCE_CMD_QUERY_QP_CAP_INFO = 0x95,

	ROCE_CMD_ENABLE_BW_CTRL = 0xa0,
	ROCE_CMD_DISABLE_BW_CTRL = 0xa1,
	ROCE_CMD_CHANGE_BW_CTRL_PARAM = 0xa2,
	ROCE_CMD_QUERY_BW_CTRL_PARAM = 0xa3,

	ROCE_CMD_TIMEOUT_ALARM = 0xb0,
	COMMON_CMD_VM_COMPAT_TEST = 0xFF
};

enum roce3_cmd_ctx_type {
	ROCE_CMD_CTX_MODIFY_QPC = 0X0,
	ROCE_CMD_CTX_MODIFY_MPT = 0X1,
	ROCE_CMD_CTX_MODIFY_CQC = 0X2,
	ROCE_CMD_CTX_MODIFY_SRQC = 0X3,
	ROCE_CMD_CTX_MODIFY_WQE_PI_CI = 0X4,
	ROCE_CMD_CTX_FETCH_WQE = 0X5,
	ROCE_CMD_CTX_DEL_TIMER = 0X6,
	ROCE_CMD_CTX_LB_SQDB = 0X7
};

enum roce3_modify_fetch_wqe_cmd_type {
	ROCE_CMD_FCH_WQE_ACKCI = 1,
	ROCE_CMD_FCH_WQE_UPDATE  = 2
};

enum roce3_gid_type {
	ROCE_IPv4_ROCEv2_GID = 0,
	ROCE_IPv6_ROCEv2_GID = 1,
	ROCE_ROCEv1_GID = 2,
	ROCE_INV_GID
};

#endif /* ROCE_PUB_CMD_H */
