/* SPDX-License-Identifier: GPL-2.0 or Linux-OpenIB */
/* Copyright (c) 2021, NEBULARMATRIX */

#ifndef NBL_IB_COUNTERS_H
#define NBL_IB_COUNTERS_H

#include "main.h"

/* updated once every 10 days to prevent data turnover */
/* (10days to ms) : 1000 * 3600 * 24 * 10 = 864 000 000 */
#define NBL_STATS_INTERVAL_MAX 864000000
#define NBL_STATS_INTERVAL_MIN 60000

#define NBL_MAX_TRY_DUMP_CNT 3
#define NBL_STATS_RETRY_WAIT 300
#define NBL_STATS_WAIT_DMA 5

#define NBL_MAX_STATS_48 0xFFFFFFFFFFFFULL
#define NBL_MAX_STATS_24 0xFFFFFFULL

#define NBL_VF_NUM 64
#define NBL_STATS_GROUP_NUM 128
#define NBL_STATS_GROUP_START_NUM 2

#define NBL_VF_CNTS 8
#define NBL_STATS_GROUP_CNTS 256
#define NBL_STATS_GROUP_OPCODE_CNTS 128
#define NBL_STATS_GROUP_ERR_CNTS 128
#define NBL_ERR_QPN_CNTS 128
#define NBL_ERR_QPN_CNTS_PER_VF 2

#define NBL_DUMP_VF_SIZE 64
#define NBL_DUMP_STATS_MAX_SIZE 512
#define NBL_DUMP_STATS_MAX_CNT 64

#define NBL_DEBUGFS_DUMP_QPC_SIZE 3145728
#define NBL_DEBUGFS_DUMP_MRT_SIZE 3145728
#define NBL_FUNDBG_READ_BUF_SIZE 11

#define NBL_CMDBUF_STR_LEN_MAX 64
#define NBL_HW_COUNTERS_CNT 7
/**
 * op_info
 *	[0]:op_status
 *	[1]:op_err_warning
 *	[2]:op_rc
 *	[6:3]op_table_sel
 *	[15:7]op_id
 *	[23:16]op_len
 *	[31:24]op_add_sel
 */
#define NBL_STATS_OP_STATUS_S 0
#define NBL_STATS_OP_STATUS_M BIT_ULL(NBL_STATS_OP_STATUS_S)
#define NBL_STATS_OP_ERR_WARN_S 1
#define NBL_STATS_OP_ERR_WARN_M BIT_ULL(NBL_STATS_OP_ERR_WARN_S)
#define NBL_STATS_OP_RC_S 2
#define NBL_STATS_OP_RC_M BIT_ULL(NBL_STATS_OP_RC_S)
#define NBL_STATS_OP_TABLE_SEL_S 3
#define NBL_STATS_OP_TABLE_SEL_M (0xfULL << NBL_STATS_OP_TABLE_SEL_S)
#define NBL_STATS_OP_ID_S 7
#define NBL_STATS_OP_ID_M (0x1ffULL << NBL_STATS_OP_ID_S)
#define NBL_STATS_OP_LEN_S 16
#define NBL_STATS_OP_LEN_M (0xffULL << NBL_STATS_OP_LEN_S)
#define NBL_STATS_OP_ADD_SEL_S 24
#define NBL_STATS_OP_ADD_SEL_M (0xffULL << NBL_STATS_OP_ADD_SEL_S)

#define NBL_PACKET_SEQ_ERR (0x2d + NBL_STATS_GROUP_ERR_CNTS)
#define NBL_OUT_OF_SEQUENCE_LOW (0x23 + NBL_STATS_GROUP_ERR_CNTS)
#define NBL_OUT_OF_SEQUENCE_HIGH (0x24 + NBL_STATS_GROUP_ERR_CNTS)
#define NBL_ROCE_ADP_RETRANS (0x58 + NBL_STATS_GROUP_ERR_CNTS)

#define LS_32(val, field) (((val) << field##_S) & (field##_M))
#define RS_32(val, field) (((val)&field##_M) >> field##_S)
#define U64_HI(val) ((u32)(((u64)(val)) >> 32))
#define U64_LO(val) ((u32)(((u64)(val)) & 0xFFFFFFFF))

#define NBL_DEFAULT_STAT_ID(x) \
	(((x) * 2) + 2)
#define NBL_DEFAULT_CM_STAT_ID_OFFSET 1

struct stat_work {
	struct work_struct work;
	struct nbl_device *nbl_dev;
};

struct nbl_stats_reg_info {
	u32 op_status : 1;
	u32 op_err_warn : 1;
	u32 op_rc : 1; /* read /clear */
	u32 op_table_sel : 4;
	u32 op_id : 9;
	u32 op_len : 8;
	u32 op_addr_sel : 8;
	struct nbl_dma_mem *mem;
};

struct nbl_stats_info {
	u64 total_stats;
	u64 last_stats;
};

struct nbl_qp_func {
	struct list_head list;
	u32 qpn;
	u16 func_id;
};

struct nbl_func_file {
	size_t used_len;
	size_t total_len;
	struct dentry *file;
	char cmd[NBL_CMDBUF_STR_LEN_MAX];
	char *buf;
};

struct nbl_rdma_stat {
	struct nbl_device *nbldev;
	u32 period;
	u32 stat_id_used_cnt[NBL_STATS_GROUP_NUM];
	struct list_head stat_head[NBL_STATS_GROUP_NUM];
	spinlock_t stat_head_lock[NBL_STATS_GROUP_NUM];
	struct nbl_stats_info vf_mem[NBL_VF_CNTS];
	struct nbl_stats_info stat_id_mem[NBL_STATS_GROUP_NUM][NBL_STATS_GROUP_CNTS];
	struct nbl_stats_info err_qpn_mem[NBL_ERR_QPN_CNTS_PER_VF];
	spinlock_t stat_mem_lock;
	struct timer_list stats_timer;
	struct nbl_func_file func_file;
};

struct nbl_dump_info {
	struct nbl_func_file dump_func_file;
	int fun_type;
};

enum nbl_op_stats_type {
	OP_STATS_CLEAR = 0,
	OP_STATS_READ,
};

enum nbl_stats_table_type {
	NBL_VF_TABLE = 0,
	NBL_STATS_ID_TABLE = 1,
	NBL_ERR_QPN_TABLE = 2,
	NBL_CLEAR_ALL = 1 << 3
};

enum nbl_vf_stats_index {
	NBL_HW_VF_STATS_INDEX_RXRESP = 0,
	NBL_HW_VF_STATS_INDEX_RXREQ = 1,
	NBL_HW_VF_STATS_INDEX_RX_QPN_ERR = 2,
	NBL_HW_VF_STATS_INDEX_RX_ERR = 3,
	NBL_HW_VF_STATS_INDEX_TXRESP = 4,
	NBL_HW_VF_STATS_INDEX_TXREQ = 5,
	NBL_HW_VF_STATS_INDEX_TX_QPN_ERR = 6,
	NBL_HW_VF_STATS_INDEX_TX_ERR = 7
};

enum nbl_qp_opcode_stats_index {
	NBL_STATS_TYPE_OP_MIN = 0,
		/* rx rc opcode */
	NBL_STATS_TYPE_RX_RC_OP_SEND_FIRST_PAYLD = NBL_STATS_TYPE_OP_MIN,
	NBL_STATS_TYPE_RX_RC_OP_SEND_MIDDLE_PAYLD = 1,
	NBL_STATS_TYPE_RX_RC_OP_SEND_LAST_PAYLD = 2,
	NBL_STATS_TYPE_RX_RC_OP_SEND_LAST_IMMD_PAYLD = 3,
	NBL_STATS_TYPE_RX_RC_OP_SEND_ONLY_PAYLD = 4,
	NBL_STATS_TYPE_RX_RC_OP_SEND_ONLY_IMMD_PAYLD = 5,
	NBL_STATS_TYPE_RX_RC_OP_WRITE_FIRST_PAYLD = 6,
	NBL_STATS_TYPE_RX_RC_OP_WRITE_MIDDLE_PAYLD = 7,
	NBL_STATS_TYPE_RX_RC_OP_WRITE_LAST_PAYLD = 8,
	NBL_STATS_TYPE_RX_RC_OP_WRITE_LAST_IMMD_PAYLD = 9,
	NBL_STATS_TYPE_RX_RC_OP_WRITE_ONLY_PAYLD = 10,
	NBL_STATS_TYPE_RX_RC_OP_WRITE_ONLY_IMMD_PAYLD = 11,
	NBL_STATS_TYPE_RX_RC_OP_REQ_RETH = 12,
	NBL_STATS_TYPE_RX_RC_OP_RESP_FIRST_AETH_PAYLD = 13,
	NBL_STATS_TYPE_RX_RC_OP_RESP_MIDDLE_AETH_PAYLD = 14,
	NBL_STATS_TYPE_RX_RC_OP_RESP_LAST_AETH_PAYLD = 15,
	NBL_STATS_TYPE_RX_RC_OP_RESP_ONLY_AETH_PAYLD = 16,
	NBL_STATS_TYPE_RX_RC_OP_ACK_AETH = 17,
	NBL_STATS_TYPE_RX_RC_OP_ATOMIC_ACK_AETH = 18,
	NBL_STATS_TYPE_RX_RC_OP_CMPSWAP_AETH = 19,
	NBL_STATS_TYPE_RX_RC_OP_FETCHADD_AETH = 20,
	NBL_STATS_TYPE_RX_RC_OP_RSV_21 = 21,
	NBL_STATS_TYPE_RX_RC_OP_SEND_LAST_INVALIDATE_IETH = 22,
	NBL_STATS_TYPE_RX_RC_OP_SEND_ONLY_INVALIDATE_IETH = 23,

	/* rx ud opcode */
	NBL_STATS_TYPE_RX_UD_SEND_ONLY_DETH = 24,
	NBL_STATS_TYPE_RX_UD_SEND_ONLY_IMMD_DETH = 25,

	/* rx normal db */
	NBL_STATS_TYPE_RX_DB_OP_NORMAL_FLUSH_RQ = 26,
	NBL_STATS_TYPE_RX_DB_OP_NORMAL_RAQ = 27,

	NBL_STATS_TYPE_RX_RSV_28 = 28,
	NBL_STATS_TYPE_RX_RSV_29 = 29,
	NBL_STATS_TYPE_RX_RSV_30 = 30,
	NBL_STATS_TYPE_RX_RSV_31 = 31,

	/* CC OAM */
	NBL_STATS_TYPE_SEND_OAM_REQ = 32,
	NBL_STATS_TYPE_SEND_OAM_ACK = 33,

	/* rx rsv */
	NBL_STATS_TYPE_RX_RSV_34 = 34,
	NBL_STATS_RX_CNP = 35,
	NBL_STATS_TYPE_RX_RSV_36 = 36,
	NBL_STATS_TYPE_RX_RSV_37 = 37,
	NBL_STATS_TYPE_RX_RSV_38 = 38,
	NBL_STATS_TYPE_RX_RSV_39 = 39,
	NBL_STATS_TYPE_RX_RSV_40 = 40,
	NBL_STATS_TYPE_RX_RSV_41 = 41,
	NBL_STATS_TYPE_RX_RSV_42 = 42,
	NBL_STATS_TYPE_RX_RSV_43 = 43,
	NBL_STATS_TYPE_RX_RSV_44 = 44,
	NBL_STATS_TYPE_RX_RSV_45 = 45,
	NBL_STATS_TYPE_RX_RSV_46 = 46,
	NBL_STATS_TYPE_RX_RSV_47 = 47,

	/* tx drop DB */
	NBL_STATS_TYPE_TX_DB_OP_DROP_INVAILD = 48,
	NBL_STATS_TYPE_TX_DB_OP_DROP_SWSQ = 49,
	NBL_STATS_TYPE_TX_DB_OP_DROP_TXPSQ = 50,
	NBL_STATS_TYPE_TX_DB_OP_DROP_TQRECHECK = 51,
	NBL_STATS_TYPE_TX_DB_OP_DROP_TQRNR = 52,
	NBL_STATS_TYPE_TX_DB_OP_DROP_TQRTO = 53,
	NBL_STATS_TYPE_TX_DB_OP_DROP_PSNERR = 54,
	NBL_STATS_TYPE_TX_DB_OP_DROP_RAQ = 55,
	NBL_STATS_TYPE_TX_DB_OP_DROP_TXPRAQ = 56,
	NBL_STATS_TYPE_TX_DB_OP_DROP_TQ_WAITACK = 57,
	NBL_STATS_TYPE_TX_DB_OP_DROP_OAMACK = 58,

	/* rx rsv */
	NBL_STATS_TYPE_RX_RSV_59 = 59,
	NBL_STATS_TYPE_RX_RSV_60 = 60,
	NBL_STATS_TYPE_RX_RSV_61 = 61,
	NBL_STATS_TYPE_RX_RSV_62 = 62,
	NBL_STATS_TYPE_RX_RSV_63 = 63,

	/* tx rc opcode */
	NBL_STATS_TYPE_TX_RC_OP_SEND_FIRST_PAYLD = 64,
	NBL_STATS_TYPE_TX_RC_OP_SEND_MIDDLE_PAYLD = 65,
	NBL_STATS_TYPE_TX_RC_OP_SEND_LAST_PAYLD = 66,
	NBL_STATS_TYPE_TX_RC_OP_SEND_LAST_IMMD_PAYLD = 67,
	NBL_STATS_TYPE_TX_RC_OP_SEND_ONLY_PAYLD = 68,
	NBL_STATS_TYPE_TX_RC_OP_SEND_ONLY_IMMD_PAYLD = 69,
	NBL_STATS_TYPE_TX_RC_OP_WRITE_FIRST_PAYLD = 70,
	NBL_STATS_TYPE_TX_RC_OP_WRITE_MIDDLE_PAYLD = 71,
	NBL_STATS_TYPE_TX_RC_OP_WRITE_LAST_PAYLD = 72,
	NBL_STATS_TYPE_TX_RC_OP_WRITE_LAST_IMMD_PAYLD = 73,
	NBL_STATS_TYPE_TX_RC_OP_WRITE_ONLY_PAYLD = 74,
	NBL_STATS_TYPE_TX_RC_OP_WRITE_ONLY_IMMD_PAYLD = 75,
	NBL_STATS_TYPE_TX_RC_OP_REQ_RETH = 76,
	NBL_STATS_TYPE_TX_RC_OP_RESP_FIRST_AETH_PAYLD = 77,
	NBL_STATS_TYPE_TX_RC_OP_RESP_MIDDLE_AETH_PAYLD = 78,
	NBL_STATS_TYPE_TX_RC_OP_RESP_LAST_AETH_PAYLD = 79,
	NBL_STATS_TYPE_TX_RC_OP_RESP_ONLY_AETH_PAYLD = 80,
	NBL_STATS_TYPE_TX_RC_OP_ACK_AETH = 81,
	NBL_STATS_TYPE_TX_RC_OP_ATOMIC_ACK_AETH = 82,
	NBL_STATS_TYPE_TX_RC_OP_CMPSWAP_AETH = 83,
	NBL_STATS_TYPE_TX_RC_OP_FETCHADD_AETH = 84,
	NBL_STATS_TYPE_TX_RC_OP_RSV_85 = 85,
	NBL_STATS_TYPE_TX_RC_OP_SEND_LAST_INVALIDATE_IETH = 86,
	NBL_STATS_TYPE_TX_RC_OP_SEND_ONLY_INVALIDATE_IETH = 87,

	/* tx ud opcode */
	NBL_STATS_TYPE_TX_UD_SEND_ONLY_DETH = 88,
	NBL_STATS_TYPE_TX_UD_SEND_ONLY_IMMD_DETH = 89,

	/* local */
	NBL_STATS_TYPE_TX_OP_BIND_MW_LOCAL = 90,
	NBL_STATS_TYPE_TX_OP_LOCAL_INV_LOCAL = 91,
	NBL_STATS_TYPE_TX_OP_FRMR_LOCAL = 92,
	NBL_STATS_TYPE_TX_OP_NOP_FOR_LOCAL = 93,

	/* tx rsv*/
	NBL_STATS_TYPE_TX_RSV_94 = 94,
	NBL_STATS_TYPE_TX_RSV_95 = 95,

	/* CC OAM */
	NBL_STATS_TYPE_SD_OAM_REQ = 96,
	NBL_STATS_TYPE_SD_OAM_ACK = 97,

	/* tx rsv*/
	NBL_STATS_TYPE_TX_RSV_98 = 98,
	NBL_STATS_TX_CNP = 99,
	NBL_STATS_TYPE_TX_RSV_100 = 100,
	NBL_STATS_TYPE_TX_RSV_101 = 101,
	NBL_STATS_TYPE_TX_RSV_102 = 102,
	NBL_STATS_TYPE_TX_RSV_103 = 103,
	NBL_STATS_TYPE_TX_RSV_104 = 104,
	NBL_STATS_TYPE_TX_RSV_105 = 105,
	NBL_STATS_TYPE_TX_RSV_106 = 106,
	NBL_STATS_TYPE_TX_RSV_107 = 107,
	NBL_STATS_TYPE_TX_RSV_108 = 108,
	NBL_STATS_TYPE_TX_RSV_109 = 109,
	NBL_STATS_TYPE_TX_RSV_110 = 110,
	NBL_STATS_TYPE_TX_RSV_111 = 111,

	/* tx normal DB */
	NBL_STATS_TYPE_TX_DB_OP_NORMAL_INVALID = 112,
	NBL_STATS_TYPE_TX_DB_OP_NORMAL_SWSQ = 113,
	NBL_STATS_TYPE_TX_DB_OP_NORMAL_TXPSQ = 114,
	NBL_STATS_TYPE_TX_DB_OP_NORMAL_TQRECHECK = 115,
	NBL_STATS_TYPE_TX_DB_OP_NORMAL_TQRNR = 116,
	NBL_STATS_TYPE_TX_DB_OP_NORMAL_TQRTO = 117,
	NBL_STATS_TYPE_TX_DB_OP_NORMAL_PSNERR = 118,
	NBL_STATS_TYPE_TX_DB_OP_NORMAL_RAQ = 119,
	NBL_STATS_TYPE_TX_DB_OP_NORMAL_TXPRAQ = 120,
	NBL_STATS_TYPE_TX_DB_OP_NORMAL_TQ_WAITACK = 121,
	NBL_STATS_TYPE_TX_DB_OP_NORMAL_OAMACK = 122,

	/* tx rsv*/
	NBL_STATS_TYPE_TX_RSV_123 = 123,
	NBL_STATS_TYPE_TX_RSV_124 = 124,
	NBL_STATS_TYPE_TX_RSV_125 = 125,
	NBL_STATS_TYPE_TX_RSV_126 = 126,
	NBL_STATS_TYPE_TX_RSV_127 = 127,
	NBL_STATS_TYPE_OP_MAX = 128
};

enum nbl_qp_errcode_stats_index {
	/* rxp normal request */
	NBL_STATS_TYPE_RXP_NORMAL_REQ = 0,
	NBL_STATS_TYPE_RXP_NORMAL_RESP = 1,
	/* rxp packet error 2-31 */
	NBL_STATS_TYPE_RXP_PACKET_ERR_ETH_TVER_CHECK_ERR = 2,
	NBL_STATS_TYPE_RXP_PACKET_ERR_INVAILD_SERVICE_TYPE = 3,
	NBL_STATS_TYPE_RXP_PACKET_ERR_QPC_STATE_ERROR = 4,
	NBL_STATS_TYPE_RXP_PACKET_ERR_RC_BTH_OPCODE_EQ_RSV = 5,
	NBL_STATS_TYPE_RXP_PACKET_ERR_UD_BTH_OPCODE_EQ_RSV = 6,
	NBL_STATS_TYPE_RXP_PACKET_ERR_RX_1_3_CLASS_C_K = 7,
	NBL_STATS_TYPE_RXP_PACKET_ERR_ORQ_PI_FLAG_NEQ_ORQ_CI_FLAG = 8,
	NBL_STATS_TYPE_RXP_PACKET_ERR_RX_1_6_CLASS_C_K = 9,

	NBL_STATS_TYPE_RXP_PACKET_ERR_10 = 10,
	NBL_STATS_TYPE_RXP_PACKET_ERR_11 = 11,
	NBL_STATS_TYPE_RXP_PACKET_ERR_12 = 12,
	NBL_STATS_TYPE_RXP_PACKET_ERR_13 = 13,
	NBL_STATS_TYPE_RXP_PACKET_ERR_14 = 14,
	NBL_STATS_TYPE_RXP_PACKET_ERR_15 = 15,
	NBL_STATS_TYPE_RXP_PACKET_ERR_16 = 16,
	NBL_STATS_TYPE_RXP_PACKET_ERR_17 = 17,
	NBL_STATS_TYPE_RXP_PACKET_ERR_18 = 18,
	NBL_STATS_TYPE_RXP_PACKET_ERR_19 = 19,
	NBL_STATS_TYPE_RXP_PACKET_ERR_20 = 20,
	NBL_STATS_TYPE_RXP_PACKET_ERR_21 = 21,
	NBL_STATS_TYPE_RXP_PACKET_ERR_22 = 22,
	NBL_STATS_TYPE_RXP_PACKET_ERR_23 = 23,
	NBL_STATS_TYPE_RXP_PACKET_ERR_24 = 24,
	NBL_STATS_TYPE_RXP_PACKET_ERR_25 = 25,
	NBL_STATS_TYPE_RXP_PACKET_ERR_26 = 26,
	NBL_STATS_TYPE_RXP_PACKET_ERR_27 = 27,
	NBL_STATS_TYPE_RXP_PACKET_ERR_28 = 28,
	NBL_STATS_TYPE_RXP_PACKET_ERR_29 = 29,
	NBL_STATS_TYPE_RXP_PACKET_ERR_30 = 30,
	NBL_STATS_TYPE_RXP_PACKET_ERR_31 = 31,
	/* rxp request error */
	NBL_STATS_TYPE_ERR_RXP_REQ__32 = 32,
	NBL_STATS_TYPE_ERR_RXP_REQ__33 = 33,
	NBL_STATS_TYPE_ERR_RXP_REQ__34 = 34,
	NBL_STATS_TYPE_ERR_RXP_REQ__35 = 35,
	NBL_STATS_TYPE_ERR_RXP_REQ__36 = 36,
	NBL_STATS_TYPE_ERR_RXP_REQ__37 = 37,
	NBL_STATS_TYPE_ERR_RXP_REQ__38 = 38,
	NBL_STATS_TYPE_ERR_RXP_REQ__39 = 39,
	/* rxp response error */
	NBL_STATS_TYPE_ERR_RXP_RESP_40 = 40,
	NBL_STATS_TYPE_ERR_RXP_RESP_41 = 41,
	NBL_STATS_TYPE_ERR_RXP_RESP_42 = 42,
	NBL_STATS_TYPE_ERR_RXP_RESP_43 = 43,
	NBL_STATS_TYPE_ERR_RXP_RESP_44 = 44,
	NBL_STATS_TYPE_ERR_RXP_RESP_45 = 45,
	NBL_STATS_TYPE_ERR_RXP_RESP_46 = 46,
	NBL_STATS_TYPE_ERR_RXP_RESP_47 = 47,
	NBL_STATS_TYPE_ERR_RXP_RESP_48 = 48,
	NBL_STATS_TYPE_ERR_RXP_RESP_49 = 49,
	NBL_STATS_TYPE_ERR_RXP_RESP_50 = 50,
	NBL_STATS_TYPE_ERR_RXP_RESP_51 = 51,
	NBL_STATS_TYPE_ERR_RXP_RESP_52 = 52,
	NBL_STATS_TYPE_ERR_RXP_RESP_53 = 53,
	NBL_STATS_TYPE_ERR_RXP_RESP_54 = 54,
	/* rx mr */
	NBL_STATS_TYPE_ERR_RXMR_55 = 55,
	NBL_STATS_TYPE_ERR_RXMR_56 = 56,
	NBL_STATS_TYPE_ERR_RXMR_57 = 57,
	NBL_STATS_TYPE_ERR_RXMR_58 = 58,
	NBL_STATS_TYPE_ERR_RXMR_59 = 59,
	NBL_STATS_TYPE_ERR_RXMR_60 = 60,
	NBL_STATS_TYPE_ERR_RXMR_61 = 61,
	NBL_STATS_TYPE_ERR_RXMR_62 = 62,
	NBL_STATS_TYPE_ERR_RXMR_63 = 63,
	NBL_STATS_TYPE_ERR_RXMR_64 = 64,
	NBL_STATS_TYPE_ERR_RXMR_65 = 65,
	NBL_STATS_TYPE_ERR_RXMR_66 = 66,
	NBL_STATS_TYPE_ERR_RXMR_67 = 67,
	NBL_STATS_TYPE_ERR_RXMR_68 = 68,
	NBL_STATS_TYPE_ERR_RXMR_69 = 69,
	NBL_STATS_TYPE_ERR_RXMR_70 = 70,
	NBL_STATS_TYPE_ERR_RXMR_71 = 71,
	/* CEAQ RAQP */
	NBL_STATS_TYPE_ERR_72 = 72,
	NBL_STATS_TYPE_ERR_73 = 73,
	NBL_STATS_TYPE_ERR_74 = 74,
	NBL_STATS_TYPE_ERR_75 = 75,
	NBL_STATS_TYPE_ERR_76 = 76,
	NBL_STATS_TYPE_ERR_77 = 77,
	NBL_STATS_TYPE_ERR_78 = 78,
	NBL_STATS_TYPE_ERR_79 = 79,
	/* normal */
	NBL_STATS_TYPE_TXP_REQ = 80,
	NBL_STATS_TYPE_TXP_RESP = 81,
	/* TXP */
	NBL_STATS_TYPE_ERR_TXP_82 = 82,
	NBL_STATS_TYPE_ERR_TXP_83 = 83,
	NBL_STATS_TYPE_ERR_TXP_84 = 84,
	NBL_STATS_TYPE_ERR_TXP_85 = 85,
	NBL_STATS_TYPE_ERR_TXP_86 = 86,
	NBL_STATS_TYPE_ERR_TXP_87 = 87,
	NBL_STATS_TYPE_ERR_TXP_88 = 88,
	NBL_STATS_TYPE_ERR_TXP_89 = 89,
	NBL_STATS_TYPE_ERR_TXP_90 = 90,
	NBL_STATS_TYPE_ERR_TXP_91 = 91,
	NBL_STATS_TYPE_ERR_TXP_92 = 92,
	NBL_STATS_TYPE_ERR_TXP_93 = 93,
	NBL_STATS_TYPE_ERR_TXP_94 = 94,
	NBL_STATS_TYPE_ERR_TXP_95 = 95,
	/* tx mr */
	NBL_STATS_TYPE_ERR_TXMR_96 = 96,
	NBL_STATS_TYPE_ERR_TXMR_97 = 97,
	NBL_STATS_TYPE_ERR_TXMR_98 = 98,
	NBL_STATS_TYPE_ERR_TXMR_99 = 99,
	NBL_STATS_TYPE_ERR_TXMR_100 = 100,
	NBL_STATS_TYPE_ERR_TXMR_101 = 101,
	NBL_STATS_TYPE_ERR_TXMR_102 = 102,
	NBL_STATS_TYPE_ERR_TXMR_103 = 103,
	NBL_STATS_TYPE_ERR_TXMR_104 = 104,
	NBL_STATS_TYPE_ERR_TXMR_105 = 105,
	NBL_STATS_TYPE_ERR_TXMR_106 = 106,
	NBL_STATS_TYPE_ERR_TXMR_107 = 107,
	NBL_STATS_TYPE_ERR_TXMR_108 = 108,
	NBL_STATS_TYPE_ERR_TXMR_109 = 109,
	NBL_STATS_TYPE_ERR_TXMR_110 = 110,
	NBL_STATS_TYPE_ERR_TXMR_111 = 111,
	NBL_STATS_TYPE_ERR_TXMR_112 = 112,
	NBL_STATS_TYPE_ERR_TXMR_113 = 113,
	NBL_STATS_TYPE_ERR_TXMR_114 = 114,
	NBL_STATS_TYPE_ERR_TXMR_115 = 115,
	NBL_STATS_TYPE_ERR_TXMR_116 = 116,
	NBL_STATS_TYPE_ERR_TXMR_117 = 117,
	NBL_STATS_TYPE_ERR_TXMR_118 = 118,
	NBL_STATS_TYPE_ERR_TXMR_119 = 119,
	/* rsv */
	NBL_STATS_TYPE_ERR_RSV_120 = 120,
	NBL_STATS_TYPE_ERR_RSV_121 = 121,
	NBL_STATS_TYPE_ERR_RSV_122 = 122,
	NBL_STATS_TYPE_ERR_RSV_123 = 123,
	NBL_STATS_TYPE_ERR_RSV_124 = 124,
	NBL_STATS_TYPE_ERR_RSV_125 = 125,
	NBL_STATS_TYPE_ERR_RSV_126 = 126,
	NBL_STATS_TYPE_ERR_RSV_127 = 127,
	NBL_STATS_TYPE_ERR_MAX = 128
};

int update_vf_stats(struct nbl_device *nbl_dev);
int update_qp_stats(struct nbl_device *nbl_dev, int stat_id);
int update_err_qpn_stats(struct nbl_device *nbl_dev);
int update_all_stats(struct nbl_device *nbl_dev);
void nbl_stats_mem_clear(struct nbl_device *nbl_dev,
					struct nbl_stats_reg_info *reg_info);

int nbl_grc_add_stat_id(struct nbl_pci_f *rf,
					u16 func_id, u32 qp_id, u8 *req_stat_id);
int nbl_grc_del_stat_id(struct nbl_pci_f *rf, u8 stat_id, u16 func_id, u32 qp_id);
int nbl_grc_mod_stat_id(struct nbl_pci_f *rf,
					u8 stat_id_old, u8 stat_id_new, u16 func_id, u32 qp_id);
int nbl_grc_get_used_cnt(struct nbl_pci_f *rf, u8 stat_id, u32 *req_used_cnt);
int nbl_grc_hw_stat_clear(struct nbl_pci_f *rf,
						struct nbl_stats_reg_info *reg_info);
int nbl_grc_hw_stat_errcode_enable(struct nbl_pci_f *rf, bool enable);

void nbl_hw_stats_start_timer(struct nbl_device *nbl_dev, u32 time);
void nbl_hw_stats_stop_timer(struct nbl_device *nbl_dev);

int nbl_counters_func_init(struct nbl_device *nbl_dev);
void nbl_counters_func_deinit(struct nbl_device *nbl_dev);

struct rdma_hw_stats *nbl_alloc_hw_stats(struct ib_device *ibdev, u32 port_num);

int nbl_get_hw_stats(struct ib_device *ibdev, struct rdma_hw_stats *stats,
			u32 port_num, int index);

int nbl_grc_read_ecn_stat(struct nbl_pci_f *rf, struct get_ecn_cnt_tbl_resp *grc_resp);
#endif /* NBL_IB_COUNTERS_H */
