# SPDX-License-Identifier: GPL-2.0-or-later
#
# This file is part of tsse driver for Linux
#
# Copyright © 2023 Montage Technology. All rights reserved.

obj-m += tsse.o

tsse-objs := tsse_dev_mgr.o \
	tsse_ipc.o \
	tsse_fw_service.o \
	tsse_service.o \
	tsse_irq.o \
	tsse_dev_drv.o \
	tsse_vuart.o
