#*******************************************************************************
#*******************************************************************************

include_directories(${CMAKE_CURRENT_SOURCE_DIR})

#*******************************************************************************
#*******************************************************************************

#aux_source_directory(.          CLIENT_SRC)
set(CLIENT_SRC fs_client.c)

#*******************************************************************************
#*******************************************************************************

add_library(client ${CLIENT_SRC})
target_link_libraries(client infra
                             securec)
