/* SPDX-License-Identifier: GPL-2.0 */
/* Copyright(c) 2021 Ramaxel Memory Technology, Ltd */

#ifndef SPHW_CSR_H
#define SPHW_CSR_H

/* bit30/bit31 for bar index flag
 * 00: bar0
 * 01: bar1
 * 10: bar2
 * 11: bar3
 */
#define SPHW_CFG_REGS_FLAG			0x40000000

#define SPHW_MGMT_REGS_FLAG			0xC0000000

#define SPHW_REGS_FLAG_MAKS			0x3FFFFFFF

#define SPHW_VF_CFG_REG_OFFSET			0x2000

#define SPHW_HOST_CSR_BASE_ADDR			(SPHW_MGMT_REGS_FLAG + 0x6000)
#define SPHW_CSR_GLOBAL_BASE_ADDR		(SPHW_MGMT_REGS_FLAG + 0x6400)

/* HW interface registers */
#define SPHW_CSR_FUNC_ATTR0_ADDR		(SPHW_CFG_REGS_FLAG + 0x0)
#define SPHW_CSR_FUNC_ATTR1_ADDR		(SPHW_CFG_REGS_FLAG + 0x4)
#define SPHW_CSR_FUNC_ATTR2_ADDR		(SPHW_CFG_REGS_FLAG + 0x8)
#define SPHW_CSR_FUNC_ATTR3_ADDR		(SPHW_CFG_REGS_FLAG + 0xC)
#define SPHW_CSR_FUNC_ATTR4_ADDR		(SPHW_CFG_REGS_FLAG + 0x10)
#define SPHW_CSR_FUNC_ATTR5_ADDR		(SPHW_CFG_REGS_FLAG + 0x14)
#define SPHW_CSR_FUNC_ATTR6_ADDR		(SPHW_CFG_REGS_FLAG + 0x18)

#define SPHW_FUNC_CSR_MAILBOX_DATA_OFF		0x80
#define SPHW_FUNC_CSR_MAILBOX_CONTROL_OFF		\
			(SPHW_CFG_REGS_FLAG + 0x0100)
#define SPHW_FUNC_CSR_MAILBOX_INT_OFFSET_OFF		\
			(SPHW_CFG_REGS_FLAG + 0x0104)
#define SPHW_FUNC_CSR_MAILBOX_RESULT_H_OFF		\
			(SPHW_CFG_REGS_FLAG + 0x0108)
#define SPHW_FUNC_CSR_MAILBOX_RESULT_L_OFF		\
			(SPHW_CFG_REGS_FLAG + 0x010C)

#define SPHW_PPF_ELECTION_OFFSET		0x0
#define SPHW_MPF_ELECTION_OFFSET		0x20

#define SPHW_CSR_PPF_ELECTION_ADDR		\
			(SPHW_HOST_CSR_BASE_ADDR + SPHW_PPF_ELECTION_OFFSET)

#define SPHW_CSR_GLOBAL_MPF_ELECTION_ADDR		\
			(SPHW_HOST_CSR_BASE_ADDR + SPHW_MPF_ELECTION_OFFSET)

#define SPHW_CSR_FUNC_PPF_ELECT_BASE_ADDR	(SPHW_CFG_REGS_FLAG + 0x60)
#define SPHW_CSR_FUNC_PPF_ELECT_PORT_STRIDE	0x4

#define SPHW_CSR_FUNC_PPF_ELECT(host_idx)	\
	(SPHW_CSR_FUNC_PPF_ELECT_BASE_ADDR +	\
	 (host_idx) * SPHW_CSR_FUNC_PPF_ELECT_PORT_STRIDE)

#define SPHW_CSR_DMA_ATTR_TBL_ADDR		(SPHW_CFG_REGS_FLAG + 0x380)
#define SPHW_CSR_DMA_ATTR_INDIR_IDX_ADDR	(SPHW_CFG_REGS_FLAG + 0x390)

/* MSI-X registers */
#define SPHW_CSR_MSIX_INDIR_IDX_ADDR		(SPHW_CFG_REGS_FLAG + 0x310)
#define SPHW_CSR_MSIX_CTRL_ADDR			(SPHW_CFG_REGS_FLAG + 0x300)
#define SPHW_CSR_MSIX_CNT_ADDR			(SPHW_CFG_REGS_FLAG +	0x304)
#define SPHW_CSR_FUNC_MSI_CLR_WR_ADDR		(SPHW_CFG_REGS_FLAG + 0x58)

#define SPHW_MSI_CLR_INDIR_RESEND_TIMER_CLR_SHIFT	0
#define SPHW_MSI_CLR_INDIR_INT_MSK_SET_SHIFT		1
#define SPHW_MSI_CLR_INDIR_INT_MSK_CLR_SHIFT		2
#define SPHW_MSI_CLR_INDIR_AUTO_MSK_SET_SHIFT		3
#define SPHW_MSI_CLR_INDIR_AUTO_MSK_CLR_SHIFT		4
#define SPHW_MSI_CLR_INDIR_SIMPLE_INDIR_IDX_SHIFT	22

#define SPHW_MSI_CLR_INDIR_RESEND_TIMER_CLR_MASK	0x1U
#define SPHW_MSI_CLR_INDIR_INT_MSK_SET_MASK		0x1U
#define SPHW_MSI_CLR_INDIR_INT_MSK_CLR_MASK		0x1U
#define SPHW_MSI_CLR_INDIR_AUTO_MSK_SET_MASK		0x1U
#define SPHW_MSI_CLR_INDIR_AUTO_MSK_CLR_MASK		0x1U
#define SPHW_MSI_CLR_INDIR_SIMPLE_INDIR_IDX_MASK	0x3FFU

#define SPHW_MSI_CLR_INDIR_SET(val, member)		\
		(((val) & SPHW_MSI_CLR_INDIR_##member##_MASK) << \
		SPHW_MSI_CLR_INDIR_##member##_SHIFT)

/* EQ registers */
#define SPHW_AEQ_INDIR_IDX_ADDR			(SPHW_CFG_REGS_FLAG + 0x210)
#define SPHW_CEQ_INDIR_IDX_ADDR			(SPHW_CFG_REGS_FLAG + 0x290)

#define SPHW_EQ_INDIR_IDX_ADDR(type) \
		((type == SPHW_AEQ) ? SPHW_AEQ_INDIR_IDX_ADDR : SPHW_CEQ_INDIR_IDX_ADDR)

#define SPHW_AEQ_MTT_OFF_BASE_ADDR		(SPHW_CFG_REGS_FLAG + 0x240)
#define SPHW_CEQ_MTT_OFF_BASE_ADDR		(SPHW_CFG_REGS_FLAG + 0x2C0)

#define SPHW_CSR_EQ_PAGE_OFF_STRIDE		8

#define SPHW_AEQ_HI_PHYS_ADDR_REG(pg_num)	\
		(SPHW_AEQ_MTT_OFF_BASE_ADDR + \
		(pg_num) * SPHW_CSR_EQ_PAGE_OFF_STRIDE)

#define SPHW_AEQ_LO_PHYS_ADDR_REG(pg_num)	\
		(SPHW_AEQ_MTT_OFF_BASE_ADDR + \
		(pg_num) * SPHW_CSR_EQ_PAGE_OFF_STRIDE + 4)

#define SPHW_CEQ_HI_PHYS_ADDR_REG(pg_num)	\
		(SPHW_CEQ_MTT_OFF_BASE_ADDR + \
		(pg_num) * SPHW_CSR_EQ_PAGE_OFF_STRIDE)

#define SPHW_CEQ_LO_PHYS_ADDR_REG(pg_num)	\
		(SPHW_CEQ_MTT_OFF_BASE_ADDR + \
		(pg_num) * SPHW_CSR_EQ_PAGE_OFF_STRIDE + 4)

#define SPHW_CSR_AEQ_CTRL_0_ADDR		(SPHW_CFG_REGS_FLAG + 0x200)
#define SPHW_CSR_AEQ_CTRL_1_ADDR		(SPHW_CFG_REGS_FLAG + 0x204)
#define SPHW_CSR_AEQ_CONS_IDX_ADDR		(SPHW_CFG_REGS_FLAG + 0x208)
#define SPHW_CSR_AEQ_PROD_IDX_ADDR		(SPHW_CFG_REGS_FLAG + 0x20C)
#define SPHW_CSR_AEQ_CI_SIMPLE_INDIR_ADDR	(SPHW_CFG_REGS_FLAG + 0x50)

#define SPHW_CSR_CEQ_CTRL_0_ADDR		(SPHW_CFG_REGS_FLAG + 0x280)
#define SPHW_CSR_CEQ_CTRL_1_ADDR		(SPHW_CFG_REGS_FLAG + 0x284)
#define SPHW_CSR_CEQ_CONS_IDX_ADDR		(SPHW_CFG_REGS_FLAG + 0x288)
#define SPHW_CSR_CEQ_PROD_IDX_ADDR		(SPHW_CFG_REGS_FLAG + 0x28c)
#define SPHW_CSR_CEQ_CI_SIMPLE_INDIR_ADDR	(SPHW_CFG_REGS_FLAG + 0x54)

/* API CMD registers */
#define SPHW_CSR_API_CMD_BASE			(SPHW_MGMT_REGS_FLAG + 0x2000)

#define SPHW_CSR_API_CMD_STRIDE			0x80

#define SPHW_CSR_API_CMD_CHAIN_HEAD_HI_ADDR(idx)	\
	(SPHW_CSR_API_CMD_BASE + 0x0 + (idx) * SPHW_CSR_API_CMD_STRIDE)

#define SPHW_CSR_API_CMD_CHAIN_HEAD_LO_ADDR(idx)	\
	(SPHW_CSR_API_CMD_BASE + 0x4 + (idx) * SPHW_CSR_API_CMD_STRIDE)

#define SPHW_CSR_API_CMD_STATUS_HI_ADDR(idx)		\
	(SPHW_CSR_API_CMD_BASE + 0x8 + (idx) * SPHW_CSR_API_CMD_STRIDE)

#define SPHW_CSR_API_CMD_STATUS_LO_ADDR(idx)		\
	(SPHW_CSR_API_CMD_BASE + 0xC + (idx) * SPHW_CSR_API_CMD_STRIDE)

#define SPHW_CSR_API_CMD_CHAIN_NUM_CELLS_ADDR(idx)	\
	(SPHW_CSR_API_CMD_BASE + 0x10 + (idx) * SPHW_CSR_API_CMD_STRIDE)

#define SPHW_CSR_API_CMD_CHAIN_CTRL_ADDR(idx)		\
	(SPHW_CSR_API_CMD_BASE + 0x14 + (idx) * SPHW_CSR_API_CMD_STRIDE)

#define SPHW_CSR_API_CMD_CHAIN_PI_ADDR(idx)		\
	(SPHW_CSR_API_CMD_BASE + 0x1C + (idx) * SPHW_CSR_API_CMD_STRIDE)

#define SPHW_CSR_API_CMD_CHAIN_REQ_ADDR(idx)		\
	(SPHW_CSR_API_CMD_BASE + 0x20 + (idx) * SPHW_CSR_API_CMD_STRIDE)

#define SPHW_CSR_API_CMD_STATUS_0_ADDR(idx)		\
	(SPHW_CSR_API_CMD_BASE + 0x30 + (idx) * SPHW_CSR_API_CMD_STRIDE)

#endif
