# SPDX-License-Identifier: GPL-2.0

generic-y += clkdev.h
generic-y += export.h
generic-y += kvm_types.h
generic-y += mcs_spinlock.h
generic-y += qrwlock.h
generic-y += qspinlock.h
generic-y += rwsem.h
generic-y += scatterlist.h
generic-y += user.h
generated-y += syscall_table.h
