obj-$(CONFIG_MGBEVF) += rnpgbevf.o
rnpgbevf-objs :=   \
		vf.o \
                rnpgbevf_mbx.o \
                rnpgbevf_ethtool.o \
                rnpgbevf_sysfs.o \
                rnpgbevf_main.o

