/* SPDX-License-Identifier: GPL-2.0 */
/* Copyright (c) LD. */
#ifndef _PS3_KERNEL_VERSION_H_
#define _PS3_KERNEL_VERSION_H_

#define DRIVER_SUPPORT_PRIV_BUSY
#define PS3_TRACK_QUEUE_DEPTH
#define PS3_SUPPORT_PCIE_REPORT
#define PS3_SUPPORT_CMD_SCP
#define PS3_SUPPORT_DRIVER_SENSE
#define PS3_SUPPORT_FS
#define PS3_DID_NEXUS_FAILURE
#define PS3_FALLTHROUGH
#define PS3_SYPPORT_BIO_ITER
#define PS3_AER_CLEAR_STATUS
#define PS3_LINUX_SIGNAL
#define DRIVER_SUPPORT_KERNEL_IRQ_AFFINITY
#define PS3_OS_MANAGED_IRQ_SUPPORT
#define PS3_CMD_CDB_CHECK
#include <linux/blk-mq-pci.h>
#ifndef PS3_TAGSET_SUPPORT
#define PS3_TAGSET_SUPPORT
#endif
#define PS3_FSNOTIFY_FILE
#define PS3_KERNEL_WRITE_FILE
#define PS3_BLK_QUEUE_FLAG_CLEAR
#define PS3_STATIC_MINOR
#define PS3_SUPPORT_FLUSH_SCHEDULED
#define PS3_MAP_QUEUES_RET

#endif
