/* SPDX-License-Identifier: GPL-2.0 */
/* Copyright (c) 2023 - 2024 ZTE Corporation */

//generate function cmdlist from symbol file

#ifndef DPP_CMD_SHELL_H
#define DPP_CMD_SHELL_H

#include "zxic_common.h"
#include "dpp_dtb.h"
#include "dpp_tbl_diag.h"

struct DPP_COMMAND {
	char *name;
	char *doc;
	void *func;
};

u32 dpp_cmd_help(void);

struct DPP_COMMAND dpp_commands[] = {
	{ "dpp_cmd_help", "none", dpp_cmd_help },
	{ "zxic_comm_set_print_level", "debug_level", zxic_comm_set_print_level },
	{ "zxic_comm_set_print_en", "enable", zxic_comm_set_print_en },
	{ "diag_dpp_sdt_tbl_prt", "sdt_no", diag_dpp_sdt_tbl_prt },
	{ "diag_dpp_se_smmu0_wr64", "slot vport base_addr index data0 data1",
	  diag_dpp_se_smmu0_wr64 },
	{ "diag_dpp_se_smmu0_rd64", "slot vport base_addr index", diag_dpp_se_smmu0_rd64 },
	{ "diag_dpp_se_smmu0_wr128", "slot vport base_addr index data0 data1 data2 data3",
	  diag_dpp_se_smmu0_wr128 },
	{ "diag_dpp_se_smmu0_rd128", "slot vport base_addr index", diag_dpp_se_smmu0_rd128 },
	{ "diag_dpp_vport_mac_add", "slot vport sriov_vlan_tpid sriov_vlan_id mac0...5",
	  diag_dpp_vport_mac_add },
	{ "diag_dpp_vport_mac_del", "slot vport sriov_vlan_tpid sriov_vlan_id mac0...5",
	  diag_dpp_vport_mac_del },
	{ "diag_dpp_vport_batch_mac_add", "slot vport mac_num vlanid mac16 mac32",
	  diag_dpp_vport_batch_mac_add },
	{ "diag_dpp_vport_batch_mac_del", "slot vport mac_num vlanid mac16 mac32",
	  diag_dpp_vport_batch_mac_del },
	{ "diag_dpp_vport_mac_transter", "slot vport new_vport", diag_dpp_vport_mac_transter },
	{ "diag_dpp_vport_mac_max_num", "slot vport", diag_dpp_vport_mac_max_num },
	{ "diag_dpp_vport_mac_flush_online", "slot vport", diag_dpp_vport_mac_flush_online },
	{ "diag_dpp_vport_mac_flush_offline", "slot vport", diag_dpp_vport_mac_flush_offline },
	{ "diag_dpp_vport_mac_search", "slot vport sriov_vlan_tpid sriov_vlan_id mac0...5",
	  diag_dpp_vport_mac_search },
	{ "diag_dpp_vport_mac_prt", "slot vport", diag_dpp_vport_mac_prt },
	{ "diag_dpp_vport_mc_mac_add", "slot vport mac0...5", diag_dpp_vport_mc_mac_add },
	{ "diag_dpp_vport_mc_mac_del", "slot vport mac0...5", diag_dpp_vport_mc_mac_del },
	{ "diag_dpp_vport_batch_mc_mac_add", "slot vport mac_num mac0...5",
	  diag_dpp_vport_batch_mc_mac_add },
	{ "diag_dpp_vport_batch_mc_mac_del", "slot vport mac_num mac0...5",
	  diag_dpp_vport_batch_mc_mac_del },
	{ "diag_dpp_vport_mc_mac_transter", "slot vport new_vport",
	  diag_dpp_vport_mc_mac_transter },
	{ "diag_dpp_vport_mc_mac_max_num", "slot vport", diag_dpp_vport_mc_mac_max_num },
	{ "diag_dpp_vport_mc_mac_flush_online", "slot vport", diag_dpp_vport_mc_mac_flush_online },
	{ "diag_dpp_vport_mc_mac_flush_offline", "slot vport",
	  diag_dpp_vport_mc_mac_flush_offline },
	{ "diag_dpp_vport_mc_mac_prt", "slot vport", diag_dpp_vport_mc_mac_prt },
	{ "diag_dpp_vport_table_set", "slot vport attr value", diag_dpp_vport_table_set },
	{ "diag_dpp_vport_table_init", "slot vport", diag_dpp_vport_table_init },
	{ "diag_dpp_vport_table_delete", "slot vport", diag_dpp_vport_table_delete },
	{ "diag_dpp_vport_table_prt", "slot vport", diag_dpp_vport_table_prt },
	{ "diag_dpp_vport_egress_meter_en_set", "slot vport enable",
	  diag_dpp_vport_egress_meter_en_set },
	{ "diag_dpp_vport_egress_meter_en_prt", "slot vport", diag_dpp_vport_egress_meter_en_prt },
	{ "diag_dpp_vport_ingress_meter_en_set", "slot vport enable",
	  diag_dpp_vport_ingress_meter_en_set },
	{ "diag_dpp_vport_ingress_meter_en_prt", "slot vport",
	  diag_dpp_vport_ingress_meter_en_prt },
	{ "diag_dpp_vport_egress_meter_mode_set", "slot vport mode",
	  diag_dpp_vport_egress_meter_mode_set },
	{ "diag_dpp_vport_egress_meter_mode_prt", "slot vport",
	  diag_dpp_vport_egress_meter_mode_prt },
	{ "diag_dpp_vport_ingress_meter_mode_set", "slot vport mode",
	  diag_dpp_vport_ingress_meter_mode_set },
	{ "diag_dpp_vport_ingress_meter_mode_prt", "slot vport",
	  diag_dpp_vport_ingress_meter_mode_prt },
	{ "diag_dpp_vport_rx_flow_hash_set", "slot vport hash_mode",
	  diag_dpp_vport_rx_flow_hash_set },
	{ "diag_dpp_vport_rx_flow_hash_prt", "slot vport", diag_dpp_vport_rx_flow_hash_prt },
	{ "diag_dpp_vport_hash_index_prt", "slot vport", diag_dpp_vport_hash_index_prt },
	{ "diag_dpp_vport_hash_funcs_set", "slot vport funcs", diag_dpp_vport_hash_funcs_set },
	{ "diag_dpp_vport_rss_en_set", "slot vport enable", diag_dpp_vport_rss_en_set },
	{ "diag_dpp_vport_virtio_en_set", "slot vport enable", diag_dpp_vport_virtio_en_set },
	{ "diag_dpp_vport_virtio_version_set", "slot vport version",
	  diag_dpp_vport_virtio_version_set },
	{ "diag_dpp_vport_promisc_en_set", "slot vport enable", diag_dpp_vport_promisc_en_set },
	{ "diag_dpp_vport_business_vlan_offload_en_set", "slot vport enable",
	  diag_dpp_vport_business_vlan_offload_en_set },
	{ "diag_dpp_vport_vlan_offload_en_set", "slot vport enable",
	  diag_dpp_vport_vlan_offload_en_set },
	{ "diag_dpp_uplink_phy_port_table_set", "slot vport uplink_phy_port_id attr value",
	  diag_dpp_uplink_phy_port_table_set },
	{ "diag_dpp_uplink_phy_port_table_prt", "slot vport uplink_phy_port_id",
	  diag_dpp_uplink_phy_port_table_prt },
	{ "diag_dpp_uplink_phy_bond_vport", "slot vport port_id", diag_dpp_uplink_phy_bond_vport },
	{ "diag_dpp_uplink_phy_hardware_bond_set", "slot vport port_id enable",
	  diag_dpp_uplink_phy_hardware_bond_set },
	{ "diag_dpp_uplink_phy_lacp_pf_vqm_vfid_set", "slot vport port_id vqm_vfid",
	  diag_dpp_uplink_phy_lacp_pf_vqm_vfid_set },
	{ "diag_dpp_uplink_phy_lacp_pf_memport_qid_set", "slot vport port_id qid",
	  diag_dpp_uplink_phy_lacp_pf_memport_qid_set },
	{ "diag_dpp_ptp_port_vfid_set", "slot vport ptp_port_vfid", diag_dpp_ptp_port_vfid_set },
	{ "diag_dpp_ptp_tc_enable_set", "slot vport ptp_tc_enable", diag_dpp_ptp_tc_enable_set },
	{ "diag_dpp_tm_flowid_pport_table_set", "slot vport port_id flow_id",
	  diag_dpp_tm_flowid_pport_table_set },
	{ "diag_dpp_tm_flowid_pport_table_del", "slot vport port_id",
	  diag_dpp_tm_flowid_pport_table_del },
	{ "diag_dpp_tm_pport_trust_mode_table_set", "slot vport port_id mode",
	  diag_dpp_tm_pport_trust_mode_table_set },
	{ "diag_dpp_tm_pport_trust_mode_table_del", "slot vport port_id",
	  diag_dpp_tm_pport_trust_mode_table_del },
	{ "diag_dpp_tm_pport_mcode_switch_set", "slot vport port_id mode",
	  diag_dpp_tm_pport_mcode_switch_set },
	{ "diag_dpp_tm_pport_mcode_switch_del", "slot vport port_id",
	  diag_dpp_tm_pport_mcode_switch_del },
	{ "diag_dpp_vport_bc_table_set", "slot vport enable", diag_dpp_vport_bc_table_set },
	{ "diag_dpp_vport_bc_table_prt", "slot vport", diag_dpp_vport_bc_table_prt },
	{ "diag_dpp_vport_uc_promisc_table_set", "slot vport enable",
	  diag_dpp_vport_uc_promisc_table_set },
	{ "diag_dpp_vport_uc_promisc_table_prt", "slot vport",
	  diag_dpp_vport_uc_promisc_table_prt },
	{ "diag_dpp_vport_mc_promisc_table_set", "slot vport enable",
	  diag_dpp_vport_mc_promisc_table_set },
	{ "diag_dpp_vport_mc_promisc_table_prt", "slot vport",
	  diag_dpp_vport_mc_promisc_table_prt },
	{ "dpp_dtb_prt_disable", "none", dpp_dtb_prt_disable },
	{ "dpp_dtb_prt_enable", "none", dpp_dtb_prt_enable },
	{ "dpp_dtb_debug_fun_enable", "none", dpp_dtb_debug_fun_enable },
	{ "dpp_dtb_debug_fun_disable", "none", dpp_dtb_debug_fun_disable },
	{ "dpp_dtb_soft_perf_test_set", "value", dpp_dtb_soft_perf_test_set },
	{ "dpp_dtb_hardware_perf_test_set", "value", dpp_dtb_hardware_perf_test_set },
	{ "dpp_dtb_down_table_overtime_set", "times_s", dpp_dtb_down_table_overtime_set },
	{ "dpp_dtb_dump_table_overtime_set", "times_s", dpp_dtb_dump_table_overtime_set },
	{ "diag_dpp_rdma_trans_item_add", "rdma", diag_dpp_rdma_trans_item_add },
	{ "diag_dpp_rdma_trans_item_del", "rdma", diag_dpp_rdma_trans_item_del },
	{ "diag_dpp_pcie_channel_prt", "none", diag_dpp_pcie_channel_prt },
	{ "diag_dpp_se_hash_stat_prt", "slot fun_id", diag_dpp_se_hash_stat_prt },
	{ "diag_dpp_se_hash_stat_clr", "slot fun_id", diag_dpp_se_hash_stat_clr },
	{ "diag_dpp_hash_item_prt", "slot sdt", diag_dpp_hash_item_prt },
	{ "diag_dpp_vqm_vfid_vlan_init", "slot vport", diag_dpp_vqm_vfid_vlan_init },
	{ "diag_dpp_vqm_vfid_vlan_delete", "slot vport", diag_dpp_vqm_vfid_vlan_delete },
	{ "diag_dpp_vqm_vfid_vlan_set", "slot vport attr value", diag_dpp_vqm_vfid_vlan_set },
	{ "diag_dpp_vqm_vfid_vlan_prt", "slot vport", diag_dpp_vqm_vfid_vlan_prt },
	{ "diag_dpp_rxfh_set", "slot vport qid0...3 qnum", diag_dpp_rxfh_set },
	{ "diag_dpp_rxfh_del", "slot vport", diag_dpp_rxfh_del },
	{ "diag_dpp_rxfh_prt", "slot vport", diag_dpp_rxfh_prt },
	{ "diag_dpp_thash_key_set", "slot vport rsk_031_000~rsk_319_288", diag_dpp_thash_key_set },
	{ "diag_dpp_thash_key_prt", "slot vport", diag_dpp_thash_key_prt },
	{ "diag_dpp_vport_register_info_prt", "none", diag_dpp_vport_register_info_prt },
	{ "diag_dpp_stat_mc_packet_rx_cnt_prt", "slot vport index mode",
	  diag_dpp_stat_mc_packet_rx_cnt_prt },
	{ "diag_dpp_stat_bc_packet_rx_cnt_prt", "slot vport index mode",
	  diag_dpp_stat_bc_packet_rx_cnt_prt },
	{ "diag_dpp_stat_1588_packet_rx_cnt_prt", "slot vport index mode",
	  diag_dpp_stat_1588_packet_rx_cnt_prt },
	{ "diag_dpp_stat_1588_packet_tx_cnt_prt", "slot vport index mode",
	  diag_dpp_stat_1588_packet_tx_cnt_prt },
	{ "diag_dpp_stat_1588_packet_drop_cnt_prt", "slot vport index mode",
	  diag_dpp_stat_1588_packet_drop_cnt_prt },
	{ "diag_dpp_stat_1588_enc_packet_rx_cnt_prt", "slot vport index mode",
	  diag_dpp_stat_1588_enc_packet_rx_cnt_prt },
	{ "diag_dpp_stat_1588_enc_packet_tx_cnt_prt", "slot vport index mode",
	  diag_dpp_stat_1588_enc_packet_tx_cnt_prt },
	{ "diag_dpp_stat_spoof_packet_drop_cnt_prt", "slot vport index mode",
	  diag_dpp_stat_spoof_packet_drop_cnt_prt },
	{ "diag_dpp_stat_mcode_packet_cnt_prt", "slot vport index mode",
	  diag_dpp_stat_mcode_packet_cnt_prt },
	{ "diag_dpp_stat_port_RDMA_packet_msg_tx_cnt_prt", "slot vport index mode",
	  diag_dpp_stat_port_RDMA_packet_msg_tx_cnt_prt },
	{ "diag_dpp_stat_port_RDMA_packet_msg_rx_cnt_prt", "slot vport index mode",
	  diag_dpp_stat_port_RDMA_packet_msg_rx_cnt_prt },
	{ "diag_dpp_stat_plcr_packet_drop_tx_cnt_prt", "slot vport index mode",
	  diag_dpp_stat_plcr_packet_drop_tx_cnt_prt },
	{ "diag_dpp_stat_plcr_packet_drop_rx_cnt_prt", "slot vport index mode",
	  diag_dpp_stat_plcr_packet_drop_rx_cnt_prt },
	{ "diag_dpp_stat_MTU_packet_msg_tx_cnt_prt", "slot vport index mode",
	  diag_dpp_stat_MTU_packet_msg_tx_cnt_prt },
	{ "diag_dpp_stat_MTU_packet_msg_rx_cnt_prt", "slot vport index mode",
	  diag_dpp_stat_MTU_packet_msg_rx_cnt_prt },
	{ "diag_dpp_stat_port_uc_packet_rx_cnt_prt", "slot vport index mode",
	  diag_dpp_stat_port_uc_packet_rx_cnt_prt },
	{ "diag_dpp_stat_port_uc_packet_tx_cnt_prt", "slot vport index mode",
	  diag_dpp_stat_port_uc_packet_tx_cnt_prt },
	{ "diag_dpp_stat_port_mc_packet_rx_cnt_prt", "slot vport index mode",
	  diag_dpp_stat_port_mc_packet_rx_cnt_prt },
	{ "diag_dpp_stat_port_mc_packet_tx_cnt_prt", "slot vport index mode",
	  diag_dpp_stat_port_mc_packet_tx_cnt_prt },
	{ "diag_dpp_stat_port_bc_packet_rx_cnt_prt", "slot vport index mode",
	  diag_dpp_stat_port_bc_packet_rx_cnt_prt },
	{ "diag_dpp_stat_port_bc_packet_tx_cnt_prt", "slot vport index mode",
	  diag_dpp_stat_port_bc_packet_tx_cnt_prt },
	{ "diag_dpp_stat_asn_phyport_rx_pkt_cnt_get", "slot vport index mode",
	  diag_dpp_stat_asn_phyport_rx_pkt_cnt_get },
	{ "diag_dpp_stat_psn_phyport_tx_pkt_cnt_get", "slot vport index mode",
	  diag_dpp_stat_psn_phyport_tx_pkt_cnt_get },
	{ "diag_dpp_stat_psn_phyport_rx_pkt_cnt_get", "slot vport index mode",
	  diag_dpp_stat_psn_phyport_rx_pkt_cnt_get },
	{ "diag_dpp_stat_psn_ack_phyport_tx_pkt_cnt_get", "slot vport index mode",
	  diag_dpp_stat_psn_ack_phyport_tx_pkt_cnt_get },
	{ "diag_dpp_stat_psn_ack_phyport_rx_pkt_cnt_get", "slot vport index mode",
	  diag_dpp_stat_psn_ack_phyport_rx_pkt_cnt_get },
	{ "diag_dpp_lag_group_create", "slot vport lag_id", diag_dpp_lag_group_create },
	{ "diag_dpp_lag_group_delete", "slot vport lag_id", diag_dpp_lag_group_delete },
	{ "diag_dpp_lag_mode_set", "slot vport lag_id mode", diag_dpp_lag_mode_set },
	{ "diag_dpp_lag_group_hash_factor_set", "slot vport lag_id factor",
	  diag_dpp_lag_group_hash_factor_set },
	{ "diag_dpp_lag_group_member_add", "slot vport lag_id uplink_phy_port_id",
	  diag_dpp_lag_group_member_add },
	{ "diag_dpp_lag_group_member_del", "slot vport lag_id uplink_phy_port_id",
	  diag_dpp_lag_group_member_del },
	{ "diag_dpp_lag_table_prt", "slot vport lag_id", diag_dpp_lag_table_prt },
	{ "diag_dpp_tm_pport_dscp_map_table_set", "slot vport port dscp_id up_id",
	  diag_dpp_tm_pport_dscp_map_table_set },
	{ "diag_dpp_tm_pport_dscp_map_table_del", "slot vport port dscp_id",
	  diag_dpp_tm_pport_dscp_map_table_del },
	{ "diag_dpp_tm_pport_dscp_map_table_prt", "slot vport port dscp_id",
	  diag_dpp_tm_pport_dscp_map_table_prt },
	{ "diag_dpp_tm_pport_up_map_table_set", "slot vport port up_id tc_id",
	  diag_dpp_tm_pport_up_map_table_set },
	{ "diag_dpp_tm_pport_up_map_table_del", "slot vport port up_id",
	  diag_dpp_tm_pport_up_map_table_del },
	{ "diag_dpp_tm_pport_up_map_table_prt", "slot vport port up_id",
	  diag_dpp_tm_pport_up_map_table_prt },
	{ "diag_dpp_vport_vhca_id_add", "slot vport vhca_id", diag_dpp_vport_vhca_id_add },
	{ "diag_dpp_vport_vhca_id_del", "slot vport vhca_id", diag_dpp_vport_vhca_id_del },
	{ "diag_dpp_vport_vhca_id_table_prt", "slot vport vhca_id",
	  diag_dpp_vport_vhca_id_table_prt },
	{ "diag_dpp_vport_reset", "slot vport", diag_dpp_vport_reset },
	{ "diag_dpp_vlan_filter_init", "slot vport", diag_dpp_vlan_filter_init },
	{ "diag_dpp_add_vlan_filter", "slot vport vlan_id", diag_dpp_add_vlan_filter },
	{ "diag_dpp_del_vlan_filter", "slot vport vlan_id", diag_dpp_del_vlan_filter },
	{ "diag_dpp_vlan_filter_table_prt", "slot vport vlan_group_id",
	  diag_dpp_vlan_filter_table_prt },
	{ "diag_dpp_fd_cfg_pre1", "smac dmac sip dip sport dport", diag_dpp_fd_cfg_pre1 },
	{ "diag_dpp_fd_cfg_pre2", "ethertype cvlan_pri vlan vxlan_vni vqm_vfid",
	  diag_dpp_fd_cfg_pre2 },
	{ "diag_dpp_fd_cfg_pre3", "action_index action_index2 count_id hash_alg rss_hash_factor",
	  diag_dpp_fd_cfg_pre3 },
	{ "diag_dpp_fd_cfg_pre4", "uplink_fd_id v_qid", diag_dpp_fd_cfg_pre4 },
	{ "diag_dpp_fd_cfg_add", "slot vport", diag_dpp_fd_cfg_add },
	{ "diag_dpp_fd_cfg_del", "slot vport index", diag_dpp_fd_cfg_del },
	{ "diag_dpp_fd_cfg_get", "slot vport index", diag_dpp_fd_cfg_get },
	{ "diag_dpp_fd_cfg_search", "slot vport index", diag_dpp_fd_cfg_search },
	{ "diag_dpp_acl_glb_data_prt", "", diag_dpp_acl_glb_data_prt },
	{ "diag_dpp_fd_acl_index_req", "slot vport", diag_dpp_fd_acl_index_req },
	{ "diag_dpp_fd_acl_index_rel", "slot vport index", diag_dpp_fd_acl_index_rel },
	{ "diag_dpp_fd_acl_all_delete", "slot vport", diag_dpp_fd_acl_all_delete },
	{ "diag_dpp_dtb_stat_ppu_cnt_clr", "slot vport rd_mode counter_id num",
	  diag_dpp_dtb_stat_ppu_cnt_clr },
	{ "diag_dpp_fd_acl_stat_clear", "slot vport", diag_dpp_fd_acl_stat_clear },
	{ "diag_dpp_se_eram_res_prt", "slot vport", diag_dpp_se_eram_res_prt },
	{ "diag_dpp_se_hash_res_prt", "slot vport", diag_dpp_se_hash_res_prt },
	{ "diag_dpp_se_acl_res_prt", "slot vport", diag_dpp_se_acl_res_prt },
	{ "diag_dpp_se_lpm_res_prt", "slot vport", diag_dpp_se_lpm_res_prt },
	{ "diag_dpp_se_ddr_res_prt", "slot vport", diag_dpp_se_ddr_res_prt },
	{ "diag_dpp_se_stat_res_prt", "slot vport", diag_dpp_se_stat_res_prt },
	{ "diag_dpp_eram_data_stub", "data0 data1 data2 data3", diag_dpp_eram_data_stub },
	{ "diag_dpp_eram_entry_insert", "slot vport sdt index", diag_dpp_eram_entry_insert },
	{ "diag_dpp_eram_entry_delete", "slot vport sdt index", diag_dpp_eram_entry_delete },
	{ "diag_dpp_eram_entry_get", "slot vport sdt index", diag_dpp_eram_entry_get },
	{ "diag_dpp_stat_item_prt", "slot vport stat_item_no", diag_dpp_stat_item_prt },
	{ "diag_dpp_stat_item_prt_all", "slot vport", diag_dpp_stat_item_prt_all },
	{ "diag_dpp_stat_item_cnt_prt", "slot vport stat_item_no index rd_mode",
	  diag_dpp_stat_item_cnt_prt },
	{ "diag_dpp_glb_cfg_set",
	  "slot vport glb_cfg_data_0 glb_cfg_data_1 glb_cfg_data_2 glb_cfg_data_3",
	  diag_dpp_glb_cfg_set },
	{ "diag_dpp_glb_cfg_prt", "slot vport", diag_dpp_glb_cfg_prt },
	{ "diag_dpp_pkt_capture_enable", "slot vport cap_point", diag_dpp_pkt_capture_enable },
	{ "diag_dpp_pkt_capture_disable", "slot vport cap_point", diag_dpp_pkt_capture_disable },
	{ "diag_dpp_pkt_capture_disable_all", "slot vport", diag_dpp_pkt_capture_disable_all },
	{ "diag_dpp_pkt_capture_enable_status_get", "slot vport",
	  diag_dpp_pkt_capture_enable_status_get },
	{ "diag_dpp_pkt_capture_rule_index_to_tcam_index", "rule_index rule_mode cap_point",
	  diag_dpp_pkt_capture_rule_index_to_tcam_index },
	{ "diag_dpp_pkt_capture_tcam_index_to_rule_index", "tcam_index",
	  diag_dpp_pkt_capture_tcam_index_to_rule_index },
	{ "diag_dpp_pkt_capture_item_l2_set", "dmac_0 dmac_1 smac_0 smac_1 ethtype",
	  diag_dpp_pkt_capture_item_l2_set },
	{ "diag_dpp_pkt_capture_item_l3_set",
	  "sip_0 sip_1 sip_2 sip_3 dip0 dip_1 dip_2 dip_3 protocol",
	  diag_dpp_pkt_capture_item_l3_set },
	{ "diag_dpp_pkt_capture_item_l4_set", "dport sport qp", diag_dpp_pkt_capture_item_l4_set },
	{ "diag_dpp_pkt_capture_item_kw_set", "kw_0 kw_1 kw_2 kw_3 kw_off kw_len",
	  diag_dpp_pkt_capture_item_kw_set },
	{ "diag_dpp_pkt_capture_item_insert",
	  "slot vport tcam_index rule_config cap_point panel_id vqm_vfid vhca_id",
	  diag_dpp_pkt_capture_item_insert },
	{ "diag_dpp_pkt_capture_item_delete", "slot vport tcam_index",
	  diag_dpp_pkt_capture_item_delete },
	{ "diag_dpp_pkt_capture_table_dump", "slot vport", diag_dpp_pkt_capture_table_dump },
	{ "diag_dpp_pkt_capture_table_flush", "slot vport", diag_dpp_pkt_capture_table_flush },
	{ "diag_dpp_pkt_capture_speed_set", "slot vport speed", diag_dpp_pkt_capture_speed_set },
	{ "diag_dpp_pkt_capture_speed_get", "slot vport", diag_dpp_pkt_capture_speed_get },
	{ "diag_dpp_mcode_feature_get", "slot vport index", diag_dpp_mcode_feature_get },
	{ "diag_dpp_pktrx_mcode_glb_cfg_write", "slot vport start_bit_no end_bit_no glb_cfg_data_1",
	  diag_dpp_pktrx_mcode_glb_cfg_write },
	{ "diag_dpp_l2d_psn_cfg_set", "slot vport psn_cfg", diag_dpp_l2d_psn_cfg_set },
	{ "diag_dpp_l2d_psn_cfg_get", "slot vport", diag_dpp_l2d_psn_cfg_get },
	{ "diag_dpp_dtb_dump_test", "slot vport num flag", diag_dpp_dtb_dump_test },
};

#endif
