# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2015 - 2017 Beijing WangXun Technology Co., Ltd.
#
# Makefile for the Netswift 10GbE PCI Express ethernet driver
#

obj-$(CONFIG_TXGBE) += txgbe.o

txgbe-objs := txgbe_main.o txgbe_ethtool.o \
              txgbe_hw.o txgbe_phy.o txgbe_bp.o \
              txgbe_mbx.o txgbe_mtd.o txgbe_param.o txgbe_lib.o txgbe_ptp.o
