# SPDX-License-Identifier: GPL-2.0
# hst2dr makefile
obj-$(CONFIG_SCSI_HST2DR) += hst2dr.o
hst2dr-y +=  hst2dr_base.o     \
		hst2dr_conf.o \
		hst2dr_init.o      \
		hst2dr_transport.o     \
		hst2dr_ctl.o	\
		hst2dr_hal.o			\
		hst2dr_comm.o

