/* SPDX-License-Identifier: GPL-2.0 */
/**
 * Copyright (C), 2020, Linkdata Technologies Co., Ltd.
 *
 * @file: sxe2vf_rx.h
 * @author: Linkdata
 * @date: 2025.02.16
 * @brief:
 * @note:
 */

#ifndef __SXE2VF_RX_H__
#define __SXE2VF_RX_H__

#include <linux/types.h>
#include <linux/kernel.h>

struct sxe2vf_vsi;

#define SXE2VF_RXQ_CTX_DBUFF_SHIFT 7

#define SXE2VF_PAGE_SIZE_8KB 8192

#define SXE2VF_RXBUF_3072 3072
#define SXE2VF_RXBUF_2048 2048
#define SXE2VF_RXBUF_1536 1536
#define SXE2VF_RX_HDR_SIZE 256

#define SXE2VF_RX_HWTAIL_VALUE_MASK (~0x7)

enum {
	SXE2VF_RXQ_BUILD_SKB_ENABLED = 0,
	SXE2VF_RXQ_LRO_ENABLED,
	SXE2VF_RTXQ_VLAN_TAG_LOC_L2TAG1,
	SXE2VF_RXQ_VLAN_TAG_LOC_L2TAG2_2,
	SXE2VF_TXQ_VLAN_TAG_LOC_L2TAG2,
	SXE2VF_RXQ_RXFCS_ENABLED,
};

#if (PAGE_SIZE < 8192)

#define SXE2VF_PAD_RX_LEN_EXCEED_2K                                            \
	((unsigned int)(NET_SKB_PAD + SXE2VF_RXBUF_1536) >                     \
	 SKB_WITH_OVERHEAD(SXE2VF_RXBUF_2048))

static u16 sxe2vf_skb_pad_cal(void)
{
	u16 rx_buf_len;
	u16 value;

	if (SXE2VF_PAD_RX_LEN_EXCEED_2K)
		rx_buf_len = SXE2VF_RXBUF_3072 + SKB_DATA_ALIGN(NET_IP_ALIGN);
	else
		rx_buf_len = SXE2VF_RXBUF_1536;

	rx_buf_len -= NET_IP_ALIGN;

	value = ALIGN(rx_buf_len, PAGE_SIZE / 2);

	value = SKB_WITH_OVERHEAD(value) - rx_buf_len;

	return value;
}

#define SXE2VF_SKB_PAD_VALUE sxe2vf_skb_pad_cal()

#else
#define SXE2VF_PAD_RX_LEN_EXCEED_2K false
#define SXE2VF_SKB_PAD_VALUE (NET_SKB_PAD + NET_IP_ALIGN)
#define SXE2VF_LAST_OFFSET \
	(SKB_WITH_OVERHEAD(PAGE_SIZE) - SXE2VF_RXBUF_2048)
#endif

#define SXE2VF_RX_DMA_ATTR (DMA_ATTR_SKIP_CPU_SYNC | DMA_ATTR_WEAK_ORDERING)

#define SXE2VF_RX_DESC_EUDPE (6)

#define SXE2VF_HBUFF_LEN_MIN (2)

#define SXE2VF_RX_DESC_PKT_LEN_SHIFT (0)

#define SXE2VF_RX_DESC_PKT_LEN_MASK (0x3FFF)

#define SXE2VF_RX_DESC_LROCNT_MASK (0xF)
#define SXE2VF_RX_DESC_LROCNT_SHIFT (0)

#define SXE2VF_RX_DESC_RXDID_MASK (0x7)

#define SXE2VF_RX_DESC_PTYPE_MASK (0x3FF)

#define SXE2VF_RX_DESC_RSS_VLD_MASK (0x1)

#define SXE2VF_RX_DESC_PHY_PORT_MASK (0x3)

#define SXE2VF_RX_DESC_IPSEC_PKT (21)
#define SXE2VF_RX_DESC_IPSEC_ENGINE (22)
#define SXE2VF_RX_DESC_IPSEC_MODE (23)
#define SXE2VF_RX_DESC_IPSEC_STATUS (24)
#define SXE2VF_RX_DESC_IPSEC_STATUS_MASK (0x7)
#define SXE2VF_RX_DESC_IPSEC_STATUS_GET(qw)                                    \
	(((qw) >> SXE2VF_RX_DESC_IPSEC_STATUS) &                               \
	 SXE2VF_RX_DESC_IPSEC_STATUS_MASK)

enum sxe2_rx_desc_status0_err {
	SXE2VF_RX_DESC_STATUS0_DD = 0,
	SXE2VF_RX_DESC_STATUS0_EOP = 1,
	SXE2VF_RX_DESC_STATUS0_L2TAG1_P = 2,
	SXE2VF_RX_DESC_STATUS0_L3L4_P = 3,
	SXE2VF_RX_DESC_STATUS0_CRCP = 4,
	SXE2VF_RX_DESC_STATUS0_SECP = 5,
	SXE2VF_RX_DESC_STATUS0_SECTAG = 6,

	SXE2VF_RX_DESC_ERROR_RXE = 7,
	SXE2VF_RX_DESC_ERROR_PA_ERR = 8,
	SXE2VF_RX_DESC_ERROR_PKT_HBO = 9,
	SXE2VF_RX_DESC_ERROR_IPE = 10,
	SXE2VF_RX_DESC_ERROR_L4E = 11,
	SXE2VF_RX_DESC_ERROR_EIPE = 12,
	SXE2VF_RX_DESC_ERROR_OVERSIZE = 13,
	SXE2VF_RX_DESC_ERROR_SEC_ERR = 14,

};

enum sxe2_rx_desc_status1 {
	SXE2VF_RX_DESC_STATUS1_START = 10,
	SXE2VF_RX_DESC_STATUS1_SECE = 0 + SXE2VF_RX_DESC_STATUS1_START,
	SXE2VF_RX_DESC_STATUS1_EXT_UDP_0 = 1 + SXE2VF_RX_DESC_STATUS1_START,
	SXE2VF_RX_DESC_STATUS1_UMBCAST = 2 + SXE2VF_RX_DESC_STATUS1_START,
	SXE2VF_RX_DESC_STATUS1_FLTSTAT = 4 + SXE2VF_RX_DESC_STATUS1_START,
};

enum sxe2_rx_desc_status2 {
	SXE2VF_RX_DESC_STATUS2_START = 26,
	SXE2VF_RX_DESC_STATUS2_FIM = 0 + SXE2VF_RX_DESC_STATUS2_START,
	SXE2VF_RX_DESC_STATUS2_LPBK = 1 + SXE2VF_RX_DESC_STATUS2_START,
	SXE2VF_RX_DESC_STATUS2_IPV6EXADD = 2 + SXE2VF_RX_DESC_STATUS2_START,
	SXE2VF_RX_DESC_STATUS2_RSS_VLD = 3 + SXE2VF_RX_DESC_STATUS2_START,
	SXE2VF_RX_DESC_STATUS2_ACL_HIT = 4 + SXE2VF_RX_DESC_STATUS2_START,
	SXE2VF_RX_DESC_STATUS2_INT_UDP_0 = 5 + SXE2VF_RX_DESC_STATUS2_START,
};

enum {
	SXE2VF_PTYPE_OUTER_L2 = 0,
	SXE2VF_PTYPE_OUTER_IP = 1,
};

enum {
	SXE2VF_PTYPE_OUTER_NONE = 0,
	SXE2VF_PTYPE_OUTER_IPV4 = 1,
	SXE2VF_PTYPE_OUTER_IPV6 = 2,
};

enum {
	SXE2VF_PTYPE_NOT_FRAG = 0,
	SXE2VF_PTYPE_FRAG = 1,
};

enum {
	SXE2VF_PTYPE_TUNNEL_NONE = 0,
	SXE2VF_PTYPE_TUNNEL_IP_IP = 1,
	SXE2VF_PTYPE_TUNNEL_IP_MAC = 2,
	SXE2VF_PTYPE_TUNNEL_IP_MAC_VLAN = 3,
	SXE2VF_PTYPE_TUNNEL_IP_GTPU = 4,
	SXE2VF_PTYPE_TUNNEL_IP_GRENAT = 5,
	SXE2VF_PTYPE_TUNNEL_IP_GRENAT_MAC = 6,
	SXE2VF_PTYPE_TUNNEL_IP_GRENAT_MAC_VLAN = 7,
};

enum {
	SXE2VF_PTYPE_TUNNEL_END_NONE = 0,
	SXE2VF_PTYPE_TUNNEL_END_IPV4 = 1,
	SXE2VF_PTYPE_TUNNEL_END_IPV6 = 2,
};

enum {
	SXE2VF_PTYPE_INNER_PROT_NONE = 0,
	SXE2VF_PTYPE_INNER_PROT_UDP = 1,
	SXE2VF_PTYPE_INNER_PROT_TCP = 2,
	SXE2VF_PTYPE_INNER_PROT_SCTP = 3,
	SXE2VF_PTYPE_INNER_PROT_ICMP = 4,
	SXE2VF_PTYPE_INNER_PROT_TIMESYNC = 5,
};

enum {
	SXE2VF_PTYPE_PAYLOAD_LAYER_NONE = 0,
	SXE2VF_PTYPE_PAYLOAD_LAYER_PAY2 = 1,
	SXE2VF_PTYPE_PAYLOAD_LAYER_PAY3 = 2,
	SXE2VF_PTYPE_PAYLOAD_LAYER_PAY4 = 3,
};

struct sxe2vf_rx_ptype_info {
	u32 known : 1;
	u32 outer_ip : 1;
	u32 outer_ip_ver : 2;
	u32 outer_frag : 1;
	u32 tunnel_type : 3;
	u32 tunnel_end_prot : 2;
	u32 tunnel_end_frag : 1;
	u32 inner_prot : 4;
	u32 payload_layer : 3;
	u32 hash_layer : 3;
};

#define SXE2VF_PTYPE_UNUSED_ENTRY(PTYPE)                                       \
	[PTYPE] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }

#define SXE2VF_PTYPE(PTYPE, OUTER_IP, OUTER_IP_VER, OUTER_FRAG, T, TE, TEF, I, \
		     PL, HL)                                                   \
	[PTYPE] = {                                                            \
		1,                                                             \
		SXE2VF_PTYPE_OUTER_##OUTER_IP,                                 \
		SXE2VF_PTYPE_OUTER_##OUTER_IP_VER,                             \
		SXE2VF_PTYPE_##OUTER_FRAG,                                     \
		SXE2VF_PTYPE_TUNNEL_##T,                                       \
		SXE2VF_PTYPE_TUNNEL_END_##TE,                                  \
		SXE2VF_PTYPE_##TEF,                                            \
		SXE2VF_PTYPE_INNER_PROT_##I,                                   \
		SXE2VF_PTYPE_PAYLOAD_LAYER_##PL,                               \
		SXE2VF_PTYPE_PAYLOAD_LAYER_##HL,                               \
	}

#define SXE2VF_PTYPE_NOF SXE2VF_PTYPE_NOT_FRAG
#define SXE2VF_PTYPE_FRG SXE2VF_PTYPE_FRAG

static const struct sxe2vf_rx_ptype_info sxe2vf_ptype_table[BIT(10)] = {
	SXE2VF_PTYPE_UNUSED_ENTRY(0),
	SXE2VF_PTYPE(1, L2, NONE, NOF, NONE, NONE, NOF, NONE, PAY2, PAY2),
	SXE2VF_PTYPE(2, L2, NONE, NOF, NONE, NONE, NOF, NONE, PAY2, PAY2),
	SXE2VF_PTYPE_UNUSED_ENTRY(3), SXE2VF_PTYPE_UNUSED_ENTRY(4),
	SXE2VF_PTYPE_UNUSED_ENTRY(5),
	SXE2VF_PTYPE(6, L2, NONE, NOF, NONE, NONE, NOF, NONE, PAY2, PAY2),
	SXE2VF_PTYPE(7, L2, NONE, NOF, NONE, NONE, NOF, NONE, PAY2, PAY2),
	SXE2VF_PTYPE_UNUSED_ENTRY(8), SXE2VF_PTYPE_UNUSED_ENTRY(9),
	SXE2VF_PTYPE(10, L2, NONE, NOF, NONE, NONE, NOF, NONE, PAY2, PAY2),
	SXE2VF_PTYPE(11, L2, NONE, NOF, NONE, NONE, NOF, NONE, PAY2, PAY2),
	SXE2VF_PTYPE_UNUSED_ENTRY(12), SXE2VF_PTYPE_UNUSED_ENTRY(13),
	SXE2VF_PTYPE_UNUSED_ENTRY(14), SXE2VF_PTYPE_UNUSED_ENTRY(15),
	SXE2VF_PTYPE_UNUSED_ENTRY(16), SXE2VF_PTYPE_UNUSED_ENTRY(17),
	SXE2VF_PTYPE_UNUSED_ENTRY(18), SXE2VF_PTYPE_UNUSED_ENTRY(19),
	SXE2VF_PTYPE_UNUSED_ENTRY(20), SXE2VF_PTYPE_UNUSED_ENTRY(21),

	SXE2VF_PTYPE(22, IP, IPV4, FRG, NONE, NONE, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(23, IP, IPV4, NOF, NONE, NONE, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(24, IP, IPV4, NOF, NONE, NONE, NOF, UDP, PAY4, PAY4),
	SXE2VF_PTYPE_UNUSED_ENTRY(25),
	SXE2VF_PTYPE(26, IP, IPV4, NOF, NONE, NONE, NOF, TCP, PAY4, PAY4),
	SXE2VF_PTYPE(27, IP, IPV4, NOF, NONE, NONE, NOF, SCTP, PAY4, PAY4),
	SXE2VF_PTYPE(28, IP, IPV4, NOF, NONE, NONE, NOF, ICMP, PAY4, PAY3),

	SXE2VF_PTYPE(29, IP, IPV4, NOF, IP_IP, IPV4, FRG, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(30, IP, IPV4, NOF, IP_IP, IPV4, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(31, IP, IPV4, NOF, IP_IP, IPV4, NOF, UDP, PAY4, PAY4),
	SXE2VF_PTYPE_UNUSED_ENTRY(32),
	SXE2VF_PTYPE(33, IP, IPV4, NOF, IP_IP, IPV4, NOF, TCP, PAY4, PAY4),
	SXE2VF_PTYPE(34, IP, IPV4, NOF, IP_IP, IPV4, NOF, SCTP, PAY4, PAY4),
	SXE2VF_PTYPE(35, IP, IPV4, NOF, IP_IP, IPV4, NOF, ICMP, PAY4, PAY3),

	SXE2VF_PTYPE(36, IP, IPV4, NOF, IP_IP, IPV6, FRG, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(37, IP, IPV4, NOF, IP_IP, IPV6, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(38, IP, IPV4, NOF, IP_IP, IPV6, NOF, UDP, PAY4, PAY4),
	SXE2VF_PTYPE_UNUSED_ENTRY(39),
	SXE2VF_PTYPE(40, IP, IPV4, NOF, IP_IP, IPV6, NOF, TCP, PAY4, PAY4),
	SXE2VF_PTYPE(41, IP, IPV4, NOF, IP_IP, IPV6, NOF, SCTP, PAY4, PAY4),
	SXE2VF_PTYPE(42, IP, IPV4, NOF, IP_IP, IPV6, NOF, ICMP, PAY4, PAY3),

	SXE2VF_PTYPE(43, IP, IPV4, NOF, IP_GRENAT, NONE, NOF, NONE, PAY3, PAY3),

	SXE2VF_PTYPE(44, IP, IPV4, NOF, IP_GRENAT, IPV4, FRG, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(45, IP, IPV4, NOF, IP_GRENAT, IPV4, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(46, IP, IPV4, NOF, IP_GRENAT, IPV4, NOF, UDP, PAY4, PAY4),
	SXE2VF_PTYPE_UNUSED_ENTRY(47),
	SXE2VF_PTYPE(48, IP, IPV4, NOF, IP_GRENAT, IPV4, NOF, TCP, PAY4, PAY4),
	SXE2VF_PTYPE(49, IP, IPV4, NOF, IP_GRENAT, IPV4, NOF, SCTP, PAY4, PAY4),
	SXE2VF_PTYPE(50, IP, IPV4, NOF, IP_GRENAT, IPV4, NOF, ICMP, PAY4, PAY3),

	SXE2VF_PTYPE(51, IP, IPV4, NOF, IP_GRENAT, IPV6, FRG, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(52, IP, IPV4, NOF, IP_GRENAT, IPV6, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(53, IP, IPV4, NOF, IP_GRENAT, IPV6, NOF, UDP, PAY4, PAY4),
	SXE2VF_PTYPE_UNUSED_ENTRY(54),
	SXE2VF_PTYPE(55, IP, IPV4, NOF, IP_GRENAT, IPV6, NOF, TCP, PAY4, PAY4),
	SXE2VF_PTYPE(56, IP, IPV4, NOF, IP_GRENAT, IPV6, NOF, SCTP, PAY4, PAY4),
	SXE2VF_PTYPE(57, IP, IPV4, NOF, IP_GRENAT, IPV6, NOF, ICMP, PAY4, PAY3),

	SXE2VF_PTYPE(58, IP, IPV4, NOF, IP_GRENAT_MAC, NONE, NOF, NONE, PAY3,
		     PAY3),

	SXE2VF_PTYPE(59, IP, IPV4, NOF, IP_GRENAT_MAC, IPV4, FRG, NONE, PAY3,
		     PAY3),
	SXE2VF_PTYPE(60, IP, IPV4, NOF, IP_GRENAT_MAC, IPV4, NOF, NONE, PAY3,
		     PAY3),
	SXE2VF_PTYPE(61, IP, IPV4, NOF, IP_GRENAT_MAC, IPV4, NOF, UDP, PAY4,
		     PAY4),
	SXE2VF_PTYPE_UNUSED_ENTRY(62),
	SXE2VF_PTYPE(63, IP, IPV4, NOF, IP_GRENAT_MAC, IPV4, NOF, TCP, PAY4,
		     PAY4),
	SXE2VF_PTYPE(64, IP, IPV4, NOF, IP_GRENAT_MAC, IPV4, NOF, SCTP, PAY4,
		     PAY4),
	SXE2VF_PTYPE(65, IP, IPV4, NOF, IP_GRENAT_MAC, IPV4, NOF, ICMP, PAY4,
		     PAY3),

	SXE2VF_PTYPE(66, IP, IPV4, NOF, IP_GRENAT_MAC, IPV6, FRG, NONE, PAY3,
		     PAY3),
	SXE2VF_PTYPE(67, IP, IPV4, NOF, IP_GRENAT_MAC, IPV6, NOF, NONE, PAY3,
		     PAY3),
	SXE2VF_PTYPE(68, IP, IPV4, NOF, IP_GRENAT_MAC, IPV6, NOF, UDP, PAY4,
		     PAY4),
	SXE2VF_PTYPE_UNUSED_ENTRY(69),
	SXE2VF_PTYPE(70, IP, IPV4, NOF, IP_GRENAT_MAC, IPV6, NOF, TCP, PAY4,
		     PAY4),
	SXE2VF_PTYPE(71, IP, IPV4, NOF, IP_GRENAT_MAC, IPV6, NOF, SCTP, PAY4,
		     PAY4),
	SXE2VF_PTYPE(72, IP, IPV4, NOF, IP_GRENAT_MAC, IPV6, NOF, ICMP, PAY4,
		     PAY3),

	SXE2VF_PTYPE(73, IP, IPV4, NOF, IP_GRENAT_MAC_VLAN, NONE, NOF, NONE,
		     PAY3, PAY3),

	SXE2VF_PTYPE(74, IP, IPV4, NOF, IP_GRENAT_MAC_VLAN, IPV4, FRG, NONE,
		     PAY3, PAY3),
	SXE2VF_PTYPE(75, IP, IPV4, NOF, IP_GRENAT_MAC_VLAN, IPV4, NOF, NONE,
		     PAY3, PAY3),
	SXE2VF_PTYPE(76, IP, IPV4, NOF, IP_GRENAT_MAC_VLAN, IPV4, NOF, UDP,
		     PAY4, PAY4),
	SXE2VF_PTYPE_UNUSED_ENTRY(77),
	SXE2VF_PTYPE(78, IP, IPV4, NOF, IP_GRENAT_MAC_VLAN, IPV4, NOF, TCP,
		     PAY4, PAY4),
	SXE2VF_PTYPE(79, IP, IPV4, NOF, IP_GRENAT_MAC_VLAN, IPV4, NOF, SCTP,
		     PAY4, PAY4),
	SXE2VF_PTYPE(80, IP, IPV4, NOF, IP_GRENAT_MAC_VLAN, IPV4, NOF, ICMP,
		     PAY4, PAY3),

	SXE2VF_PTYPE(81, IP, IPV4, NOF, IP_GRENAT_MAC_VLAN, IPV6, FRG, NONE,
		     PAY3, PAY3),
	SXE2VF_PTYPE(82, IP, IPV4, NOF, IP_GRENAT_MAC_VLAN, IPV6, NOF, NONE,
		     PAY3, PAY3),
	SXE2VF_PTYPE(83, IP, IPV4, NOF, IP_GRENAT_MAC_VLAN, IPV6, NOF, UDP,
		     PAY4, PAY4),
	SXE2VF_PTYPE_UNUSED_ENTRY(84),
	SXE2VF_PTYPE(85, IP, IPV4, NOF, IP_GRENAT_MAC_VLAN, IPV6, NOF, TCP,
		     PAY4, PAY4),
	SXE2VF_PTYPE(86, IP, IPV4, NOF, IP_GRENAT_MAC_VLAN, IPV6, NOF, SCTP,
		     PAY4, PAY4),
	SXE2VF_PTYPE(87, IP, IPV4, NOF, IP_GRENAT_MAC_VLAN, IPV6, NOF, ICMP,
		     PAY4, PAY3),

	SXE2VF_PTYPE(88, IP, IPV6, FRG, NONE, NONE, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(89, IP, IPV6, NOF, NONE, NONE, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(90, IP, IPV6, NOF, NONE, NONE, NOF, UDP, PAY4, PAY4),
	SXE2VF_PTYPE_UNUSED_ENTRY(91),
	SXE2VF_PTYPE(92, IP, IPV6, NOF, NONE, NONE, NOF, TCP, PAY4, PAY4),
	SXE2VF_PTYPE(93, IP, IPV6, NOF, NONE, NONE, NOF, SCTP, PAY4, PAY4),
	SXE2VF_PTYPE(94, IP, IPV6, NOF, NONE, NONE, NOF, ICMP, PAY4, PAY3),

	SXE2VF_PTYPE(95, IP, IPV6, NOF, IP_IP, IPV4, FRG, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(96, IP, IPV6, NOF, IP_IP, IPV4, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(97, IP, IPV6, NOF, IP_IP, IPV4, NOF, UDP, PAY4, PAY4),
	SXE2VF_PTYPE_UNUSED_ENTRY(98),
	SXE2VF_PTYPE(99, IP, IPV6, NOF, IP_IP, IPV4, NOF, TCP, PAY4, PAY4),
	SXE2VF_PTYPE(100, IP, IPV6, NOF, IP_IP, IPV4, NOF, SCTP, PAY4, PAY4),
	SXE2VF_PTYPE(101, IP, IPV6, NOF, IP_IP, IPV4, NOF, ICMP, PAY4, PAY3),

	SXE2VF_PTYPE(102, IP, IPV6, NOF, IP_IP, IPV6, FRG, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(103, IP, IPV6, NOF, IP_IP, IPV6, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(104, IP, IPV6, NOF, IP_IP, IPV6, NOF, UDP, PAY4, PAY4),
	SXE2VF_PTYPE_UNUSED_ENTRY(105),
	SXE2VF_PTYPE(106, IP, IPV6, NOF, IP_IP, IPV6, NOF, TCP, PAY4, PAY4),
	SXE2VF_PTYPE(107, IP, IPV6, NOF, IP_IP, IPV6, NOF, SCTP, PAY4, PAY4),
	SXE2VF_PTYPE(108, IP, IPV6, NOF, IP_IP, IPV6, NOF, ICMP, PAY4, PAY3),

	SXE2VF_PTYPE(109, IP, IPV6, NOF, IP_GRENAT, NONE, NOF, NONE, PAY3,
		     PAY3),

	SXE2VF_PTYPE(110, IP, IPV6, NOF, IP_GRENAT, IPV4, FRG, NONE, PAY3,
		     PAY3),
	SXE2VF_PTYPE(111, IP, IPV6, NOF, IP_GRENAT, IPV4, NOF, NONE, PAY3,
		     PAY3),
	SXE2VF_PTYPE(112, IP, IPV6, NOF, IP_GRENAT, IPV4, NOF, UDP, PAY4, PAY4),
	SXE2VF_PTYPE_UNUSED_ENTRY(113),
	SXE2VF_PTYPE(114, IP, IPV6, NOF, IP_GRENAT, IPV4, NOF, TCP, PAY4, PAY4),
	SXE2VF_PTYPE(115, IP, IPV6, NOF, IP_GRENAT, IPV4, NOF, SCTP, PAY4,
		     PAY4),
	SXE2VF_PTYPE(116, IP, IPV6, NOF, IP_GRENAT, IPV4, NOF, ICMP, PAY4,
		     PAY3),

	SXE2VF_PTYPE(117, IP, IPV6, NOF, IP_GRENAT, IPV6, FRG, NONE, PAY3,
		     PAY3),
	SXE2VF_PTYPE(118, IP, IPV6, NOF, IP_GRENAT, IPV6, NOF, NONE, PAY3,
		     PAY3),
	SXE2VF_PTYPE(119, IP, IPV6, NOF, IP_GRENAT, IPV6, NOF, UDP, PAY4, PAY4),
	SXE2VF_PTYPE_UNUSED_ENTRY(120),
	SXE2VF_PTYPE(121, IP, IPV6, NOF, IP_GRENAT, IPV6, NOF, TCP, PAY4, PAY4),
	SXE2VF_PTYPE(122, IP, IPV6, NOF, IP_GRENAT, IPV6, NOF, SCTP, PAY4,
		     PAY4),
	SXE2VF_PTYPE(123, IP, IPV6, NOF, IP_GRENAT, IPV6, NOF, ICMP, PAY4,
		     PAY3),

	SXE2VF_PTYPE(124, IP, IPV6, NOF, IP_GRENAT_MAC, NONE, NOF, NONE, PAY3,
		     PAY3),

	SXE2VF_PTYPE(125, IP, IPV6, NOF, IP_GRENAT_MAC, IPV4, FRG, NONE, PAY3,
		     PAY3),
	SXE2VF_PTYPE(126, IP, IPV6, NOF, IP_GRENAT_MAC, IPV4, NOF, NONE, PAY3,
		     PAY3),
	SXE2VF_PTYPE(127, IP, IPV6, NOF, IP_GRENAT_MAC, IPV4, NOF, UDP, PAY4,
		     PAY4),
	SXE2VF_PTYPE_UNUSED_ENTRY(128),
	SXE2VF_PTYPE(129, IP, IPV6, NOF, IP_GRENAT_MAC, IPV4, NOF, TCP, PAY4,
		     PAY4),
	SXE2VF_PTYPE(130, IP, IPV6, NOF, IP_GRENAT_MAC, IPV4, NOF, SCTP, PAY4,
		     PAY4),
	SXE2VF_PTYPE(131, IP, IPV6, NOF, IP_GRENAT_MAC, IPV4, NOF, ICMP, PAY4,
		     PAY3),

	SXE2VF_PTYPE(132, IP, IPV6, NOF, IP_GRENAT_MAC, IPV6, FRG, NONE, PAY3,
		     PAY3),
	SXE2VF_PTYPE(133, IP, IPV6, NOF, IP_GRENAT_MAC, IPV6, NOF, NONE, PAY3,
		     PAY3),
	SXE2VF_PTYPE(134, IP, IPV6, NOF, IP_GRENAT_MAC, IPV6, NOF, UDP, PAY4,
		     PAY4),
	SXE2VF_PTYPE_UNUSED_ENTRY(135),
	SXE2VF_PTYPE(136, IP, IPV6, NOF, IP_GRENAT_MAC, IPV6, NOF, TCP, PAY4,
		     PAY4),
	SXE2VF_PTYPE(137, IP, IPV6, NOF, IP_GRENAT_MAC, IPV6, NOF, SCTP, PAY4,
		     PAY4),
	SXE2VF_PTYPE(138, IP, IPV6, NOF, IP_GRENAT_MAC, IPV6, NOF, ICMP, PAY4,
		     PAY3),

	SXE2VF_PTYPE(139, IP, IPV6, NOF, IP_GRENAT_MAC_VLAN, NONE, NOF, NONE,
		     PAY3, PAY3),

	SXE2VF_PTYPE(140, IP, IPV6, NOF, IP_GRENAT_MAC_VLAN, IPV4, FRG, NONE,
		     PAY3, PAY3),
	SXE2VF_PTYPE(141, IP, IPV6, NOF, IP_GRENAT_MAC_VLAN, IPV4, NOF, NONE,
		     PAY3, PAY3),
	SXE2VF_PTYPE(142, IP, IPV6, NOF, IP_GRENAT_MAC_VLAN, IPV4, NOF, UDP,
		     PAY4, PAY4),
	SXE2VF_PTYPE_UNUSED_ENTRY(143),
	SXE2VF_PTYPE(144, IP, IPV6, NOF, IP_GRENAT_MAC_VLAN, IPV4, NOF, TCP,
		     PAY4, PAY4),
	SXE2VF_PTYPE(145, IP, IPV6, NOF, IP_GRENAT_MAC_VLAN, IPV4, NOF, SCTP,
		     PAY4, PAY4),
	SXE2VF_PTYPE(146, IP, IPV6, NOF, IP_GRENAT_MAC_VLAN, IPV4, NOF, ICMP,
		     PAY4, PAY3),

	SXE2VF_PTYPE(147, IP, IPV6, NOF, IP_GRENAT_MAC_VLAN, IPV6, FRG, NONE,
		     PAY3, PAY3),
	SXE2VF_PTYPE(148, IP, IPV6, NOF, IP_GRENAT_MAC_VLAN, IPV6, NOF, NONE,
		     PAY3, PAY3),
	SXE2VF_PTYPE(149, IP, IPV6, NOF, IP_GRENAT_MAC_VLAN, IPV6, NOF, UDP,
		     PAY4, PAY4),
	SXE2VF_PTYPE_UNUSED_ENTRY(150),
	SXE2VF_PTYPE(151, IP, IPV6, NOF, IP_GRENAT_MAC_VLAN, IPV6, NOF, TCP,
		     PAY4, PAY4),
	SXE2VF_PTYPE(152, IP, IPV6, NOF, IP_GRENAT_MAC_VLAN, IPV6, NOF, SCTP,
		     PAY4, PAY4),
	SXE2VF_PTYPE(153, IP, IPV6, NOF, IP_GRENAT_MAC_VLAN, IPV6, NOF, ICMP,
		     PAY4, PAY3),
	SXE2VF_PTYPE_UNUSED_ENTRY(154), SXE2VF_PTYPE_UNUSED_ENTRY(155),
	SXE2VF_PTYPE_UNUSED_ENTRY(156), SXE2VF_PTYPE_UNUSED_ENTRY(157),
	SXE2VF_PTYPE_UNUSED_ENTRY(158), SXE2VF_PTYPE_UNUSED_ENTRY(159),

	SXE2VF_PTYPE(160, IP, IPV4, NOF, NONE, NONE, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(161, IP, IPV6, NOF, NONE, NONE, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(162, IP, IPV4, NOF, NONE, NONE, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(163, IP, IPV6, NOF, NONE, NONE, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(164, IP, IPV4, NOF, NONE, NONE, NOF, NONE, PAY4, PAY4),
	SXE2VF_PTYPE(165, IP, IPV6, NOF, NONE, NONE, NOF, NONE, PAY4, PAY4),
	SXE2VF_PTYPE(166, IP, IPV4, NOF, NONE, NONE, NOF, NONE, PAY4, PAY4),
	SXE2VF_PTYPE(167, IP, IPV6, NOF, NONE, NONE, NOF, NONE, PAY4, PAY4),

	[168 ... 254] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },

	[255] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },

	[256 ... 271] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },

	SXE2VF_PTYPE(272, IP, IPV4, NOF, NONE, NONE, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(273, IP, IPV4, NOF, NONE, NONE, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(274, IP, IPV6, NOF, NONE, NONE, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(275, IP, IPV6, NOF, NONE, NONE, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(276, L2, NONE, NOF, NONE, NONE, NOF, NONE, PAY2, PAY2),
	SXE2VF_PTYPE_UNUSED_ENTRY(277),
	SXE2VF_PTYPE(278, L2, NONE, NOF, NONE, NONE, NOF, NONE, PAY2, PAY2),

	[279 ... 326] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },

	SXE2VF_PTYPE(327, IP, IPV4, NOF, NONE, NONE, NOF, NONE, PAY4, PAY4),
	SXE2VF_PTYPE(328, IP, IPV6, NOF, NONE, NONE, NOF, NONE, PAY4, PAY4),
	SXE2VF_PTYPE(329, IP, IPV4, NOF, IP_GTPU, NONE, NOF, NONE, PAY4, PAY4),
	SXE2VF_PTYPE(330, IP, IPV6, NOF, IP_GTPU, NONE, NOF, NONE, PAY4, PAY4),

	SXE2VF_PTYPE(331, IP, IPV4, NOF, IP_GTPU, IPV4, FRG, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(332, IP, IPV4, NOF, IP_GTPU, IPV4, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(333, IP, IPV4, NOF, IP_GTPU, IPV4, NOF, NONE, PAY4, PAY4),
	SXE2VF_PTYPE(334, IP, IPV4, NOF, IP_GTPU, IPV4, NOF, NONE, PAY4, PAY4),
	SXE2VF_PTYPE(335, IP, IPV4, NOF, IP_GTPU, IPV4, NOF, NONE, PAY4, PAY4),

	SXE2VF_PTYPE(336, IP, IPV6, NOF, IP_GTPU, IPV4, FRG, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(337, IP, IPV6, NOF, IP_GTPU, IPV4, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(338, IP, IPV6, NOF, IP_GTPU, IPV4, NOF, NONE, PAY4, PAY4),
	SXE2VF_PTYPE(339, IP, IPV6, NOF, IP_GTPU, IPV4, NOF, NONE, PAY4, PAY4),
	SXE2VF_PTYPE(340, IP, IPV6, NOF, IP_GTPU, IPV4, NOF, NONE, PAY4, PAY4),

	SXE2VF_PTYPE(341, IP, IPV4, NOF, IP_GTPU, IPV6, FRG, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(342, IP, IPV4, NOF, IP_GTPU, IPV6, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(343, IP, IPV4, NOF, IP_GTPU, IPV6, NOF, NONE, PAY4, PAY4),
	SXE2VF_PTYPE(344, IP, IPV4, NOF, IP_GTPU, IPV6, NOF, NONE, PAY4, PAY4),
	SXE2VF_PTYPE(345, IP, IPV4, NOF, IP_GTPU, IPV6, NOF, NONE, PAY4, PAY4),

	SXE2VF_PTYPE(346, IP, IPV6, NOF, IP_GTPU, IPV6, FRG, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(347, IP, IPV6, NOF, IP_GTPU, IPV6, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(348, IP, IPV6, NOF, IP_GTPU, IPV6, NOF, NONE, PAY4, PAY4),
	SXE2VF_PTYPE(349, IP, IPV6, NOF, IP_GTPU, IPV6, NOF, NONE, PAY4, PAY4),
	SXE2VF_PTYPE(350, IP, IPV6, NOF, IP_GTPU, IPV6, NOF, NONE, PAY4, PAY4),

	SXE2VF_PTYPE(351, IP, IPV4, NOF, NONE, NONE, NOF, NONE, PAY4, PAY4),
	SXE2VF_PTYPE(352, IP, IPV4, NOF, NONE, NONE, NOF, NONE, PAY4, PAY4),
	SXE2VF_PTYPE(353, IP, IPV6, NOF, NONE, NONE, NOF, NONE, PAY4, PAY4),
	SXE2VF_PTYPE(354, IP, IPV6, NOF, NONE, NONE, NOF, NONE, PAY4, PAY4),

	[355 ... 359] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },

	SXE2VF_PTYPE(360, IP, IPV4, NOF, NONE, NONE, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(361, IP, IPV6, NOF, NONE, NONE, NOF, NONE, PAY3, PAY3),

	[362 ... 370] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },

	SXE2VF_PTYPE(371, L2, NONE, NOF, NONE, NONE, NOF, NONE, PAY2, PAY2),
	[372 ... 380] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
	SXE2VF_PTYPE(381, IP, IPV4, NOF, NONE, NONE, NOF, UDP, PAY4, PAY4),
	[382 ... 390] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
	SXE2VF_PTYPE(391, IP, IPV6, NOF, NONE, NONE, NOF, UDP, PAY4, PAY4),

	[392 ... 395] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },

	SXE2VF_PTYPE(396, IP, IPV4, NOF, NONE, IPV4, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(397, IP, IPV6, NOF, NONE, IPV4, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(398, IP, IPV4, NOF, NONE, IPV4, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(399, IP, IPV6, NOF, NONE, IPV4, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(400, IP, IPV4, NOF, NONE, IPV4, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(401, IP, IPV6, NOF, NONE, IPV4, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(402, IP, IPV4, NOF, NONE, IPV6, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(403, IP, IPV6, NOF, NONE, IPV6, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(404, IP, IPV4, NOF, NONE, IPV6, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(405, IP, IPV6, NOF, NONE, IPV6, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(406, IP, IPV4, NOF, NONE, IPV6, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(407, IP, IPV6, NOF, NONE, IPV6, NOF, NONE, PAY3, PAY3),

	SXE2VF_PTYPE(408, IP, IPV4, NOF, NONE, IPV4, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(409, IP, IPV6, NOF, NONE, IPV4, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(410, IP, IPV4, NOF, NONE, IPV6, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(411, IP, IPV6, NOF, NONE, IPV6, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(412, IP, IPV4, NOF, NONE, IPV4, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(413, IP, IPV6, NOF, NONE, IPV4, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(414, IP, IPV4, NOF, NONE, IPV6, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(415, IP, IPV6, NOF, NONE, IPV6, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(416, IP, IPV4, NOF, NONE, IPV4, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(417, IP, IPV6, NOF, NONE, IPV4, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(418, IP, IPV4, NOF, NONE, IPV6, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(419, IP, IPV6, NOF, NONE, IPV6, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(420, IP, IPV4, NOF, NONE, IPV4, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(421, IP, IPV6, NOF, NONE, IPV4, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(422, IP, IPV4, NOF, NONE, IPV6, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(423, IP, IPV6, NOF, NONE, IPV6, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(424, IP, IPV4, NOF, NONE, IPV4, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(425, IP, IPV6, NOF, NONE, IPV4, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(426, IP, IPV4, NOF, NONE, IPV6, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(427, IP, IPV6, NOF, NONE, IPV6, NOF, NONE, PAY3, PAY3),

	[428 ... 768] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },

	SXE2VF_PTYPE(769, L2, NONE, NOF, NONE, NONE, NOF, NONE, PAY2, PAY2),
	SXE2VF_PTYPE(770, L2, NONE, NOF, NONE, NONE, NOF, NONE, PAY2, PAY2),
	SXE2VF_PTYPE(771, L2, NONE, NOF, NONE, NONE, NOF, NONE, PAY2, PAY2),
	SXE2VF_PTYPE_UNUSED_ENTRY(772),
	SXE2VF_PTYPE(773, L2, NONE, NOF, NONE, NONE, NOF, NONE, PAY2, PAY2),
	SXE2VF_PTYPE_UNUSED_ENTRY(774), SXE2VF_PTYPE_UNUSED_ENTRY(775),

	SXE2VF_PTYPE(776, IP, IPV4, NOF, NONE, NONE, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(777, IP, IPV4, NOF, NONE, NONE, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(778, IP, IPV4, NOF, NONE, NONE, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(779, IP, IPV4, NOF, NONE, NONE, NOF, NONE, PAY4, PAY4),
	SXE2VF_PTYPE(780, IP, IPV4, NOF, NONE, NONE, NOF, NONE, PAY4, PAY4),
	SXE2VF_PTYPE(781, IP, IPV4, NOF, NONE, NONE, NOF, NONE, PAY4, PAY4),
	SXE2VF_PTYPE_UNUSED_ENTRY(782), SXE2VF_PTYPE_UNUSED_ENTRY(783),

	SXE2VF_PTYPE(784, IP, IPV6, NOF, NONE, NONE, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(785, IP, IPV6, NOF, NONE, NONE, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(786, IP, IPV6, NOF, NONE, NONE, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(787, IP, IPV6, NOF, NONE, NONE, NOF, NONE, PAY4, PAY4),
	SXE2VF_PTYPE(788, IP, IPV6, NOF, NONE, NONE, NOF, NONE, PAY4, PAY4),
	SXE2VF_PTYPE(789, IP, IPV6, NOF, NONE, NONE, NOF, NONE, PAY4, PAY4),
	SXE2VF_PTYPE_UNUSED_ENTRY(790), SXE2VF_PTYPE_UNUSED_ENTRY(791),

	SXE2VF_PTYPE(792, IP, IPV4, NOF, NONE, NONE, NOF, TCP, PAY4, PAY4),
	SXE2VF_PTYPE(793, IP, IPV4, NOF, NONE, NONE, NOF, TCP, PAY4, PAY4),
	SXE2VF_PTYPE(794, IP, IPV4, NOF, NONE, NONE, NOF, UDP, PAY4, PAY4),
	SXE2VF_PTYPE(795, IP, IPV4, NOF, NONE, NONE, NOF, UDP, PAY4, PAY4),
	SXE2VF_PTYPE(796, IP, IPV4, NOF, NONE, NONE, NOF, UDP, PAY4, PAY4),
	SXE2VF_PTYPE(797, IP, IPV4, NOF, NONE, NONE, NOF, UDP, PAY4, PAY4),
	SXE2VF_PTYPE(798, IP, IPV4, NOF, NONE, NONE, NOF, UDP, PAY4, PAY4),
	SXE2VF_PTYPE(799, IP, IPV4, NOF, NONE, NONE, NOF, UDP, PAY4, PAY4),
	SXE2VF_PTYPE(800, IP, IPV4, NOF, NONE, NONE, NOF, UDP, PAY4, PAY4),
	SXE2VF_PTYPE(801, IP, IPV4, NOF, NONE, NONE, NOF, UDP, PAY4, PAY4),
	SXE2VF_PTYPE_UNUSED_ENTRY(802), SXE2VF_PTYPE_UNUSED_ENTRY(803),
	SXE2VF_PTYPE_UNUSED_ENTRY(804), SXE2VF_PTYPE_UNUSED_ENTRY(805),
	SXE2VF_PTYPE_UNUSED_ENTRY(806), SXE2VF_PTYPE_UNUSED_ENTRY(807),

	SXE2VF_PTYPE(808, IP, IPV6, NOF, NONE, NONE, NOF, TCP, PAY4, PAY4),
	SXE2VF_PTYPE(809, IP, IPV6, NOF, NONE, NONE, NOF, TCP, PAY4, PAY4),
	SXE2VF_PTYPE(810, IP, IPV6, NOF, NONE, NONE, NOF, UDP, PAY4, PAY4),
	SXE2VF_PTYPE(811, IP, IPV6, NOF, NONE, NONE, NOF, UDP, PAY4, PAY4),
	SXE2VF_PTYPE(812, IP, IPV6, NOF, NONE, NONE, NOF, UDP, PAY4, PAY4),
	SXE2VF_PTYPE(813, IP, IPV6, NOF, NONE, NONE, NOF, UDP, PAY4, PAY4),
	SXE2VF_PTYPE(814, IP, IPV6, NOF, NONE, NONE, NOF, UDP, PAY4, PAY4),
	SXE2VF_PTYPE(815, IP, IPV6, NOF, NONE, NONE, NOF, UDP, PAY4, PAY4),
	SXE2VF_PTYPE(816, IP, IPV6, NOF, NONE, NONE, NOF, UDP, PAY4, PAY4),
	SXE2VF_PTYPE(817, IP, IPV6, NOF, NONE, NONE, NOF, UDP, PAY4, PAY4),
	SXE2VF_PTYPE_UNUSED_ENTRY(818), SXE2VF_PTYPE_UNUSED_ENTRY(819),

	SXE2VF_PTYPE(820, IP, IPV6, NOF, IP_MAC, NONE, NOF, NONE, PAY3, PAY3),

	SXE2VF_PTYPE(821, IP, IPV6, NOF, IP_MAC, IPV4, FRG, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(822, IP, IPV6, NOF, IP_MAC, IPV4, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(823, IP, IPV6, NOF, IP_MAC, IPV4, NOF, UDP, PAY4, PAY4),
	SXE2VF_PTYPE(824, IP, IPV6, NOF, IP_MAC, IPV4, NOF, TCP, PAY4, PAY4),
	SXE2VF_PTYPE(825, IP, IPV6, NOF, IP_MAC, IPV4, NOF, SCTP, PAY4, PAY4),
	SXE2VF_PTYPE(826, IP, IPV6, NOF, IP_MAC, IPV4, NOF, ICMP, PAY4, PAY3),

	SXE2VF_PTYPE(827, IP, IPV6, NOF, IP_MAC, IPV6, FRG, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(828, IP, IPV6, NOF, IP_MAC, IPV6, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(829, IP, IPV6, NOF, IP_MAC, IPV6, NOF, UDP, PAY4, PAY4),
	SXE2VF_PTYPE(830, IP, IPV6, NOF, IP_MAC, IPV6, NOF, TCP, PAY4, PAY4),
	SXE2VF_PTYPE(831, IP, IPV6, NOF, IP_MAC, IPV6, NOF, SCTP, PAY4, PAY4),
	SXE2VF_PTYPE(832, IP, IPV6, NOF, IP_MAC, IPV6, NOF, ICMP, PAY4, PAY3),

	SXE2VF_PTYPE(832, IP, IPV6, NOF, IP_MAC_VLAN, NONE, NOF, NONE, PAY3,
		     PAY3),

	SXE2VF_PTYPE(836, IP, IPV6, NOF, IP_MAC_VLAN, IPV4, FRG, NONE, PAY3,
		     PAY3),
	SXE2VF_PTYPE(837, IP, IPV6, NOF, IP_MAC_VLAN, IPV4, NOF, NONE, PAY3,
		     PAY3),
	SXE2VF_PTYPE(838, IP, IPV6, NOF, IP_MAC_VLAN, IPV4, NOF, UDP, PAY4,
		     PAY4),
	SXE2VF_PTYPE(839, IP, IPV6, NOF, IP_MAC_VLAN, IPV4, NOF, TCP, PAY4,
		     PAY4),
	SXE2VF_PTYPE(840, IP, IPV6, NOF, IP_MAC_VLAN, IPV4, NOF, SCTP, PAY4,
		     PAY4),
	SXE2VF_PTYPE(841, IP, IPV6, NOF, IP_MAC_VLAN, IPV4, NOF, ICMP, PAY4,
		     PAY3),

	SXE2VF_PTYPE(842, IP, IPV6, NOF, IP_MAC_VLAN, IPV6, FRG, NONE, PAY3,
		     PAY3),
	SXE2VF_PTYPE(843, IP, IPV6, NOF, IP_MAC_VLAN, IPV6, NOF, NONE, PAY3,
		     PAY3),
	SXE2VF_PTYPE(844, IP, IPV6, NOF, IP_MAC_VLAN, IPV6, NOF, UDP, PAY4,
		     PAY4),
	SXE2VF_PTYPE(845, IP, IPV6, NOF, IP_MAC_VLAN, IPV6, NOF, TCP, PAY4,
		     PAY4),
	SXE2VF_PTYPE(846, IP, IPV6, NOF, IP_MAC_VLAN, IPV6, NOF, SCTP, PAY4,
		     PAY4),
	SXE2VF_PTYPE(847, IP, IPV6, NOF, IP_MAC_VLAN, IPV6, NOF, ICMP, PAY4,
		     PAY3),

	[848 ... 867] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 },

	SXE2VF_PTYPE(878, IP, IPV6, NOF, IP_GRENAT, NONE, NOF, NONE, PAY4, PAY4),

	SXE2VF_PTYPE(877, IP, IPV6, NOF, IP_GRENAT, IPV4, FRG, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(876, IP, IPV6, NOF, IP_GRENAT, IPV4, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(879, IP, IPV6, NOF, IP_GRENAT, IPV4, NOF, UDP,  PAY4, PAY4),
	SXE2VF_PTYPE(880, IP, IPV6, NOF, IP_GRENAT, IPV4, NOF, TCP,  PAY4, PAY4),
	SXE2VF_PTYPE(875, IP, IPV6, NOF, IP_GRENAT, IPV4, NOF, SCTP, PAY4, PAY4),
	SXE2VF_PTYPE(874, IP, IPV6, NOF, IP_GRENAT, IPV4, NOF, ICMP, PAY4, PAY3),

	SXE2VF_PTYPE(871, IP, IPV6, NOF, IP_GRENAT, IPV6, FRG, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(870, IP, IPV6, NOF, IP_GRENAT, IPV6, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(872, IP, IPV6, NOF, IP_GRENAT, IPV6, NOF, UDP,  PAY4, PAY4),
	SXE2VF_PTYPE(873, IP, IPV6, NOF, IP_GRENAT, IPV6, NOF, TCP,  PAY4, PAY4),
	SXE2VF_PTYPE(869, IP, IPV6, NOF, IP_GRENAT, IPV6, NOF, SCTP, PAY4, PAY4),
	SXE2VF_PTYPE(868, IP, IPV6, NOF, IP_GRENAT, IPV6, NOF, ICMP, PAY4, PAY3),

	SXE2VF_PTYPE(891, IP, IPV4, NOF, IP_GRENAT, NONE, NOF, NONE, PAY4, PAY4),

	SXE2VF_PTYPE(890, IP, IPV4, NOF, IP_GRENAT, IPV4, FRG, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(889, IP, IPV4, NOF, IP_GRENAT, IPV4, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(892, IP, IPV4, NOF, IP_GRENAT, IPV4, NOF, UDP,  PAY4, PAY4),
	SXE2VF_PTYPE(893, IP, IPV4, NOF, IP_GRENAT, IPV4, NOF, TCP,  PAY4, PAY4),
	SXE2VF_PTYPE(888, IP, IPV4, NOF, IP_GRENAT, IPV4, NOF, SCTP, PAY4, PAY4),
	SXE2VF_PTYPE(887, IP, IPV4, NOF, IP_GRENAT, IPV4, NOF, ICMP, PAY4, PAY3),

	SXE2VF_PTYPE(884, IP, IPV4, NOF, IP_GRENAT, IPV6, FRG, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(883, IP, IPV4, NOF, IP_GRENAT, IPV6, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(885, IP, IPV4, NOF, IP_GRENAT, IPV6, NOF, UDP,  PAY4, PAY4),
	SXE2VF_PTYPE(886, IP, IPV4, NOF, IP_GRENAT, IPV6, NOF, TCP,  PAY4, PAY4),
	SXE2VF_PTYPE(882, IP, IPV4, NOF, IP_GRENAT, IPV6, NOF, SCTP, PAY4, PAY4),
	SXE2VF_PTYPE(881, IP, IPV4, NOF, IP_GRENAT, IPV6, NOF, ICMP, PAY4, PAY3),

	SXE2VF_PTYPE(904, IP, IPV6, NOF, IP_GRENAT, NONE, NOF, NONE, PAY4, PAY4),

	SXE2VF_PTYPE(903, IP, IPV6, NOF, IP_GRENAT, IPV4, FRG, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(902, IP, IPV6, NOF, IP_GRENAT, IPV4, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(905, IP, IPV6, NOF, IP_GRENAT, IPV4, NOF, UDP,  PAY4, PAY4),
	SXE2VF_PTYPE(906, IP, IPV6, NOF, IP_GRENAT, IPV4, NOF, TCP,  PAY4, PAY4),
	SXE2VF_PTYPE(901, IP, IPV6, NOF, IP_GRENAT, IPV4, NOF, SCTP, PAY4, PAY4),
	SXE2VF_PTYPE(900, IP, IPV6, NOF, IP_GRENAT, IPV4, NOF, ICMP, PAY4, PAY3),

	SXE2VF_PTYPE(897, IP, IPV6, NOF, IP_GRENAT, IPV6, FRG, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(896, IP, IPV6, NOF, IP_GRENAT, IPV6, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(898, IP, IPV6, NOF, IP_GRENAT, IPV6, NOF, UDP,  PAY4, PAY4),
	SXE2VF_PTYPE(899, IP, IPV6, NOF, IP_GRENAT, IPV6, NOF, TCP,  PAY4, PAY4),
	SXE2VF_PTYPE(895, IP, IPV6, NOF, IP_GRENAT, IPV6, NOF, SCTP, PAY4, PAY4),
	SXE2VF_PTYPE(894, IP, IPV6, NOF, IP_GRENAT, IPV6, NOF, ICMP, PAY4, PAY3),

	SXE2VF_PTYPE(917, IP, IPV4, NOF, IP_GRENAT, NONE, NOF, NONE, PAY4, PAY4),

	SXE2VF_PTYPE(916, IP, IPV4, NOF, IP_GRENAT, IPV4, FRG, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(915, IP, IPV4, NOF, IP_GRENAT, IPV4, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(918, IP, IPV4, NOF, IP_GRENAT, IPV4, NOF, UDP,  PAY4, PAY4),
	SXE2VF_PTYPE(919, IP, IPV4, NOF, IP_GRENAT, IPV4, NOF, TCP,  PAY4, PAY4),
	SXE2VF_PTYPE(914, IP, IPV4, NOF, IP_GRENAT, IPV4, NOF, SCTP, PAY4, PAY4),
	SXE2VF_PTYPE(913, IP, IPV4, NOF, IP_GRENAT, IPV4, NOF, ICMP, PAY4, PAY3),

	SXE2VF_PTYPE(910, IP, IPV4, NOF, IP_GRENAT, IPV6, FRG, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(909, IP, IPV4, NOF, IP_GRENAT, IPV6, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(911, IP, IPV4, NOF, IP_GRENAT, IPV6, NOF, UDP,  PAY4, PAY4),
	SXE2VF_PTYPE(912, IP, IPV4, NOF, IP_GRENAT, IPV6, NOF, TCP,  PAY4, PAY4),
	SXE2VF_PTYPE(908, IP, IPV4, NOF, IP_GRENAT, IPV6, NOF, SCTP, PAY4, PAY4),
	SXE2VF_PTYPE(907, IP, IPV4, NOF, IP_GRENAT, IPV6, NOF, ICMP, PAY4, PAY3),

	SXE2VF_PTYPE(930, IP, IPV6, NOF, IP_GRENAT_MAC_VLAN, NONE, NOF, NONE, PAY4, PAY4),

	SXE2VF_PTYPE(929, IP, IPV6, NOF, IP_GRENAT_MAC_VLAN, IPV4, FRG, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(928, IP, IPV6, NOF, IP_GRENAT_MAC_VLAN, IPV4, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(931, IP, IPV6, NOF, IP_GRENAT_MAC_VLAN, IPV4, NOF, UDP,  PAY4, PAY4),
	SXE2VF_PTYPE(932, IP, IPV6, NOF, IP_GRENAT_MAC_VLAN, IPV4, NOF, TCP,  PAY4, PAY4),
	SXE2VF_PTYPE(927, IP, IPV6, NOF, IP_GRENAT_MAC_VLAN, IPV4, NOF, SCTP, PAY4, PAY4),
	SXE2VF_PTYPE(926, IP, IPV6, NOF, IP_GRENAT_MAC_VLAN, IPV4, NOF, ICMP, PAY4, PAY3),

	SXE2VF_PTYPE(923, IP, IPV6, NOF, IP_GRENAT_MAC_VLAN, IPV6, FRG, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(922, IP, IPV6, NOF, IP_GRENAT_MAC_VLAN, IPV6, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(924, IP, IPV6, NOF, IP_GRENAT_MAC_VLAN, IPV6, NOF, UDP,  PAY4, PAY4),
	SXE2VF_PTYPE(925, IP, IPV6, NOF, IP_GRENAT_MAC_VLAN, IPV6, NOF, TCP,  PAY4, PAY4),
	SXE2VF_PTYPE(921, IP, IPV6, NOF, IP_GRENAT_MAC_VLAN, IPV6, NOF, SCTP, PAY4, PAY4),
	SXE2VF_PTYPE(920, IP, IPV6, NOF, IP_GRENAT_MAC_VLAN, IPV6, NOF, ICMP, PAY4, PAY3),

	SXE2VF_PTYPE(943, IP, IPV4, NOF, IP_GRENAT_MAC_VLAN, NONE, NOF, NONE, PAY4, PAY4),

	SXE2VF_PTYPE(942, IP, IPV4, NOF, IP_GRENAT_MAC_VLAN, IPV4, FRG, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(941, IP, IPV4, NOF, IP_GRENAT_MAC_VLAN, IPV4, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(944, IP, IPV4, NOF, IP_GRENAT_MAC_VLAN, IPV4, NOF, UDP,  PAY4, PAY4),
	SXE2VF_PTYPE(945, IP, IPV4, NOF, IP_GRENAT_MAC_VLAN, IPV4, NOF, TCP,  PAY4, PAY4),
	SXE2VF_PTYPE(940, IP, IPV4, NOF, IP_GRENAT_MAC_VLAN, IPV4, NOF, SCTP, PAY4, PAY4),
	SXE2VF_PTYPE(939, IP, IPV4, NOF, IP_GRENAT_MAC_VLAN, IPV4, NOF, ICMP, PAY4, PAY3),

	SXE2VF_PTYPE(936, IP, IPV4, NOF, IP_GRENAT_MAC_VLAN, IPV6, FRG, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(935, IP, IPV4, NOF, IP_GRENAT_MAC_VLAN, IPV6, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(937, IP, IPV4, NOF, IP_GRENAT_MAC_VLAN, IPV6, NOF, UDP,  PAY4, PAY4),
	SXE2VF_PTYPE(938, IP, IPV4, NOF, IP_GRENAT_MAC_VLAN, IPV6, NOF, TCP,  PAY4, PAY4),
	SXE2VF_PTYPE(934, IP, IPV4, NOF, IP_GRENAT_MAC_VLAN, IPV6, NOF, SCTP, PAY4, PAY4),
	SXE2VF_PTYPE(933, IP, IPV4, NOF, IP_GRENAT_MAC_VLAN, IPV6, NOF, ICMP, PAY4, PAY3),

	SXE2VF_PTYPE(956, IP, IPV6, NOF, IP_GRENAT_MAC_VLAN, NONE, NOF, NONE, PAY4, PAY4),

	SXE2VF_PTYPE(955, IP, IPV6, NOF, IP_GRENAT_MAC_VLAN, IPV4, FRG, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(954, IP, IPV6, NOF, IP_GRENAT_MAC_VLAN, IPV4, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(957, IP, IPV6, NOF, IP_GRENAT_MAC_VLAN, IPV4, NOF, UDP,  PAY4, PAY4),
	SXE2VF_PTYPE(958, IP, IPV6, NOF, IP_GRENAT_MAC_VLAN, IPV4, NOF, TCP,  PAY4, PAY4),
	SXE2VF_PTYPE(953, IP, IPV6, NOF, IP_GRENAT_MAC_VLAN, IPV4, NOF, SCTP, PAY4, PAY4),
	SXE2VF_PTYPE(952, IP, IPV6, NOF, IP_GRENAT_MAC_VLAN, IPV4, NOF, ICMP, PAY4, PAY3),

	SXE2VF_PTYPE(949, IP, IPV6, NOF, IP_GRENAT_MAC_VLAN, IPV6, FRG, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(948, IP, IPV6, NOF, IP_GRENAT_MAC_VLAN, IPV6, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(950, IP, IPV6, NOF, IP_GRENAT_MAC_VLAN, IPV6, NOF, UDP,  PAY4, PAY4),
	SXE2VF_PTYPE(951, IP, IPV6, NOF, IP_GRENAT_MAC_VLAN, IPV6, NOF, TCP,  PAY4, PAY4),
	SXE2VF_PTYPE(947, IP, IPV6, NOF, IP_GRENAT_MAC_VLAN, IPV6, NOF, SCTP, PAY4, PAY4),
	SXE2VF_PTYPE(946, IP, IPV6, NOF, IP_GRENAT_MAC_VLAN, IPV6, NOF, ICMP, PAY4, PAY3),

	SXE2VF_PTYPE(969, IP, IPV4, NOF, IP_GRENAT_MAC_VLAN, NONE, NOF, NONE, PAY4, PAY4),

	SXE2VF_PTYPE(968, IP, IPV4, NOF, IP_GRENAT_MAC_VLAN, IPV4, FRG, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(967, IP, IPV4, NOF, IP_GRENAT_MAC_VLAN, IPV4, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(970, IP, IPV4, NOF, IP_GRENAT_MAC_VLAN, IPV4, NOF, UDP,  PAY4, PAY4),
	SXE2VF_PTYPE(971, IP, IPV4, NOF, IP_GRENAT_MAC_VLAN, IPV4, NOF, TCP,  PAY4, PAY4),
	SXE2VF_PTYPE(966, IP, IPV4, NOF, IP_GRENAT_MAC_VLAN, IPV4, NOF, SCTP, PAY4, PAY4),
	SXE2VF_PTYPE(965, IP, IPV4, NOF, IP_GRENAT_MAC_VLAN, IPV4, NOF, ICMP, PAY4, PAY3),

	SXE2VF_PTYPE(962, IP, IPV4, NOF, IP_GRENAT_MAC_VLAN, IPV6, FRG, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(961, IP, IPV4, NOF, IP_GRENAT_MAC_VLAN, IPV6, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(963, IP, IPV4, NOF, IP_GRENAT_MAC_VLAN, IPV6, NOF, UDP,  PAY4, PAY4),
	SXE2VF_PTYPE(964, IP, IPV4, NOF, IP_GRENAT_MAC_VLAN, IPV6, NOF, TCP,  PAY4, PAY4),
	SXE2VF_PTYPE(960, IP, IPV4, NOF, IP_GRENAT_MAC_VLAN, IPV6, NOF, SCTP, PAY4, PAY4),
	SXE2VF_PTYPE(959, IP, IPV4, NOF, IP_GRENAT_MAC_VLAN, IPV6, NOF, ICMP, PAY4, PAY3),

	SXE2VF_PTYPE(982, IP, IPV6, NOF, IP_GRENAT_MAC, NONE, NOF, NONE, PAY4, PAY4),

	SXE2VF_PTYPE(981, IP, IPV6, NOF, IP_GRENAT_MAC, IPV4, FRG, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(980, IP, IPV6, NOF, IP_GRENAT_MAC, IPV4, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(983, IP, IPV6, NOF, IP_GRENAT_MAC, IPV4, NOF, UDP,  PAY4, PAY4),
	SXE2VF_PTYPE(984, IP, IPV6, NOF, IP_GRENAT_MAC, IPV4, NOF, TCP,  PAY4, PAY4),
	SXE2VF_PTYPE(979, IP, IPV6, NOF, IP_GRENAT_MAC, IPV4, NOF, SCTP, PAY4, PAY4),
	SXE2VF_PTYPE(978, IP, IPV6, NOF, IP_GRENAT_MAC, IPV4, NOF, ICMP, PAY4, PAY3),

	SXE2VF_PTYPE(975, IP, IPV6, NOF, IP_GRENAT_MAC, IPV6, FRG, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(974, IP, IPV6, NOF, IP_GRENAT_MAC, IPV6, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(976, IP, IPV6, NOF, IP_GRENAT_MAC, IPV6, NOF, UDP,  PAY4, PAY4),
	SXE2VF_PTYPE(977, IP, IPV6, NOF, IP_GRENAT_MAC, IPV6, NOF, TCP,  PAY4, PAY4),
	SXE2VF_PTYPE(973, IP, IPV6, NOF, IP_GRENAT_MAC, IPV6, NOF, SCTP, PAY4, PAY4),
	SXE2VF_PTYPE(972, IP, IPV6, NOF, IP_GRENAT_MAC, IPV6, NOF, ICMP, PAY4, PAY3),

	SXE2VF_PTYPE(995, IP, IPV4, NOF, IP_GRENAT_MAC, NONE, NOF, NONE, PAY4, PAY4),

	SXE2VF_PTYPE(994, IP, IPV4, NOF, IP_GRENAT_MAC, IPV4, FRG, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(993, IP, IPV4, NOF, IP_GRENAT_MAC, IPV4, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(996, IP, IPV4, NOF, IP_GRENAT_MAC, IPV4, NOF, UDP,  PAY4, PAY4),
	SXE2VF_PTYPE(997, IP, IPV4, NOF, IP_GRENAT_MAC, IPV4, NOF, TCP,  PAY4, PAY4),
	SXE2VF_PTYPE(992, IP, IPV4, NOF, IP_GRENAT_MAC, IPV4, NOF, SCTP, PAY4, PAY4),
	SXE2VF_PTYPE(991, IP, IPV4, NOF, IP_GRENAT_MAC, IPV4, NOF, ICMP, PAY4, PAY3),

	SXE2VF_PTYPE(988, IP, IPV4, NOF, IP_GRENAT_MAC, IPV6, FRG, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(987, IP, IPV4, NOF, IP_GRENAT_MAC, IPV6, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(989, IP, IPV4, NOF, IP_GRENAT_MAC, IPV6, NOF, UDP,  PAY4, PAY4),
	SXE2VF_PTYPE(990, IP, IPV4, NOF, IP_GRENAT_MAC, IPV6, NOF, TCP,  PAY4, PAY4),
	SXE2VF_PTYPE(986, IP, IPV4, NOF, IP_GRENAT_MAC, IPV6, NOF, SCTP, PAY4, PAY4),
	SXE2VF_PTYPE(985, IP, IPV4, NOF, IP_GRENAT_MAC, IPV6, NOF, ICMP, PAY4, PAY3),

	SXE2VF_PTYPE(1008, IP, IPV6, NOF, IP_GRENAT_MAC, NONE, NOF, NONE, PAY4, PAY4),

	SXE2VF_PTYPE(1007, IP, IPV6, NOF, IP_GRENAT_MAC, IPV4, FRG, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(1006, IP, IPV6, NOF, IP_GRENAT_MAC, IPV4, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(1009, IP, IPV6, NOF, IP_GRENAT_MAC, IPV4, NOF, UDP,  PAY4, PAY4),
	SXE2VF_PTYPE(1010, IP, IPV6, NOF, IP_GRENAT_MAC, IPV4, NOF, TCP,  PAY4, PAY4),
	SXE2VF_PTYPE(1005, IP, IPV6, NOF, IP_GRENAT_MAC, IPV4, NOF, SCTP, PAY4, PAY4),
	SXE2VF_PTYPE(1004, IP, IPV6, NOF, IP_GRENAT_MAC, IPV4, NOF, ICMP, PAY4, PAY3),

	SXE2VF_PTYPE(1001, IP, IPV6, NOF, IP_GRENAT_MAC, IPV6, FRG, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(1000, IP, IPV6, NOF, IP_GRENAT_MAC, IPV6, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(1002, IP, IPV6, NOF, IP_GRENAT_MAC, IPV6, NOF, UDP,  PAY4, PAY4),
	SXE2VF_PTYPE(1003, IP, IPV6, NOF, IP_GRENAT_MAC, IPV6, NOF, TCP,  PAY4, PAY4),
	SXE2VF_PTYPE(999, IP, IPV6, NOF, IP_GRENAT_MAC, IPV6, NOF, SCTP, PAY4, PAY4),
	SXE2VF_PTYPE(998, IP, IPV6, NOF, IP_GRENAT_MAC, IPV6, NOF, ICMP, PAY4, PAY3),

	SXE2VF_PTYPE(1021, IP, IPV4, NOF, IP_GRENAT_MAC, NONE, NOF, NONE, PAY4, PAY4),

	SXE2VF_PTYPE(1020, IP, IPV4, NOF, IP_GRENAT_MAC, IPV4, FRG, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(1019, IP, IPV4, NOF, IP_GRENAT_MAC, IPV4, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(1022, IP, IPV4, NOF, IP_GRENAT_MAC, IPV4, NOF, UDP,  PAY4, PAY4),
	SXE2VF_PTYPE(1023, IP, IPV4, NOF, IP_GRENAT_MAC, IPV4, NOF, TCP,  PAY4, PAY4),
	SXE2VF_PTYPE(1018, IP, IPV4, NOF, IP_GRENAT_MAC, IPV4, NOF, SCTP, PAY4, PAY4),
	SXE2VF_PTYPE(1017, IP, IPV4, NOF, IP_GRENAT_MAC, IPV4, NOF, ICMP, PAY4, PAY3),

	SXE2VF_PTYPE(1014, IP, IPV4, NOF, IP_GRENAT_MAC, IPV6, FRG, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(1013, IP, IPV4, NOF, IP_GRENAT_MAC, IPV6, NOF, NONE, PAY3, PAY3),
	SXE2VF_PTYPE(1015, IP, IPV4, NOF, IP_GRENAT_MAC, IPV6, NOF, UDP,  PAY4, PAY4),
	SXE2VF_PTYPE(1016, IP, IPV4, NOF, IP_GRENAT_MAC, IPV6, NOF, TCP,  PAY4, PAY4),
	SXE2VF_PTYPE(1012, IP, IPV4, NOF, IP_GRENAT_MAC, IPV6, NOF, SCTP, PAY4, PAY4),
	SXE2VF_PTYPE(1011, IP, IPV4, NOF, IP_GRENAT_MAC, IPV6, NOF, ICMP, PAY4, PAY3),
};

static inline struct sxe2vf_rx_ptype_info sxe2vf_rx_ptype_parse(u16 ptype)
{
	return sxe2vf_ptype_table[ptype];
}

struct sxe2vf_skb_private_data {
	dma_addr_t dma;
	u16 lro_cnt;
	bool page_released;
};

static inline u32 sxe2vf_rx_page_order(struct sxe2vf_queue *rxq)
{
	u32 order = 0;

#if (PAGE_SIZE < 8192)
	if (rxq->rx_buf_len > (PAGE_SIZE / 2))
		order = 1;
#endif
	return order;
}

#define SXE2VF_RX_PAGE_ORDER(rxq) (sxe2vf_rx_page_order(rxq))
#define SXE2VF_RX_PAGE_SIZE(rxq) (PAGE_SIZE << SXE2VF_RX_PAGE_ORDER(rxq))

#define SXE2VF_SKB_PRIV(skb) ((struct sxe2vf_skb_private_data *)(skb)->cb)

union sxe2vf_rx_desc {
	struct {
		__le64 pkt_addr;
		__le64 hdr_addr;
		__le64 rsvd1;
		__le64 rsvd2;
	} read;
	struct {
		u8 rxdid_src;
		u8 mirror;
		__le16 l2tag1;
		__le32 filter_status;

		__le16 status0_err;
		__le16 ptype_status1;
		__le32 pktl_hdrl_status2;

		__le32 status_lrocnt_fdpf_id;
		__le16 l2tag2_1st;
		__le16 l2tag2_2nd;

		u8 acl_pf_id;
		u8 sw_pf_id;
		__le16 flow_id;
		__le32 fd_filter_id;

	} wb;
};

#define SXE2VF_RX_DESC(rxq, ridx)                                              \
	(&(((union sxe2vf_rx_desc *)((rxq)->desc.base_addr))[ridx]))

#define SXE2VF_RX_DESC_SIZE(rxq)                                               \
	(ALIGN((rxq)->depth * sizeof(union sxe2vf_rx_desc), PAGE_SIZE))

#define SXE2VF_RX_BUF_LEN(rxq) ((rxq)->depth * sizeof(struct sxe2vf_rx_buf))

static inline bool sxe2vf_is_non_eop(struct sxe2vf_queue *rxq,
				     union sxe2vf_rx_desc *rx_desc)
{
	if (likely(sxe2vf_desc_status0_err_test(rx_desc->wb.status0_err,
						BIT(SXE2VF_RX_DESC_STATUS0_EOP))))
		return false;

	return true;
}

static inline u8 sxe2vf_rx_desc_lro_cnt(struct sxe2vf_queue *rxq,
					union sxe2vf_rx_desc *rx_desc)
{
	if (test_bit(SXE2VF_RXQ_LRO_ENABLED, &rxq->flags)) {
		return (le32_to_cpu(rx_desc->wb.status_lrocnt_fdpf_id) >>
			SXE2VF_RX_DESC_LROCNT_SHIFT) &
		       SXE2VF_RX_DESC_LROCNT_MASK;
	}

	return 0;
}

static inline u16 sxe2vf_rx_offset_get(struct sxe2vf_queue *rxq)
{
	return test_bit(SXE2VF_RXQ_BUILD_SKB_ENABLED, &rxq->flags) ?
		       SXE2VF_SKB_PAD_VALUE :
		       0;
}

s32 sxe2vf_rx_cfg(struct sxe2vf_vsi *vsi);

u16 sxe2vf_frame_size_set(struct sxe2vf_adapter *adapter);

void sxe2vf_rx_ring_free(struct sxe2vf_queue *rxq);

bool sxe2vf_rx_buffers_alloc(struct sxe2vf_queue *rxq, u16 cnt);

void sxe2vf_rx_rings_res_free(struct sxe2vf_vsi *vsi);

s32 sxe2vf_rxqs_stop(struct sxe2vf_vsi *vsi);

void sxe2vf_rx_rings_clean(struct sxe2vf_vsi *vsi);

int sxe2vf_rxq_irq_clean(struct sxe2vf_queue *rxq, int budget);

s32 sxe2vf_rx_hw_cfg(struct sxe2vf_vsi *vsi);

#endif
