/* SPDX-License-Identifier: GPL-2.0 or Linux-OpenIB */
/*
 * Copyright (c) 2026 nebula-matrix Limited.
 * Author:
 */

#ifndef _GRC_COMMON_H_
#define _GRC_COMMON_H_

enum grc_msg_op_code {
	GRC_MSG_OP_GET_FUNCTION_ID = 1,
	GRC_MSG_OP_SET_VOA = 2,
	GRC_MSG_OP_SET_SD_RANGE = 3,
	GRC_MSG_OP_GET_INIT_PARAM = 4,
	GRC_MSG_OP_ADD_STAT_ID = 5,
	GRC_MSG_OP_DESTROY_VOA = 6,
	GRC_MSG_OP_GET_SD_RANGE = 7,
	GRC_MSG_OP_GET_VOA_TBL = 8,
	GRC_MSG_OP_FREE_FUNC_ID = 9,
	GRC_MSG_OP_WRITE_REG = 10,
	GRC_MSG_OP_READ_REG = 11,
	GRC_MSG_OP_CQP_INIT = 12,
	GRC_MSG_OP_ADD_SRC_ADDR_INFO = 13,
	GRC_MSG_OP_DEL_SRC_ADDR_INFO = 14,
	GRC_MSG_OP_GET_SRC_ADDR_INFO = 15,
	GRC_MSG_OP_SEND_SRC_ADDR_INFO = 16,
	GRC_MSG_OP_STAT_ID_ADD = 17,
	GRC_MSG_OP_STAT_ID_DEL = 18,
	GRC_MSG_OP_STAT_ID_MOD = 19,
	GRC_MSG_OP_USED_CNT_GET = 20,
	GRC_MSG_OP_HW_STAT_GET = 21,
	GRC_MSG_OP_HW_STAT_CLEAR = 22,
	GRC_MSG_OP_ERRCODE_EN = 23,
	GRC_MSG_OP_SET_NOTIFY_INFO = 24,
	GRC_MSG_OP_HW_MISX_ID_REQ = 25,
	GRC_MSG_OP_SET_DSCH = 26,
	GRC_MSG_OP_CC_REG_SET = 27,
	GRC_MSG_OP_SET_VF_ENABLE = 28,
	GRC_MSG_OP_SET_VFID_VSI_MAP = 29,
	GRC_MSG_OP_GET_GLO_MSIX_IDX = 30,
	GRC_MSG_OP_ENA_RDMA_INTRL = 31,
	GRC_MSG_OP_UPDATE_DSCH = 32,
	GRC_MSG_OP_REGISTER_CLIENT = 33,
	GRC_MSG_OP_UNREGISTER_CLIENT = 34,
	GRC_MSG_OP_QUERY_FMR_NOFENCE = 35,
	GRC_MSG_OP_SET_DIF_VF_EN = 36,
	GRC_MSG_OP_CLEAR_CACHE = 37,
	GRC_MSG_OP_GET_ECN_STAT = 38,
	GRC_MSG_OP_MAX,
};

struct clear_cache_req {
	u32 cache_type;
};

struct get_ecn_cnt_tbl_req {
	u16 rss_lag_en;
	u16 dport_id;
	u16 lag_dport_id[NBL_RDMA_LAG_MAX_PORTS];
};

struct get_ecn_cnt_tbl_resp {
	u64 pkt_cnt;
};

#endif /* _GRC_COMMON_H_ */
