#
# Makefile for Hisilicon processors family
#

obj-$(CONFIG_ARCH_HI3521DV200) += mach-hi3521dv200.o
obj-$(CONFIG_ARCH_HI3520DV500) += mach-hi3521dv200.o
obj-$(CONFIG_ARCH_HI3516A) += mach-hi3516a.o
obj-$(CONFIG_ARCH_HI3516CV500) += mach-hi3516cv500.o
obj-$(CONFIG_ARCH_HI3516EV200) += mach-hi3516ev200.o
obj-$(CONFIG_ARCH_HI3516EV300) += mach-hi3516ev300.o
obj-$(CONFIG_ARCH_HI3518EV300) += mach-hi3518ev300.o
obj-$(CONFIG_ARCH_HI3516DV200) += mach-hi3516dv200.o
obj-$(CONFIG_ARCH_HI3516DV300) += mach-hi3516dv300.o
obj-$(CONFIG_ARCH_HI3556V200) += mach-hi3556v200.o
obj-$(CONFIG_ARCH_HI3559V200) += mach-hi3559v200.o
obj-$(CONFIG_ARCH_HI3562V100) += mach-hi3559v200.o
obj-$(CONFIG_ARCH_HI3566V100) += mach-hi3559v200.o
obj-$(CONFIG_ARCH_HI3518EV20X) += mach-hi3518ev20x.o
obj-$(CONFIG_ARCH_HI3536DV100) += mach-hi3536dv100.o
obj-$(CONFIG_ARCH_HI3521A) += mach-hi3521a.o
obj-$(CONFIG_ARCH_HI3531A) += mach-hi3531a.o
obj-$(CONFIG_ARCH_HI3556AV100) += mach-hi3556av100.o
obj-$(CONFIG_ARCH_HI3519AV100) += mach-hi3519av100.o
obj-$(CONFIG_ARCH_HI3568V100) += mach-hi3519av100.o


obj-$(CONFIG_SMP)	+= platsmp.o
