# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_KUNPENG_HCCS)	+= kunpeng_hccs.o

obj-$(CONFIG_HISI_HBMDEV)	+= hisi_hbmdev.o
obj-$(CONFIG_HISI_HBMCACHE)	+= hisi_hbmcache.o
obj-$(CONFIG_ARM64_PBHA)		+= pbha.o
hisi_l3t-objs			:= hisi_lockdown.o l3t.o
obj-$(CONFIG_HISI_L3T)		+= hisi_l3t.o
