/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (C), 2026-2026, Huawei Tech. Co., Ltd.
 * File Name     : nic_kcompat.h
 * Version       : Initial Draft
 * Created       : 2026/5/20
 * Last Modified : 2026/5/20
 * Description   :
 */

#ifndef NIC_KCOMPAT_H
#define NIC_KCOMPAT_H
#define HAVE_NETIF_NAPI_NO_WEIGHT 1
#define HAVE_NETIF_NAPI_ADD_WEIGHT 1
#define HAVE_NDO_TX_TIMEOUT_TXQ 1
#define HAVE_NDO_BPF 1
#define HAVE_NDO_GET_STATS64 1
#define HAVE_NDO_ETH_IOCTL 1
#define HAVE_VOID_NDO_GET_STATS64 1
#define HAVE_NDO_SET_FEATURES 1
#define HAVE_NAPI_GRO_FLUSH_OLD 1
#define HAVE_VF_SPOOFCHK_CONFIGURE 1
#define HAVE_NDO_SET_VF_TRUST 1
#define HAVE_NDO_SET_VF_MIN_MAX_TX_RATE 1
#define HAVE_NETDEVICE_MIN_MAX_MTU 1
#define HAVE_NETDEV_STATS_IN_NETDEV 1
#define HAVE_NETDEVICE_MACSEC_OPS 1
#define HAVE_NDO_SET_VF_LINK_STATE 1
#define HAVE_NDO_SELECT_QUEUE_SB_DEV 1
#define HAVE_NETDEV_CHANGEUPPER 1
#define HAVE_ETHTOOL_COALESCE_EXTACK 1
#define HAVE_ETHTOOL_EXTENDED_RINGPARAMS 1
#define HAVE_RXFH_HASHFUNC 1
#define HAVE_ETHTOOL_GET_RXFH_INDIR_SIZE 1
#define HAVE_ETHTOOL_GET_MODULE_EEPROM_BY_PAGE 1
#define SUPPORTED_COALESCE_PARAMS 1
#define HAVE_ETHTOOL_SET_PHYS_ID 1
#define NEED_DEFINE_SPEED_20000 1
#define NEED_DEFINE_SPEED_25000 1
#define NEED_DEFINE_SPEED_40000 1
#define NEED_DEFINE_SPEED_100000 1
#define HAVE_ETHTOOL_GLINKSETTINGS 1
#define HAVE_NEW_ETHTOOL_LINK_SETTINGS_ONLY 1
#define HAVE_NETDEV_PROG_XDP_WARN_ACTION 1
#define HAVE_XDP_DO_FLUSH_MAP 1
#define HAVE_SK_BUFF_ENCAPSULATION 1
#define HAVE_TYPEDEF_SKB_FRAG_T_BIOVEC 1
#define HAVE_SKBUFF_CSUM_LEVEL 1
#define HAVE_ETH_GET_HEADLEN_NET_DEVICE_ARG 1
#define HAVE_ETH_HW_ADDR_SET 1
#define HAVE_ETH_GET_HEADLEN_FUNC 1
#define NEED_ETH_P_8021AD 1
#define HAVE_VM_FLAGS_SET 1
#define NEED_PDE_DATA 1
#define HAVE_PDE_DATA_LOWERCASE 1
#define HAVE_NETIF_F_RXHASH 1
#define HAVE_SOCK_CREATE_KERN_NET 1
#define HAVE_UDP_TUNNEL_NIC_INFO 1
#define NEED_DEFINE_FIELD_SIZEOF 1
#define HAVE_XDP_SUPPORT 1
#define HAVE_XDP_DATA_META 1
#define HAVE_XDP_RXQ_INFO_REG_NAPI_ID 1
#define HAVE_NETDEV_XDP_ACT_NDO_XMIT 1
#define HAVE_PAGE_POOL_SUPPORT 1
#define HAVE_PAGE_POOL_NEW 1
#define HAVE_PP_FLAG_PAGE_FRAG 1
#define HAVE_FLOW_ACTION_PRIORITY 1
#define HAVE_KOBJ_TYPE_DEFAULT_GROUPS 1
#endif /* NIC_KCOMPAT_H */
