/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (C), 2026-2026, Huawei Tech. Co., Ltd.
 * File Name     : sdk_kcompat.h
 * Version       : Initial Draft
 * Created       : 2026/5/20
 * Last Modified : 2026/5/20
 * Description   :
 */

#ifndef SDK_KCOMPAT_H
#define SDK_KCOMPAT_H
#define HAVE_PCIE_RESET_DONE 1
#define NEED_PTP_ADJUST_BY_SCALED_PPM 1
#define HAVE_TIMER_SETUP 1
#define HAVE_DEVLINK_H 1
#define HAVE_DEVLINK_FLASH_UPDATE_METHOD 1
#define HAVE_DEVLINK_FLASH_UPDATE_BEGIN_END_NOTIFY 1
#define HAVE_DEVLINK_FLASH_UPDATE_PARAMS_FILE_NAME 1
#define HAVE_DEVLINK_OPS_FLASH_UPDATE_HAVE_PARAMS 1
#define HAVE_DEVLINK_PARAMS_PUBLISH 1
#define HAVE_DEVLINK_PARAMS_UNPUBLISH 1
#define HAVE_DEVLINK_ALLOC 1
#define HAVE_DEVLINK_REGISTER 1
#define HAVE_DEVLINK_REGISTER_SET_DEV 1
#define HAVE_DEVLINK_REGISTER_HAVE_RET 1
#define HAVE_CLASS_CREATE_OWNER 1
#endif /* SDK_KCOMPAT_H */
