# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2020-2026 Mucse Corporation.

obj-$(CONFIG_MCEVF) += mcevf.o

mcevf-y += mcevf_main.o
mcevf-y += mcevf_n20/mcevf_hw_n20.o
mcevf-y += mcevf_fltr.o
mcevf-y += mcevf_lib.o
mcevf-y += mcevf_irq.o
mcevf-y += mcevf_base.o
mcevf-y += mcevf_txrx_lib.o
mcevf-y += mcevf_txrx.o
mcevf-y += mcevf_netdev.o
mcevf-y += mcevf_ethtool.o
mcevf-$(CONFIG_SYSFS) += mcevf_sysfs.o
mcevf-y += mcevf_fdir.o
mcevf-y += mcevf_ethtool_fdir.o
mcevf-y += mcevf_mbx.o
mcevf-y += mcevf_virtchnl.o
mcevf-y += mcevf_idc.o
