# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the Mucse network device drivers.
#

obj-$(CONFIG_MXGBE) += rnp/
obj-$(CONFIG_MXGBEVF) += rnpvf/
obj-$(CONFIG_MXGBEM) += rnpm/
obj-$(CONFIG_MGBE) += rnpgbe/
obj-$(CONFIG_MGBEVF) += rnpgbevf/
