/* SPDX-License-Identifier: GPL-2.0 */
/* Copyright (c) 2024-2026 Mucse Corporation. */

#ifndef _MCE_PATTERN_H_
#define _MCE_PATTERN_H_

/* support pattern proto */
#define MCE_PATTERN_MAC BIT_ULL(0)
#define MCE_PATTERN_IPV4 BIT_ULL(1)
#define MCE_PATTERN_IPV6 BIT_ULL(2)
#define MCE_PATTERN_UDP BIT_ULL(3)
#define MCE_PATTERN_TCP BIT_ULL(4)
#define MCE_PATTERN_SCTP BIT_ULL(5)
#define MCE_PATTERN_ESP BIT_ULL(6)
#define MCE_PATTERN_GRE BIT_ULL(7)
#define MCE_PATTERN_NVGRE BIT_ULL(8)
#define MCE_PATTERN_VXLAN BIT_ULL(9)
#define MCE_PATTERN_GTP_C BIT_ULL(10)
#define MCE_PATTERN_GTP_U BIT_BIT64(11)

/* support pattern options */
#define MCE_OPT_SMAC BIT_ULL(63)
#define MCE_OPT_DMAC BIT_ULL(62)
#define MCE_OPT_ETHTYPE BIT_ULL(61)
#define MCE_OPT_IPV4_SIP BIT_ULL(60)
#define MCE_OPT_IPV4_DIP BIT_ULL(59)
#define MCE_OPT_IPV4_DSCP BIT_ULL(58)
#define MCE_OPT_IPV4_FRAG BIT_ULL(57)
#define MCE_OPT_IPV6_SIP BIT_ULL(56)
#define MCE_OPT_IPV6_DIP BIT_ULL(55)
#define MCE_OPT_IPV6_DSCP BIT_ULL(54)
#define MCE_OPT_IPV6_FRAG BIT_ULL(53)
#define MCE_OPT_L4_PROTO BIT_ULL(52)
#define MCE_OPT_UDP_SPORT BIT_ULL(51)
#define MCE_OPT_UDP_DPORT BIT_ULL(50)
#define MCE_OPT_TCP_SPORT BIT_ULL(49)
#define MCE_OPT_TCP_DPORT BIT_ULL(48)
#define MCE_OPT_TCP_SYNC BIT_ULL(47)
#define MCE_OPT_SCTP_SPORT BIT_ULL(46)
#define MCE_OPT_SCTP_DPORT BIT_ULL(45)
#define MCE_OPT_ESP_SPI BIT_ULL(44)
/* Only valid gre protocol type is 0x6558 */
#define MCE_OPT_NVGRE_TNI BIT_ULL(42)
#define MCE_OPT_VXLAN_VNI BIT_ULL(41)
#define MCE_OPT_GTP_C_TEID BIT_ULL(40)
#define MCE_OPT_GTP_U_TEID BIT_ULL(39)
/* only support for tunnel packet select out options */
#define MCE_OPT_OUT_IPV4_SIP BIT_ULL(38)
#define MCE_OPT_OUT_IPV4_DIP BIT_ULL(37)
#define MCE_OPT_OUT_IPV6_SIP BIT_ULL(36)
#define MCE_OPT_OUT_IPV6_DIP BIT_ULL(35)
#define MCE_OPT_OUT_L4_SPORT BIT_ULL(34)
#define MCE_OPT_OUT_L4_DPORT BIT_ULL(33)
#define MCE_OPT_VLAN_VID BIT_ULL(32)
#define MCE_OPT_L4_SPORT \
	(MCE_OPT_UDP_SPORT | MCE_OPT_TCP_SPORT | MCE_OPT_SCTP_SPORT)
#define MCE_OPT_L4_DPORT \
	(MCE_OPT_UDP_DPORT | MCE_OPT_TCP_DPORT | MCE_OPT_SCTP_DPORT)
#define MCE_OPT_OUT_IP_PORT                              \
	(MCE_OPT_OUT_IPV4_SIP | MCE_OPT_OUT_IPV4_DIP | \
	 MCE_OPT_OUT_IPV6_SIP | MCE_OPT_OUT_IPV6_DIP | \
	 MCE_OPT_OUT_L4_SPORT | MCE_OPT_OUT_L4_DPORT)
#define MCE_OPT_IN_IP_PORT                                        \
	(MCE_OPT_IPV4_SIP | MCE_OPT_IPV4_DIP | MCE_OPT_IPV6_SIP | \
	 MCE_OPT_IPV6_DIP | MCE_OPT_L4_SPORT | MCE_OPT_L4_DPORT)
#define MCE_OPT_SRC_IP_PORT                                               \
	(MCE_OPT_OUT_IPV4_SIP | MCE_OPT_IPV4_SIP | MCE_OPT_OUT_IPV6_SIP | \
	 MCE_OPT_IPV6_SIP | MCE_OPT_OUT_L4_SPORT | MCE_OPT_L4_SPORT)
#define MCE_OPT_GENEVE_VNI BIT_ULL(31)
#define MCE_OPT_SCTP_VTAG BIT_ULL(30)
#define MCE_OPT_OUT_SCTP_VTAG BIT_ULL(29)
#define MCE_OPT_S_VPORT_ID BIT_ULL(28)

#define MCE_TUNNEL_OPT                                                \
	(MCE_OPT_GENEVE_VNI | MCE_OPT_VXLAN_VNI | MCE_OPT_NVGRE_TNI | \
	 MCE_OPT_GTP_C_TEID | MCE_OPT_GTP_U_TEID)
#define MCE_TUNNEL_VLAN_OPT_MASK (MCE_TUNNEL_OPT | MCE_OPT_VLAN_VID)
/* hw packet predecode compose code */
#define MCE_PTYPE_UNKNOWN (0b000000)
#define MCE_PTYPE_L2_ONLY (0b000001)
#define MCE_PTYPE_TUN_INNER_L2_ONLY (0b000010)
#define MCE_PTYPE_TUN_OUTER_L2_ONLY (0b000011)
#define MCE_PTYPE_L2_ETHTYPE (0b000110)
#define MCE_PTYPE_TUN_INNER_L2_ETHTYPE (0b000111)
#define MCE_PTYPE_IPV4_FRAG (0b001000)
#define MCE_PTYPE_IPV4_TCP_SYNC (0b001001)
#define MCE_PTYPE_IPV4_TCP (0b001010)
#define MCE_PTYPE_IPV4_UDP (0b001011)
#define MCE_PTYPE_IPV4_SCTP (0b001100)
#define MCE_PTYPE_IPV4_ESP (0b001101)
#define MCE_PTYPE_IPV4_UDP_ESP (0b001101)
#define MCE_PTYPE_IPV4_PAY (0b001110)

#define MCE_PTYPE_IPV6_FRAG (0b010000)
#define MCE_PTYPE_IPV6_TCP_SYNC (0b010001)
#define MCE_PTYPE_IPV6_TCP (0b010010)
#define MCE_PTYPE_IPV6_UDP (0b010011)
#define MCE_PTYPE_IPV6_SCTP (0b010100)
#define MCE_PTYPE_IPV6_ESP (0b010101)
#define MCE_PTYPE_IPV6_UDP_ESP (0b010101)
#define MCE_PTYPE_IPV6_PAY (0b010110)

#define MCE_PTYPE_TUN_INNER_IPV4_FRAG (0b101000)
#define MCE_PTYPE_TUN_INNER_IPV4_TCP_SYNC (0b101001)
#define MCE_PTYPE_TUN_INNER_IPV4_TCP (0b101010)
#define MCE_PTYPE_TUN_INNER_IPV4_UDP (0b101011)
#define MCE_PTYPE_TUN_INNER_IPV4_SCTP (0b101100)
#define MCE_PTYPE_TUN_INNER_IPV4_ESP (0b101101)
#define MCE_PTYPE_TUN_INNER_IPV4_UDP_ESP (0b101101)
#define MCE_PTYPE_TUN_INNER_IPV4_PAY (0b101110)

#define MCE_PTYPE_TUN_INNER_IPV6_FRAG (0b110000)
#define MCE_PTYPE_TUN_INNER_IPV6_TCP_SYNC (0b110001)
#define MCE_PTYPE_TUN_INNER_IPV6_TCP (0b110010)
#define MCE_PTYPE_TUN_INNER_IPV6_UDP (0b110011)
#define MCE_PTYPE_TUN_INNER_IPV6_SCTP (0b110100)
#define MCE_PTYPE_TUN_INNER_IPV6_ESP (0b110101)
#define MCE_PTYPE_TUN_INNER_IPV6_UDP_ESP (0b110101)
#define MCE_PTYPE_TUN_INNER_IPV6_PAY (0b110110)
#define MCE_PTYPE_TUN_IPV4_VXLAN (0b111000)
#define MCE_PTYPE_TUN_IPV4_GENEVE (0b111001)
#define MCE_PTYPE_TUN_IPV4_GRE (0b111010)
#define MCE_PTYPE_TUN_IPV6_VXLAN (0b111100)
#define MCE_PTYPE_TUN_IPV6_GENEVE (0b111101)
#define MCE_PTYPE_TUN_IPV6_GRE (0b111110)

/* inner options only valid gtp_u message_type is 0xff */
#define MCE_PTYPE_GTP_U_INNER_IPV4_FRAG (0b000100)
#define MCE_PTYPE_GTP_U_INNER_IPV4_PAY (0b011000)
#define MCE_PTYPE_GTP_U_INNER_IPV4_TCP (0b011001)
#define MCE_PTYPE_GTP_U_INNER_IPV4_UDP (0b011010)
#define MCE_PTYPE_GTP_U_INNER_IPV4_SCTP (0b011011)
#define MCE_PTYPE_GTP_U_INNER_IPV6_FRAG (0b000101)
#define MCE_PTYPE_GTP_U_INNER_IPV6_PAY (0b011100)
#define MCE_PTYPE_GTP_U_INNER_IPV6_TCP (0b011101)
#define MCE_PTYPE_GTP_U_INNER_IPV6_UDP (0b011110)
#define MCE_PTYPE_GTP_U_INNER_IPV6_SCTP (0b011111)

/* GTPv2 only valid GTP-C outer options */
#define MCE_PTYPE_GTP_U_GPDU_IPV4 (0b100000)
#define MCE_PTYPE_GTP_U_IPV4 (0b100001)
#define MCE_PTYPE_GTP_C_TEID_IPV4 (0b100010)
#define MCE_PTYPE_GTP_C_IPV4 (0b100011)

#define MCE_PTYPE_GTP_U_GPDU_IPV6 (0b100100)
#define MCE_PTYPE_GTP_U_IPV6 (0b100101)
#define MCE_PTYPE_GTP_C_TEID_IPV6 (0b100110)
#define MCE_PTYPE_GTP_C_IPV6 (0b100111)

#define __MCE_IPV4_HDR_DSCP_MASK (0xfc)
#define __MCE_IPV6_HDR_DSCP_MASK (0xfc)

enum mce_flow_params_error_type {
	MCE_FLOW_PARAMS_ERROR_ETH = 100,
	MCE_FLOW_PARAMS_ERROR_MAX,
};

enum mce_flow_item_type {
	MCE_FLOW_ITEM_TYPE_END,
	MCE_FLOW_ITEM_TYPE_VOID,
	MCE_FLOW_ITEM_TYPE_INVERT,
	MCE_FLOW_ITEM_TYPE_ANY,
	MCE_FLOW_ITEM_TYPE_PORT_ID,
	MCE_FLOW_ITEM_TYPE_RAW,
	MCE_FLOW_ITEM_TYPE_ETH,
	MCE_FLOW_ITEM_TYPE_VLAN,
	MCE_FLOW_ITEM_TYPE_IPV4,
	MCE_FLOW_ITEM_TYPE_IPV6,
	MCE_FLOW_ITEM_TYPE_ICMP,
	MCE_FLOW_ITEM_TYPE_UDP,
	MCE_FLOW_ITEM_TYPE_TCP,
	MCE_FLOW_ITEM_TYPE_SCTP,
	MCE_FLOW_ITEM_TYPE_VXLAN,
	MCE_FLOW_ITEM_TYPE_E_TAG,
	MCE_FLOW_ITEM_TYPE_NVGRE,
	MCE_FLOW_ITEM_TYPE_MPLS,
	MCE_FLOW_ITEM_TYPE_GRE,
	MCE_FLOW_ITEM_TYPE_FUZZY,
	MCE_FLOW_ITEM_TYPE_GTP,
	MCE_FLOW_ITEM_TYPE_GTPC,
	MCE_FLOW_ITEM_TYPE_GTPU,
	MCE_FLOW_ITEM_TYPE_ESP,
	MCE_FLOW_ITEM_TYPE_GENEVE,
	MCE_FLOW_ITEM_TYPE_VXLAN_GPE,
	MCE_FLOW_ITEM_TYPE_ARP_ETH_IPV4,
	MCE_FLOW_ITEM_TYPE_IPV6_EXT,
	MCE_FLOW_ITEM_TYPE_ICMP6,
	MCE_FLOW_ITEM_TYPE_ICMP6_ND_NS,
	MCE_FLOW_ITEM_TYPE_ICMP6_ND_NA,
	MCE_FLOW_ITEM_TYPE_ICMP6_ND_OPT,
	MCE_FLOW_ITEM_TYPE_ICMP6_ND_OPT_SLA_ETH,
	MCE_FLOW_ITEM_TYPE_ICMP6_ND_OPT_TLA_ETH,
	MCE_FLOW_ITEM_TYPE_MARK,
	MCE_FLOW_ITEM_TYPE_META,
	MCE_FLOW_ITEM_TYPE_GRE_KEY,
	MCE_FLOW_ITEM_TYPE_GTP_PSC,
	MCE_FLOW_ITEM_TYPE_PPPOES,
	MCE_FLOW_ITEM_TYPE_PPPOED,
	MCE_FLOW_ITEM_TYPE_PPPOE_PROTO_ID,
	MCE_FLOW_ITEM_TYPE_NSH,
	MCE_FLOW_ITEM_TYPE_IGMP,
	MCE_FLOW_ITEM_TYPE_AH,
	MCE_FLOW_ITEM_TYPE_HIGIG2,
	MCE_FLOW_ITEM_TYPE_TAG,
	MCE_FLOW_ITEM_TYPE_L2TPV3OIP,
	MCE_FLOW_ITEM_TYPE_PFCP,
	MCE_FLOW_ITEM_TYPE_ECPRI,
	MCE_FLOW_ITEM_TYPE_IPV6_FRAG_EXT,
	MCE_FLOW_ITEM_TYPE_GENEVE_OPT,
	MCE_FLOW_ITEM_TYPE_INTEGRITY,
	MCE_FLOW_ITEM_TYPE_CONNTRACK,
	MCE_FLOW_ITEM_TYPE_PORT_REPRESENTOR,
	MCE_FLOW_ITEM_TYPE_REPRESENTED_PORT,
	MCE_FLOW_ITEM_TYPE_FLEX,
	MCE_FLOW_ITEM_TYPE_L2TPV2,
	MCE_FLOW_ITEM_TYPE_PPP,
	MCE_FLOW_ITEM_TYPE_GRE_OPTION,
	MCE_FLOW_ITEM_TYPE_MACSEC,
	MCE_FLOW_ITEM_TYPE_METER_COLOR,
	MCE_FLOW_ITEM_TYPE_IPV4_FRAG_EXT,
	MCE_FLOW_ITEM_TYPE_MAX_NUM, /* 61 */
};

#define MCE_PARSE_ARFS_FLOW_ITERM_LOOKUP_LISTS                                \
	(BIT_ULL(MCE_FLOW_ITEM_TYPE_ETH) | BIT_ULL(MCE_FLOW_ITEM_TYPE_IPV4) | \
	 BIT_ULL(MCE_FLOW_ITEM_TYPE_IPV6) | BIT_ULL(MCE_FLOW_ITEM_TYPE_UDP) | \
	 BIT_ULL(MCE_FLOW_ITEM_TYPE_TCP))

#define MCE_PARSE_FLOW_ITERM_LOOKUP_LISTS                                      \
	(BIT_ULL(MCE_FLOW_ITEM_TYPE_ETH) | BIT_ULL(MCE_FLOW_ITEM_TYPE_VLAN) |  \
	 BIT_ULL(MCE_FLOW_ITEM_TYPE_IPV4) | BIT_ULL(MCE_FLOW_ITEM_TYPE_IPV6) | \
	 BIT_ULL(MCE_FLOW_ITEM_TYPE_UDP) | BIT_ULL(MCE_FLOW_ITEM_TYPE_TCP) |   \
	 BIT_ULL(MCE_FLOW_ITEM_TYPE_SCTP) | BIT_ULL(MCE_FLOW_ITEM_TYPE_ESP))
#define MCE_PARSE_ENC_OUTER_FLOW_ITERM_LOOKUP_LISTS                           \
	(BIT_ULL(MCE_FLOW_ITEM_TYPE_ETH) | BIT_ULL(MCE_FLOW_ITEM_TYPE_IPV4) | \
	 BIT_ULL(MCE_FLOW_ITEM_TYPE_IPV6) | BIT_ULL(MCE_FLOW_ITEM_TYPE_UDP) | \
	 BIT_ULL(MCE_FLOW_ITEM_TYPE_VXLAN) |                                  \
	 BIT_ULL(MCE_FLOW_ITEM_TYPE_GENEVE) |                                 \
	 BIT_ULL(MCE_FLOW_ITEM_TYPE_NVGRE) |                                  \
	 BIT_ULL(MCE_FLOW_ITEM_TYPE_GTPC) | BIT_ULL(MCE_FLOW_ITEM_TYPE_GTPU))
#define MCE_PARSE_ENC_INNER_FLOW_ITERM_LOOKUP_LISTS                           \
	(BIT_ULL(MCE_FLOW_ITEM_TYPE_ETH) | BIT_ULL(MCE_FLOW_ITEM_TYPE_IPV4) | \
	 BIT_ULL(MCE_FLOW_ITEM_TYPE_IPV6) | BIT_ULL(MCE_FLOW_ITEM_TYPE_UDP) | \
	 BIT_ULL(MCE_FLOW_ITEM_TYPE_TCP) | BIT_ULL(MCE_FLOW_ITEM_TYPE_SCTP) | \
	 BIT_ULL(MCE_FLOW_ITEM_TYPE_VXLAN) |                                  \
	 BIT_ULL(MCE_FLOW_ITEM_TYPE_GENEVE) |                                 \
	 BIT_ULL(MCE_FLOW_ITEM_TYPE_NVGRE) |                                  \
	 BIT_ULL(MCE_FLOW_ITEM_TYPE_GTPC) | BIT_ULL(MCE_FLOW_ITEM_TYPE_GTPU))

#endif /* _MCE_PATTERN_H_ */
