#!/bin/bash
# SPDX-License-Identifier: GPL-2.0

function usage() {
	echo ""
	echo "Usage:"
	echo "    $0 [enable | disable]"
	echo ""
}

function get_cgrp_path() {
	local CGRP=`mount | grep cgroup2 | head -n 1`
	if [[ "$CGRP"X == "X" ]]; then
		CGRP=`mount | grep cgroup | grep "net_cls,net_prio" | head -n 1`
	fi
	cgrp_path=`echo $CGRP | awk '{print $3}'`
}

CMD=$1

get_cgrp_path
if [[ "$cgrp_path"X == "X" ]]; then
	echo "Failed to obtain a valid cgroup mount point."
	usage;
	exit 1
fi

if [[ "$CMD"X == "enableX" ]]; then
	/usr/sbin/tuned_acc/netacc enable ${cgrp_path}
elif [[ "$CMD"X == "disableX" ]]; then
	/usr/sbin/tuned_acc/netacc disable ${cgrp_path}
	exit 0
else
	usage;
fi
