// SPDX-License-Identifier: GPL-2.0

#include <linux/suspend.h>
#include <linux/utsname.h>
#include <linux/set_memory.h>

#include <asm/hmcall.h>
#include <asm/suspend.h>
#include <asm/csr.h>

struct processor_state hibernate_state;
/* Defined in hibernate_asm.S */
extern int restore_image(void);
extern int trampoline_restore_image(unsigned long code,
		unsigned long processor_state_addr);

/**
 * struct arch_hibernate_hdr_invariants - container to store kernel build version.
 * @uts_version: put the build number and date so that we do not resume with a
 *		different kernel.
 */
struct arch_hibernate_hdr_invariants {
	char	uts_version[__NEW_UTS_LEN + 1];
};

/**
 * struct arch_hibernate_hdr - helper paramenters that help us to restore the image.
 * @invariants: container to store kernel build version.
 * @processor_state_addr: address of image where the processor_state is saved.
 */
static struct arch_hibernate_hdr {
	struct	arch_hibernate_hdr_invariants	invariants;
	unsigned long				processor_state_addr;
} resume_hdr;

void save_processor_state(void)
{
	struct vcpucb *vcb = &(hibernate_state.vcb);
	struct soft_csrs *sc = &(hibernate_state.sc);

	vcb->ksp = rdksp();
	vcb->usp = rdusp();
	vcb->soft_tid = rtid();
#if defined(CONFIG_SUBARCH_C3B)
	vcb->ptbr = rdptbr();
#elif defined(CONFIG_SUBARCH_C4)
	vcb->ptbr_usr = sw64_read_csr(CSR_PTBR_USR);
	vcb->ptbr_sys = sw64_read_csr(CSR_PTBR_SYS);
	vcb->atc = get_atc();
	save_all_soft_csrs(sc);
#endif
}

void restore_processor_state(void)
{
	struct vcpucb *vcb = &(hibernate_state.vcb);
	struct soft_csrs *sc = &(hibernate_state.sc);

	wrksp(vcb->ksp);
	wrusp(vcb->usp);
	wrtp(vcb->soft_tid);
#if defined(CONFIG_SUBARCH_C3B)
	wrptbr(vcb->ptbr);
#elif defined(CONFIG_SUBARCH_C4)
	sw64_write_csr_imb(vcb->ptbr_usr, CSR_PTBR_USR);
	sw64_write_csr_imb(vcb->ptbr_sys, CSR_PTBR_SYS);
	set_atc(vcb->atc);
	restore_all_soft_csrs(sc);
#endif
	sflush();
	tbiv();
}

static unsigned long prepare_restore_code_page(void)
{
	void *page;

	/*
	 * Memory allocated by get_safe_page() will be handled by the hibernate code, so
	 * there is no need to free it here.
	 */
	page = (void *)get_safe_page(GFP_ATOMIC);
	if (!page)
		return -ENOMEM;
	copy_page(page, restore_image);

	/* Make sure this page is executable. */
	set_memory_x((unsigned long)page, 1);

	return (unsigned long)page;
}

int swsusp_arch_resume(void)
{
	unsigned long relocated_restore_code;

#ifdef CONFIG_SW64_KERNEL_PAGE_TABLE
	/*
	 * To ensure executable and writeable permission for the pages during resuming,
	 * set CSR_ATC to KSEG. Then restore_processor_state() will restore CSR_ATC to
	 * the value saved in the image.
	 */
	set_atc(ATC_KSEG);
#endif

	/* Prepare a retore code page so that it doesn't get overwritten by itself. */
	relocated_restore_code = prepare_restore_code_page();

	trampoline_restore_image(relocated_restore_code, resume_hdr.processor_state_addr);

	return 0;
}

/* References to section boundaries */
extern const void __nosave_begin, __nosave_end;
int pfn_is_nosave(unsigned long pfn)
{
	unsigned long nosave_begin_pfn = PFN_DOWN(__pa(&__nosave_begin));
	unsigned long nosave_end_pfn = PFN_UP(__pa(&__nosave_end));

	return	(pfn >= nosave_begin_pfn) && (pfn < nosave_end_pfn);
}

static void arch_hdr_invariants(struct arch_hibernate_hdr_invariants *i)
{
	memset(i, 0, sizeof(*i));
	memcpy(i->uts_version, init_utsname()->version, sizeof(i->uts_version));
}

/**
 *	arch_hibernation_header_save - populate the architecture specific part
 *		of a hibernation image header, and save helper paramenters.
 *	@addr: address to save the data at
 */
int arch_hibernation_header_save(void *addr, unsigned int max_size)
{
	struct arch_hibernate_hdr *hdr = addr;

	if (max_size < sizeof(*hdr))
		return -EOVERFLOW;

	arch_hdr_invariants(&hdr->invariants);
	hdr->processor_state_addr = (unsigned long)&hibernate_state;

	return 0;
}
EXPORT_SYMBOL(arch_hibernation_header_save);

/**
 *	arch_hibernation_header_restore - read the architecture specific data
 *		from the hibernation image header
 *	@addr: address to read the data from
 */
int arch_hibernation_header_restore(void *addr)
{
	struct arch_hibernate_hdr_invariants invariants;
	struct arch_hibernate_hdr *hdr = addr;

	arch_hdr_invariants(&invariants);
	if (memcmp(&hdr->invariants, &invariants, sizeof(invariants))) {
		pr_crit("Hibernate image not generated by this kernel!\n");
		return -EINVAL;
	}

	resume_hdr = *hdr;

	return 0;
}
EXPORT_SYMBOL(arch_hibernation_header_restore);
