/* SPDX-License-Identifier: GPL-2.0+ */
/*
 * Copyright (c) 2025 HiSilicon Technologies Co., Ltd. All rights reserved.
 * Description: ubdevshm uba record management module
 */

#ifndef _UBDEVSHM_UBA_RECORD_H
#define _UBDEVSHM_UBA_RECORD_H

#include <linux/types.h>
#include <linux/list.h>
#include <linux/mutex.h>
#include <linux/refcount.h>
#include <ub/ubdevshm/ubdevshm.h>

/* Forward declaration */
struct shm_container;
struct access_ctx_inner;

/**
 * struct uba_record - record for each acquire operation
 * @node: link to access_ctx_inner.uba_list
 * @uba: independent uba generated by each acquire
 * @owner: used to find ctx_inner
 * @id: uba_record id embedded in mem_handle
 * @va: virtual address
 * @size: size
 */
struct uba_record {
	struct list_head node;
	struct mem_uba uba;
	struct access_ctx_inner *owner;
	int id;
	u64 va;
	u64 size;
};

/**
 * ubdevshm_uba_record_init() - initialize uba record module
 */
void ubdevshm_uba_record_init(void);

/**
 * ubdevshm_uba_record_uninit() - cleanup uba record module
 */
void ubdevshm_uba_record_uninit(void);

/**
 * ubdevshm_create_uba_record() - create an uba record
 * @ctx_inner: context that owns this record
 * @rrec: output of created record
 *
 * Return: 0 indicate success, other value indicate failure
 */
int ubdevshm_create_uba_record(struct access_ctx_inner *ctx_inner,
				struct uba_record **rrec);

/**
 * ubdevshm_link_uba_record_to_ctx() - link a record to its context
 * @cntr: container that owns the context
 * @ctx_inner: context to link to
 * @rec: record to link
 *
 * This function allocates an IDR ID for the record and adds it to the
 * context's uba_list while incrementing the acquire_refcnt.
 *
 * Return: 0 indicate success, -ENOENT if context is being destroyed
 */
int ubdevshm_link_uba_record_to_ctx(struct shm_container *cntr,
				     struct access_ctx_inner *ctx_inner,
				     struct uba_record *rec);

/**
 * ubdevshm_find_get_access_ctx_by_uba_record() - find and get context by record ID
 * @rec_id: record ID to look up
 * @rrec: output of found record
 *
 * Return: access context with increased reference count, or NULL if not found
 */
struct access_ctx_inner *ubdevshm_find_get_access_ctx_by_uba_record(u32 rec_id,
								      struct uba_record **rrec);

/**
 * ubdevshm_release_uba_record() - release an uba record
 * @cntr: container used for locking
 * @rec: record to release
 *
 * This removes the record from the context's list, from IDR, and frees memory.
 */
void ubdevshm_release_uba_record(struct shm_container *cntr, struct uba_record *rec);

/**
 * ubdevshm_cleanup_uba_records_in_ctx() - clean up all records in a context
 * @ctx: context whose records to clean up
 *
 * This is called when destroying an access context to clean up any
 * leftover records. Typically, the list should be empty.
 */
void ubdevshm_cleanup_uba_records_in_ctx(struct access_ctx_inner *ctx);

#endif /* _UBDEVSHM_UBA_RECORD_H */
