/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (C), 2026-2026, Huawei Tech. Co., Ltd.
 * File Name     : hinic5_csr_inner.h
 * Version       : Initial Draft
 * Created       : 2026/5/20
 * Last Modified : 2026/5/20
 * Description   :
 */

#ifndef HINIC5_CSR_INNER_H
#define HINIC5_CSR_INNER_H

/* bit31/bit30 for bar index flag
 * 00: bar0
 * 01: bar1
 * 10: bar2
 * 11: bar3
 */
#define HINIC5_CFG_REGS_FLAG			0x40000000

#define HINIC5_MGMT_REGS_FLAG			0xC0000000

#define HINIC5_REGS_FLAG_MASK			0x3FFFFFFF

#define HINIC5_VF_CFG_REG_OFFSET		0x2000

#define HINIC5_MISC_INTC_BAR				0x18000

#define HINIC5_HOST_CSR_BASE_ADDR		(HINIC5_MGMT_REGS_FLAG + 0x6000)
#define HINIC5_CSR_GLOBAL_BASE_ADDR		(HINIC5_MGMT_REGS_FLAG + 0x6400)

/* HW interface registers */
#define HINIC5_CSR_FUNC_ATTR0_ADDR		(HINIC5_CFG_REGS_FLAG + 0x0)
#define HINIC5_CSR_FUNC_ATTR1_ADDR		(HINIC5_CFG_REGS_FLAG + 0x4)
#define HINIC5_CSR_FUNC_ATTR2_ADDR		(HINIC5_CFG_REGS_FLAG + 0x8)
#define HINIC5_CSR_FUNC_ATTR3_ADDR		(HINIC5_CFG_REGS_FLAG + 0xC)
#define HINIC5_CSR_FUNC_ATTR4_ADDR		(HINIC5_CFG_REGS_FLAG + 0x10)
#define HINIC5_CSR_FUNC_ATTR5_ADDR		(HINIC5_CFG_REGS_FLAG + 0x14)
#define HINIC5_CSR_FUNC_ATTR6_ADDR		(HINIC5_CFG_REGS_FLAG + 0x18)
#define HINIC5_CSR_FUNC_TASK1_ADDR		(HINIC5_CFG_REGS_FLAG + 0x24)

#define HINIC5_CSR_INTC_BAR_SW_HANDSHAKE_0_CSR0_REG		(HINIC5_MISC_INTC_BAR + 0x44)

#define HINIC5_FUNC_CSR_MAILBOX_DATA_OFF	0x80
#define HINIC5_FUNC_CSR_MAILBOX_CONTROL_OFF		\
			(HINIC5_CFG_REGS_FLAG + 0x0100)
#define HINIC5_FUNC_CSR_MAILBOX_INT_OFFSET_OFF		\
			(HINIC5_CFG_REGS_FLAG + 0x0104)
#define HINIC5_FUNC_CSR_MAILBOX_RESULT_H_OFF		\
			(HINIC5_CFG_REGS_FLAG + 0x0108)
#define HINIC5_FUNC_CSR_MAILBOX_RESULT_L_OFF		\
			(HINIC5_CFG_REGS_FLAG + 0x010C)
/* CLP registers */
#define HINIC5_BAR3_CLP_BASE_ADDR		(HINIC5_MGMT_REGS_FLAG + 0x0000)

#define HINIC5_UCPU_CLP_SIZE_REG	(HINIC5_HOST_CSR_BASE_ADDR + 0x40)
#define HINIC5_UCPU_CLP_REQBASE_REG	(HINIC5_HOST_CSR_BASE_ADDR + 0x44)
#define HINIC5_UCPU_CLP_RSPBASE_REG	(HINIC5_HOST_CSR_BASE_ADDR + 0x48)
#define HINIC5_UCPU_CLP_REQ_REG		(HINIC5_HOST_CSR_BASE_ADDR + 0x4c)
#define HINIC5_UCPU_CLP_RSP_REG		(HINIC5_HOST_CSR_BASE_ADDR + 0x50)
#define HINIC5_CLP_REG(member)		(HINIC5_UCPU_CLP_##member##_REG)

#define HINIC5_CLP_REQ_DATA		HINIC5_BAR3_CLP_BASE_ADDR
#define HINIC5_CLP_RSP_DATA		(HINIC5_BAR3_CLP_BASE_ADDR + 0x1000)
#define HINIC5_CLP_DATA(member)		(HINIC5_CLP_##member##_DATA)

#define HINIC5_PTP_TS_UPDT_CFG_REG		(HINIC5_CSR_GLOBAL_BASE_ADDR + 0x3AC)
#define HINIC5_PTP_TS_INC_CFG_REG		(HINIC5_CSR_GLOBAL_BASE_ADDR + 0x3B0)
#define HINIC5_PTP_TS_CALIBRATION_REG	(HINIC5_CSR_GLOBAL_BASE_ADDR + 0x3B4)
#define HINIC5_PTP_TS_WR_DATA0_REG		(HINIC5_CSR_GLOBAL_BASE_ADDR + 0x3B8)
#define HINIC5_PTP_TS_WR_DATA1_REG		(HINIC5_CSR_GLOBAL_BASE_ADDR + 0x3BC)
#define HINIC5_PTP_TS_WR_DATA2_REG		(HINIC5_CSR_GLOBAL_BASE_ADDR + 0x3C0)
#define HINIC5_PTP_TS_RD_DATA0_REG		(HINIC5_CSR_GLOBAL_BASE_ADDR + 0x3C4)
#define HINIC5_PTP_TS_RD_DATA1_REG		(HINIC5_CSR_GLOBAL_BASE_ADDR + 0x3C8)
#define HINIC5_PTP_TS_RD_DATA2_REG		(HINIC5_CSR_GLOBAL_BASE_ADDR + 0x3CC)
#define HINIC5_PTP_TS_UP_EN_REG			(HINIC5_CSR_GLOBAL_BASE_ADDR + 0x3D0)
#define HINIC5_PTP_TS_DSTR_CFG_REG		(HINIC5_CSR_GLOBAL_BASE_ADDR + 0x3D4)
#define HINIC5_PTP_REG(member)			(HINIC5_PTP_TS_##member##_REG)

#define HINIC5_N_PTP_TS_WR_DATA0_REG		(HINIC5_CSR_GLOBAL_BASE_ADDR + 0x3E0)
#define HINIC5_N_PTP_TS_WR_DATA1_REG		(HINIC5_CSR_GLOBAL_BASE_ADDR + 0x3E4)
#define HINIC5_N_PTP_TS_WR_DATA2_REG		(HINIC5_CSR_GLOBAL_BASE_ADDR + 0x3E8)
#define HINIC5_N_PTP_TS_RD_DATA0_REG		(HINIC5_CSR_GLOBAL_BASE_ADDR + 0x3EC)
#define HINIC5_N_PTP_TS_RD_DATA1_REG		(HINIC5_CSR_GLOBAL_BASE_ADDR + 0x3F0)
#define HINIC5_N_PTP_TS_RD_DATA2_REG		(HINIC5_CSR_GLOBAL_BASE_ADDR + 0x3F4)
#define HINIC5_N_PTP_TS_UP_EN_REG			(HINIC5_CSR_GLOBAL_BASE_ADDR + 0x3F8)
#define HINIC5_N_PTP_REG(member)			(HINIC5_N_PTP_TS_##member##_REG)

#define HINIC5_PPF_ELECTION_OFFSET		0x0
#define HINIC5_MPF_ELECTION_OFFSET		0x20

#define HINIC5_CSR_PPF_ELECTION_ADDR		\
			(HINIC5_HOST_CSR_BASE_ADDR + HINIC5_PPF_ELECTION_OFFSET)

#define HINIC5_CSR_GLOBAL_MPF_ELECTION_ADDR		\
			(HINIC5_HOST_CSR_BASE_ADDR + HINIC5_MPF_ELECTION_OFFSET)

#define HINIC5_CSR_FUNC_PPF_ELECT_BASE_ADDR	(HINIC5_CFG_REGS_FLAG + 0x60)
#define HINIC5_CSR_FUNC_PPF_ELECT_PORT_STRIDE	0x4

#define HINIC5_CSR_FUNC_PPF_ELECT(host_idx)	\
	(HINIC5_CSR_FUNC_PPF_ELECT_BASE_ADDR +	\
	 (host_idx) * HINIC5_CSR_FUNC_PPF_ELECT_PORT_STRIDE)

#define HINIC5_CSR_DMA_ATTR_TBL_ADDR		(HINIC5_CFG_REGS_FLAG + 0x380)
#define HINIC5_CSR_DMA_ATTR_INDIR_IDX_ADDR	(HINIC5_CFG_REGS_FLAG + 0x390)

/* MSI-X registers */
#define HINIC5_CSR_MSIX_INDIR_IDX_ADDR		(HINIC5_CFG_REGS_FLAG + 0x310)
#define HINIC5_CSR_MSIX_CTRL_ADDR		(HINIC5_CFG_REGS_FLAG + 0x300)
#define HINIC5_CSR_MSIX_CNT_ADDR		(HINIC5_CFG_REGS_FLAG +	0x304)
#define HINIC5_CSR_FUNC_MSI_CLR_WR_ADDR		(HINIC5_CFG_REGS_FLAG + 0x58)

#define HINIC5_MSI_CLR_INDIR_RESEND_TIMER_CLR_SHIFT	0
#define HINIC5_MSI_CLR_INDIR_INT_MSK_SET_SHIFT		1
#define HINIC5_MSI_CLR_INDIR_INT_MSK_CLR_SHIFT		2
#define HINIC5_MSI_CLR_INDIR_AUTO_MSK_SET_SHIFT		3
#define HINIC5_MSI_CLR_INDIR_AUTO_MSK_CLR_SHIFT		4
#define HINIC5_MSI_CLR_INDIR_SIMPLE_INDIR_IDX_SHIFT	22

#define HINIC5_MSI_CLR_INDIR_RESEND_TIMER_CLR_MASK	0x1U
#define HINIC5_MSI_CLR_INDIR_INT_MSK_SET_MASK		0x1U
#define HINIC5_MSI_CLR_INDIR_INT_MSK_CLR_MASK		0x1U
#define HINIC5_MSI_CLR_INDIR_AUTO_MSK_SET_MASK		0x1U
#define HINIC5_MSI_CLR_INDIR_AUTO_MSK_CLR_MASK		0x1U
#define HINIC5_MSI_CLR_INDIR_SIMPLE_INDIR_IDX_MASK	0x3FFU

#define HINIC5_MSI_CLR_INDIR_SET(val, member)		\
		(((val) & HINIC5_MSI_CLR_INDIR_##member##_MASK) << \
		HINIC5_MSI_CLR_INDIR_##member##_SHIFT)

/* EQ registers */
#define HINIC5_AEQ_INDIR_IDX_ADDR		(HINIC5_CFG_REGS_FLAG + 0x210)
#define HINIC5_CEQ_INDIR_IDX_ADDR		(HINIC5_CFG_REGS_FLAG + 0x290)

#define HINIC5_EQ_INDIR_IDX_ADDR(type) \
		((type == HINIC5_AEQ) ? \
		HINIC5_AEQ_INDIR_IDX_ADDR : HINIC5_CEQ_INDIR_IDX_ADDR)

#define HINIC5_AEQ_MTT_OFF_BASE_ADDR		(HINIC5_CFG_REGS_FLAG + 0x240)
#define HINIC5_CEQ_MTT_OFF_BASE_ADDR		(HINIC5_CFG_REGS_FLAG + 0x2C0)

#define HINIC5_CSR_EQ_PAGE_OFF_STRIDE			8

#define HINIC5_AEQ_HI_PHYS_ADDR_REG(pg_num)	\
		(HINIC5_AEQ_MTT_OFF_BASE_ADDR + \
		(pg_num) * HINIC5_CSR_EQ_PAGE_OFF_STRIDE)

#define HINIC5_AEQ_LO_PHYS_ADDR_REG(pg_num)	\
		(HINIC5_AEQ_MTT_OFF_BASE_ADDR + \
		(pg_num) * HINIC5_CSR_EQ_PAGE_OFF_STRIDE + 4)

#define HINIC5_CEQ_HI_PHYS_ADDR_REG(pg_num)	\
		(HINIC5_CEQ_MTT_OFF_BASE_ADDR + \
		(pg_num) * HINIC5_CSR_EQ_PAGE_OFF_STRIDE)

#define HINIC5_CEQ_LO_PHYS_ADDR_REG(pg_num)	\
		(HINIC5_CEQ_MTT_OFF_BASE_ADDR + \
		(pg_num) * HINIC5_CSR_EQ_PAGE_OFF_STRIDE + 4)

#define HINIC5_CSR_AEQ_CTRL_0_ADDR		(HINIC5_CFG_REGS_FLAG + 0x200)
#define HINIC5_CSR_AEQ_CTRL_1_ADDR		(HINIC5_CFG_REGS_FLAG + 0x204)
#define HINIC5_CSR_AEQ_CONS_IDX_ADDR		(HINIC5_CFG_REGS_FLAG + 0x208)
#define HINIC5_CSR_AEQ_PROD_IDX_ADDR		(HINIC5_CFG_REGS_FLAG + 0x20C)
#define HINIC5_CSR_AEQ_CI_SIMPLE_INDIR_ADDR	(HINIC5_CFG_REGS_FLAG + 0x50)

#define HINIC5_CSR_CEQ_CTRL_0_ADDR		(HINIC5_CFG_REGS_FLAG + 0x280)
#define HINIC5_CSR_CEQ_CTRL_1_ADDR		(HINIC5_CFG_REGS_FLAG + 0x284)
#define HINIC5_CSR_CEQ_CONS_IDX_ADDR		(HINIC5_CFG_REGS_FLAG + 0x288)
#define HINIC5_CSR_CEQ_PROD_IDX_ADDR		(HINIC5_CFG_REGS_FLAG + 0x28c)
#define HINIC5_CSR_CEQ_CI_SIMPLE_INDIR_ADDR	(HINIC5_CFG_REGS_FLAG + 0x54)

/* API CMD registers */
#define HINIC5_CSR_API_CMD_BASE			(HINIC5_MGMT_REGS_FLAG + 0x2000)

#define HINIC5_CSR_API_CMD_STRIDE		0x80

#define HINIC5_CSR_API_CMD_CHAIN_HEAD_HI_ADDR(idx)	\
	(HINIC5_CSR_API_CMD_BASE + 0x0 + (idx) * HINIC5_CSR_API_CMD_STRIDE)

#define HINIC5_CSR_API_CMD_CHAIN_HEAD_LO_ADDR(idx)	\
	(HINIC5_CSR_API_CMD_BASE + 0x4 + (idx) * HINIC5_CSR_API_CMD_STRIDE)

#define HINIC5_CSR_API_CMD_STATUS_HI_ADDR(idx)		\
	(HINIC5_CSR_API_CMD_BASE + 0x8 + (idx) * HINIC5_CSR_API_CMD_STRIDE)

#define HINIC5_CSR_API_CMD_STATUS_LO_ADDR(idx)		\
	(HINIC5_CSR_API_CMD_BASE + 0xC + (idx) * HINIC5_CSR_API_CMD_STRIDE)

#define HINIC5_CSR_API_CMD_CHAIN_NUM_CELLS_ADDR(idx)	\
	(HINIC5_CSR_API_CMD_BASE + 0x10 + (idx) * HINIC5_CSR_API_CMD_STRIDE)

#define HINIC5_CSR_API_CMD_CHAIN_CTRL_ADDR(idx)		\
	(HINIC5_CSR_API_CMD_BASE + 0x14 + (idx) * HINIC5_CSR_API_CMD_STRIDE)

#define HINIC5_CSR_API_CMD_CHAIN_PI_ADDR(idx)		\
	(HINIC5_CSR_API_CMD_BASE + 0x1C + (idx) * HINIC5_CSR_API_CMD_STRIDE)

#define HINIC5_CSR_API_CMD_CHAIN_REQ_ADDR(idx)		\
	(HINIC5_CSR_API_CMD_BASE + 0x20 + (idx) * HINIC5_CSR_API_CMD_STRIDE)

#define HINIC5_CSR_API_CMD_STATUS_0_ADDR(idx)		\
	(HINIC5_CSR_API_CMD_BASE + 0x30 + (idx) * HINIC5_CSR_API_CMD_STRIDE)

/* self test register */
#define HINIC5_MGMT_HEALTH_STATUS_ADDR (HINIC5_MGMT_REGS_FLAG + 0x983c)

#define HINIC5_CHIP_BASE_INFO_ADDR (HINIC5_MGMT_REGS_FLAG + 0xB02C)

#define HINIC5_CHIP_ERR_STATUS0_ADDR (HINIC5_MGMT_REGS_FLAG + 0xC0EC)
#define HINIC5_CHIP_ERR_STATUS1_ADDR (HINIC5_MGMT_REGS_FLAG + 0xC0F0)

#define HINIC5_ERR_INFO0_ADDR (HINIC5_MGMT_REGS_FLAG + 0xC0F4)
#define HINIC5_ERR_INFO1_ADDR (HINIC5_MGMT_REGS_FLAG + 0xC0F8)
#define HINIC5_ERR_INFO2_ADDR (HINIC5_MGMT_REGS_FLAG + 0xC0FC)

#define HINIC5_MULT_HOST_SLAVE_STATUS_ADDR (HINIC5_MGMT_REGS_FLAG + 0xEA08)
#define HINIC5_MULT_MIGRATE_HOST_STATUS_ADDR (HINIC5_MGMT_REGS_FLAG + 0xEA0C)

#endif
