obj-y					+= core.o
obj-y					+= amd/
obj-$(CONFIG_X86_LOCAL_APIC)            += msr.o
obj-$(CONFIG_CPU_SUP_INTEL)		+= intel/
obj-$(CONFIG_CPU_SUP_CENTAUR)		+= zhaoxin/
obj-$(CONFIG_CPU_SUP_ZHAOXIN)		+= zhaoxin/
