obj-$(CONFIG_MXGBEM) += rnpm.o
rnpm-objs :=   \
		rnpm_common.o \
		rnpm_debugfs.o \
		rnpm_ethtool.o \
		rnpm_lib.o \
		rnpm_main.o \
		rnpm_mbx.o \
		rnpm_n10.o \
		rnpm_pcs.o \
		rnpm_mbx_fw.o\
		rnpm_phy.o \
		rnpm_sriov.o \
		rnpm_sysfs.o \
		rnpm_tc.o \
		rnpm_mpe.o \
		rnpm_ptp.o

