#*******************************************************************************
#*******************************************************************************

include_directories(${CMAKE_CURRENT_SOURCE_DIR})

#*******************************************************************************
#*******************************************************************************

aux_source_directory(.          POLICY_SRC)

#*******************************************************************************
#*******************************************************************************

add_library(policy ${POLICY_SRC})
target_link_libraries(policy infra
                             securec)
