# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_LIVEPATCH) += livepatch.o
obj-$(CONFIG_LIVEPATCH_PER_TASK_CONSISTENCY) += transition.o
obj-$(CONFIG_LIVEPATCH_PER_TASK_CONSISTENCY) += shadow.o
obj-$(CONFIG_LIVEPATCH_PER_TASK_CONSISTENCY) += state.o

livepatch-objs := core.o patch.o
