#*******************************************************************************
#*******************************************************************************

include_directories(${CMAKE_CURRENT_SOURCE_DIR})

#*******************************************************************************
#*******************************************************************************

aux_source_directory(.          PARSER_SRC)

#*******************************************************************************
#*******************************************************************************

add_library(parser ${PARSER_SRC})
target_link_libraries(parser infra
                          securec)
