/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (C), 2026-2026, Huawei Tech. Co., Ltd.
 * File Name     : nic_mpu_cmd_structs.h
 * Version       : Initial Draft
 * Created       : 2026/5/20
 * Last Modified : 2026/5/20
 * Description   : mailbox command structure definition file, header file is automatically generated by scripts in MAILBOX baseline table. If adding or deleting, please modify the baseline table first, then automatically generate this header file
 */

#ifndef HINIC5_NIC_CMD_STRUCTS_H
#define HINIC5_NIC_CMD_STRUCTS_H

#if defined(__LINUX__) || defined(__VMWARE__)
#include <linux/types.h>
#endif

#include "mpu_cmd_base_defs.h"

/**
 * @brief Management message head structure
 * @details This structure is used to store management message header information, including status, version and reserved fields.
 */
struct hinic5_mgmt_msg_head {
	u8 status;     /**< Status field */
	u8 version;     /**< Version field */
	u8 rsvd0[6];     /**< Reserved field */
};

/**
 * @brief struct hinic5_cmd_register_vf
 * @details nic vf register
 */
struct hinic5_cmd_register_vf {
	struct hinic5_mgmt_msg_head msg_head;     /**< Command message head */
	u8 op_register;     /**< 0 - unregister, 1 - register */
	u8 rsvd1[3];     /**< Reserved field */
	u32 support_extra_feature;     /**< support extra feature */
	u8 rsvd2[32];     /**< Reserved field */
};

/**
 * @brief Store function table configuration information
 * @details This structure contains WQE buffer size for receive queue, Maximum Transmission Unit (MTU) and reserved fields.
 */
struct hinic5_func_tbl_cfg {
	u16 rx_wqe_buf_size;     /**< Receive queue WQE buffer size */
	u16 mtu;     /**< Maximum Transmission Unit (MTU) */
	u8 rx_compact_wqe_en;     /**< rx 8Byte wqe (combined cqe) enable */
	u8 rsvd0[3];     /**< Reserved field */
	u8 mac[6];
	u16 vlan_id;
	u32 rsvd1[6];     /**< Reserved field */
};

/**
 * @brief Structure for setting function table
 * @details This structure is used for setting function table, including management message head, function ID, reserved field, configuration bitmap and function table configuration.
 */
struct hinic5_cmd_set_func_tbl {
	struct hinic5_mgmt_msg_head msg_head;     /**< Command message head */
	u16 func_id;     /**< Func ID */
	u16 rsvd;     /**< Reserved field */
	u32 cfg_bitmap;     /**< Configuration bitmap, defined by hinic5_func_tbl_cfg_bitmap */
	struct hinic5_func_tbl_cfg tbl_cfg;     /**< Configuration table */
};

/**
 * @brief Configurable func-level attributes
 * @details nic vport state info
 */
struct hinic5_vport_state {
	struct hinic5_mgmt_msg_head msg_head;     /**< Command message head */
	u16 func_id;     /**< Func ID */
	u16 rsvd1;     /**< Reserved field */
	u8 state;     /**< 0--disable, 1--enable */
	u8 num_qps;     /**< queue pairs number */
	u8 rx_compact_wqe_en;
	u8 rsvd2;     /**< Reserved field */
};

/**
 * @brief Configurable func-level attributes
 * @details nic rx_mode command structure
 */
struct hinic5_rx_mode_config {
	struct hinic5_mgmt_msg_head msg_head;     /**< Command message head */
	u16 func_id;     /**< Func ID */
	u16 rsvd1;     /**< Reserved field */
	u32 rx_mode;     /**< rx mode */
};

/**
 * @brief Configurable func-level attributes
 * @details nic set cons idx attr
 */
struct hinic5_cmd_cons_idx_attr {
	struct hinic5_mgmt_msg_head msg_head;     /**< Command message head */
	u16 func_idx;     /**< Func ID */
	u8 dma_attr_off;     /**< dma attribute offset */
	u8 pending_limit;     /**< pending limit */
	u8 coalescing_time;     /**< coalescing time */
	u8 intr_en;     /**< interrupt enable */
	u16 intr_idx;     /**< interrupt index */
	u32 l2nic_sqn;     /**< l2nic sequence number */
	u32 rsvd1;     /**< Reserved field */
	u64 ci_addr;     /**< ci address */
};

/**
 * @brief Structure for storing port statistics
 * @details This structure contains management message head and two fields for storing port statistics.
 */
struct hinic5_port_stats_info {
	struct hinic5_mgmt_msg_head msg_head;     /**< Command message head */
	u16 func_id;     /**< Func ID */
	u16 rsvd1;     /**< Reserved field */
};

/**
 * @brief Structure for storing vport statistics
 * @details Vport transmit and receive statistics, including unicast, multicast, broadcast packet count and byte count, plus sent and received discarded and error packet count.
 */
struct hinic5_vport_stats {
	u64 tx_unicast_pkts_vport;     /**< Transmitted unicast packets */
	u64 tx_unicast_bytes_vport;     /**< Transmitted unicast bytes */
	u64 tx_multicast_pkts_vport;     /**< Transmitted multicast packets */
	u64 tx_multicast_bytes_vport;     /**< Transmitted multicast bytes */
	u64 tx_broadcast_pkts_vport;     /**< Transmitted broadcast packets */
	u64 tx_broadcast_bytes_vport;     /**< Transmitted broadcast bytes */
	u64 rx_unicast_pkts_vport;     /**< Received unicast packets */
	u64 rx_unicast_bytes_vport;     /**< Received unicast bytes */
	u64 rx_multicast_pkts_vport;     /**< Received multicast packets */
	u64 rx_multicast_bytes_vport;     /**< Received multicast bytes */
	u64 rx_broadcast_pkts_vport;     /**< Received broadcast packets */
	u64 rx_broadcast_bytes_vport;     /**< Received broadcast bytes */
	u64 tx_discard_vport;     /**< Transmitted discarded packets */
	u64 rx_discard_vport;     /**< Received discarded packets */
	u64 tx_err_vport;     /**< Transmitted error packets */
	u64 rx_err_vport;     /**< Received error packets */
};

/**
 * @brief Structure for storing vport statistics information
 * @details This structure contains vport statistics data, including management message head, statistics size, reserved fields, vport statistics and additional reserved fields.
 */
struct hinic5_cmd_vport_stats {
	struct hinic5_mgmt_msg_head msg_head;     /**< Command message head */
	u32 stats_size;     /**< Statistics size */
	u32 rsvd1;     /**< Reserved field */
	struct hinic5_vport_stats stats;     /**< vport statistics */
	u64 rsvd2[6];     /**< Reserved field */
};

/**
 * @brief hinic5_cmd_clear_qp_resource
 * @details nic clear qp resource command structure
 */
struct hinic5_cmd_clear_qp_resource {
	struct hinic5_mgmt_msg_head msg_head;     /**< Command message head */
	u16 func_id;     /**< Func ID */
	u16 rsvd1;     /**< Reserved field */
};

/**
 * @brief hinic5_cmd_lro_config
 * @details nic configure lro structure
 */
struct hinic5_cmd_lro_config {
	struct hinic5_mgmt_msg_head msg_head;     /**< Command message head */
	u16 func_id;     /**< Func ID */
	u8 opcode;     /**< operation code */
	u8 rsvd1;     /**< Reserved field */
	u8 lro_ipv4_en;     /**< LRO for IPv4 */
	u8 lro_ipv6_en;     /**< LRO for IPv6 */
	u8 lro_max_pkt_len;     /**< unit is 1K */
	u8 resv2[13];     /**< Reserved field */
};

/**
 * @brief hinic5_cmd_lro_timer
 * @details nic configure lro timer
 */
struct hinic5_cmd_lro_timer {
	struct hinic5_mgmt_msg_head msg_head;     /**< Command message head */
	u8 opcode;     /**< 1: set timer value, 0: get timer value */
	u8 rsvd1;     /**< Reserved field */
	u16 rsvd2;     /**< Reserved field */
	u32 timer;     /**< timer value */
};

#define NIC_MAX_FEATURE_QWORD 4

/**
 * @brief hinic5_cmd_feature_nego
 * @details nic auto-negotiation feature command structure
 */
struct hinic5_cmd_feature_nego {
	struct hinic5_mgmt_msg_head msg_head;     /**< Command message head */
	u16 func_id;     /**< Func ID */
	u8 opcode;     /**< opeartion code 1: set, 0: get */
	u8 rsvd;     /**< Reserved field */
	u64 s_feature[NIC_MAX_FEATURE_QWORD];     /**< feature */
};

/**
 * @brief hinic5_cmd_local_lro_state
 * @details nic set lro state
 */
struct hinic5_cmd_local_lro_state {
	struct hinic5_mgmt_msg_head msg_head;     /**< Command message head */
	u16 func_id;     /**< 1: set timer value, 0: get timer value */
	u8 opcode;     /**< 0: get state, 1: set state */
	u8 state;     /**< 0: disable, 1: enable */
};

/**
 * @brief hinic5_cmd_cache_out_qp_resource
 * @details nic set cache_out_qp_resource
 */
struct hinic5_cmd_cache_out_qp_resource {
	struct hinic5_mgmt_msg_head msg_head;     /**< Command message head */
	u16 func_id;     /**< Func ID */
	u16 rsvd1;     /**< Reserved field */
};

/**
 * @brief Receive queue completion queue context structure
 * @details This structure is used to describe the context information of receive queue completion queue
 */
struct hinic5_rq_cqe_ctx {
	struct hinic5_mgmt_msg_head msg_head;     /**< Command message head */
	u8 cqe_type;     /**< Completion queue type */
	u8 rq_id;     /**< Receive queue ID */
	u8 threshold_cqe_num;     /**< Completion queue threshold */
	u8 rsvd1;     /**< Reserved field */
	u16 msix_entry_idx;     /**< MSI-X entry index */
	u16 rsvd2;     /**< Reserved field */
	u32 ci_addr_hi;     /**< Completion queue address high */
	u32 ci_addr_lo;     /**< Completion queue address low */
	u16 timer_loop;     /**< Timer loop count */
	u16 rsvd3;     /**< Reserved field */
};

struct hinic5_rq_enable {
	struct hinic5_mgmt_msg_head msg_head;     /**< Command message head */
	u32 rq_id;
	u8 rq_enable;
	u8 rsvd1[3];     /**< Reserved field */
};

#define ETH_ALEN 6     /**< Ethernet address length */

/**
 * @brief hinic5_port_mac_set
 * @details nic port mac set command structure
 */
struct hinic5_port_mac_set {
	struct hinic5_mgmt_msg_head msg_head;     /**< Command message head */
	u16 func_id;     /**< Func ID */
	u16 vlan_id;     /**< vlan id */
	u8 vf_lag_en;     /**< vf_lag enable flag (for computation, reserved) */
	u8 rsvd1;     /**< Reserved field */
	u8 mac[ETH_ALEN];     /**< mac address */
};

/**
 * @brief hinic5_port_mac_update
 * @details nic port mac update command structure
 */
struct hinic5_port_mac_update {
	struct hinic5_mgmt_msg_head msg_head;     /**< Command message head */
	u16 func_id;     /**< Func ID */
	u16 vlan_id;     /**< vlan id */
	u16 rsvd1;     /**< Reserved field */
	u8 old_mac[ETH_ALEN];     /**< mac address */
	u16 rsvd2;     /**< Reserved field */
	u8 new_mac[ETH_ALEN];     /**< mac address */
};

#define CHIP_ATTR_MAC_MAX_SIZE 192

/**
 * @brief nic_cmd_mac_info
 * @details MAC module interface
 */
struct nic_cmd_mac_info {
	struct hinic5_mgmt_msg_head head;     /**< Command message head */
	u32 valid_bitmap;     /**< valid bitmap, unused */
	u16 rsvd1;     /**< Reserved field */
	u8 host_id[32];     /**< host id, unused */
	u8 port_id[32];     /**< port id, unused */
	u8 mac_addr[CHIP_ATTR_MAC_MAX_SIZE];     /**< mac addr */
};

/**
 * @brief hinic5_cmd_vlan_config
 * @details nic configure vlan information
 */
struct hinic5_cmd_vlan_config {
	struct hinic5_mgmt_msg_head msg_head;     /**< Command message head */
	u16 func_id;     /**< Func ID */
	u8 opcode;     /**< opration code */
	u8 rsvd1;     /**< Reserved field */
	u16 vlan_id;     /**< vlan id */
	u8 blacklist_flag;     /**< Blacklist flag (for computation, reserved) */
	u8 rsvd2;     /**< Reserved field */
};

struct hinic5_cmd_vxlan_port_info {
	struct hinic5_mgmt_msg_head msg_head;   /**< Command message head */
	u16 func_id;  /**< Func ID */
	u8 opcode;  /**< opration code */
	u8 cfg_mode;  /**< Priority flag */
	u16 vxlan_port;  /**< Target port */
	u8 pkt_fmt;  /**< 0: vxlan packet  1: vxlan_gpe packet */
	u8 rsvd2;  /**< Reserved field */
};

/**
 * @brief hinic5_cmd_set_vlan_filter
 * @details nic set vlan filter
 */
struct hinic5_cmd_set_vlan_filter {
	struct hinic5_mgmt_msg_head msg_head;     /**< Command message head */
	u16 func_id;     /**< Func ID */
	u8 rsvd1[2];     /**< Reserved field */
	u32 vlan_filter_ctrl;     /**< bit0:vlan filter en; bit1:broadcast_filter_en */
};

/**
 * @brief hinic5_cmd_vlan_offload
 * @details nic set vlan offload
 */
struct hinic5_cmd_vlan_offload {
	struct hinic5_mgmt_msg_head msg_head;     /**< Command message head */
	u16 func_id;     /**< Func ID */
	u8 vlan_offload;     /**< vlan offload */
	u8 rsvd1[5];     /**< Reserved field */
};

struct hinic5_smac_check_state {
	struct hinic5_mgmt_msg_head head;     /**< Command message head */
	u8 smac_check_en;     /**< 1: enable 0: disable */
	u8 op_code;     /**< 1: set 0: get */
	u8 flash_en;     /**< Flash enable flag */
	u8 rsvd;     /**< Reserved field */
};

/**
 * @brief hinic5_cmd_vf_vlan_config
 * @details nic configure vf vlan information
 */
struct hinic5_cmd_vf_vlan_config {
	struct hinic5_mgmt_msg_head msg_head;     /**< Command message head */
	u16 func_id;     /**< Func ID */
	u8 opcode;     /**< opration code */
	u8 rsvd1;     /**< Reserved field */
	u16 vlan_id;     /**< vlan id */
	u8 qos;     /**< qos */
	u8 rsvd2[5];     /**< Reserved field */
};

/**
 * @brief hinic5_cmd_vf_trust_config
 * @details nic configure vf trust information
 */
struct hinic5_cmd_vf_trust_config {
	struct hinic5_mgmt_msg_head msg_head;     /**< Command message head */
	u16 func_id;    /**< Func ID */
	u16 vlan_id;    /**< vlan id */
	u8 trust;   /* vf_trust: 0-disable; 1-enable */
	u8 rsvd2[67];    /**< Reserved field */
};

/**
 * @brief hinic5_cmd_spoofchk_set
 * @details nic configure spoofchk
 */
struct hinic5_cmd_spoofchk_set {
	struct hinic5_mgmt_msg_head msg_head;     /**< Command message head */
	u16 func_id;     /**< Func ID */
	u8 state;     /**< state */
	u8 rsvd1;     /**< Reserved field */
};

#define NIC_RATE_DIRECT_RX_BW 0     /**< RX bandwidth rate limit */
#define NIC_RATE_DIRECT_TX_BW 1     /**< TX bandwidth rate limit */
#define NIC_RATE_DIRECT_RX_PERCENT 2     /**< RX percentage rate limit (setting command 1872 implementation differs) other parts are identical */
#define NIC_RATE_DIRECT_TX_PERCENT 3     /**< TX percentage rate limit */
#define NIC_RATE_OP_SET 0     /**< Rate limit set */
#define NIC_RATE_OP_GET 1     /**< Rate limit query */
#define NIC_RATE_OP_FLASH 2     /**< FLASH persist */
#define NIC_RATE_OP_UNUSE 4     /**< For compatibility adaptation, for 1823 (since this field won't be read, it will actually perform rate limit configuration), 1872/1825 and later generations actually do nothing and return directly */

/**
 * @brief hinic5_cmd_rate_cfg
 * @details nic rate configuration
 */
struct hinic5_cmd_rate_cfg {
	struct hinic5_mgmt_msg_head msg_head;     /**< Command message head */
	u16 func_id;     /**< Func ID */
	u8 cfg_mode;     /* BIT[0]: set and query, 0-set, 1-query;
			  * BIT[1]: whether to support persist to Flash Currently only supports percentage rate limit persisting;
			  * BIT[2]: if 1 means do nothing and return directly
			  */
	u8 direct;     /* Direction: 0-RX bandwidth limit 1-TX bandwidth limit 2-RX_RATE percentage 3-TX_RATE percentage */
	u32 cir;     /**< C bucket rate Mbps old field name min_rate */
	u32 pir;     /* P bucket rate Mbps if bandwidth limit, represents C bucket rate (Mbps),
		      * if direct is percentage limit, represents percentage, old field name max_rate
		      */
	u32 cbs;     /**< C bucket depth Mbit 0 uses default bucket depth */
	u32 pbs;     /**< P bucket depth Mbit 0 uses default bucket depth */
};

#define NIC_RATE_MODE_PERCENT 0     /**< Effective as percentage rate limit. */
#define NIC_RATE_MODE_BANDWIDTH 1     /**< Effective as bandwidth rate limit. */

/**
 * @brief hinic5_cmd_rate_cfg_ret
 * @details nic rate configuration query
 */
struct hinic5_cmd_rate_cfg_ret {
	struct hinic5_mgmt_msg_head msg_head;     /**< Command message head */
	u16 car_id;     /**< RX direction rate limit needs to return CAR_ID */
	u8 rate_mode;     /**< Current rate limit mode: 0-percentage rate limit 1-bandwidth rate limit */
	u8 rsvd;     /**< Reserved field */
	u32 cir;     /**< C bucket rate Mbps old field name min_rate */
	u32 pir;     /* P bucket rate Mbps if bandwidth limit, represents C bucket rate (Mbps),
		      * if direct is percentage limit, represents percentage, old field name max_rate
		      */
	u32 cbs;     /**< C bucket depth Mbit 0 uses default bucket depth */
	u32 pbs;     /**< P bucket depth Mbit 0 uses default bucket depth */
};

#define NIC_DCB_COS_MAX 0x8     /**< Define maximum priority (COS) for NIC DCB */

/**
 * @brief Structure for RSS configuration
 * @details This structure contains various parameters needed for RSS configuration, such as function ID, RSS enable flag, priority queue number, priority to traffic class mapping, queue pair number, etc.
 */
struct hinic5_cmd_rss_config {
	struct hinic5_mgmt_msg_head msg_head;     /**< Command message head */
	u16 func_id;     /**< Function ID, used to identify which function's RSS is being configured */
	u8 rss_en;     /* RSS enable flag, if 1 means RSS function is enabled, 0 means disabled */
	u8 rq_priority_number;     /* Number of priority queues, which determines the specific implementation of RSS */
	u8 prio_tc[NIC_DCB_COS_MAX];     /* Mapping between priority and traffic class, array length is NIC_DCB_COS_MAX */
	u16 num_qps;     /**< Number of queue pairs, which determines the specific implementation of RSS */
	u16 rsvd1;     /**< Reserved field */
};

/**
 * @brief RSS (Receive Side Scaling) template management structure
 * @details This structure is used for managing RSS templates, including management message head, function ID, command, template ID, etc.
 */
struct hinic5_rss_template_mgmt {
	struct hinic5_mgmt_msg_head msg_head;     /**< Command message head */
	u16 func_id;     /**< Function ID, used to identify the function module corresponding to the current message */
	u8 cmd;     /**< Command, used to identify the operation to be executed */
	u8 template_id;     /**< Template ID, used to identify the template corresponding to the current operation */
	u8 rsvd1[4];     /**< Reserved field */
};

/**
 * @brief RSS (Receive Side Scaling) context table structure
 * @details This structure contains RSS context table data, including management message head, func id, context information, and reserved fields.
 */
struct hinic5_rss_context_table {
	struct hinic5_mgmt_msg_head msg_head;     /**< Command message head */
	u16 func_id;     /**< Function ID, used to identify the function module corresponding to the current message */
	u16 rsvd1;     /**< Reserved field */
	u32 context;     /**< RSS context */
};

#define NIC_RSS_KEY_SIZE 40     /**< Define RSS key size as 40 */

/**
 * @brief Structure for RSS hash key
 * @details This structure is used to store RSS hash key related information
 */
struct hinic5_cmd_rss_hash_key {
	struct hinic5_mgmt_msg_head msg_head;     /**< Command message head */
	u16 func_id;     /**< Function ID */
	u8 opcode;     /**< Operation code */
	u8 rsvd1;     /**< Reserved field */
	u8 key[NIC_RSS_KEY_SIZE];     /**< RSS hash key */
};

/**
 * @brief Structure for RSS engine type
 * @details This structure is used to describe RSS engine type related information
 */
struct hinic5_cmd_rss_engine_type {
	struct hinic5_mgmt_msg_head msg_head;     /**< Command message head */
	u16 func_id;     /**< Function ID */
	u8 opcode;     /**< Operation code */
	u8 hash_engine;     /**< Hash engine */
	u8 rsvd1[4];     /**< Reserved field */
};

/**
 * @brief hinic5_ipcs_err_rss_enable_operation_s
 * @details IP checksum error packets, enable rss quadruple hash
 */
struct hinic5_ipcs_err_rss_enable_operation_s {
	struct hinic5_mgmt_msg_head head;     /**< Command message head */
	u8 en_tag;
	u8 type;     /**< 1: set  0: get */
	u8 rsvd[2];     /**< Reserved field */
};

/**
 * @brief Network interface command filter delete rule structure
 * @details This structure is used to store network interface command filter delete rule related information.
 */
struct nic_cmd_fdir_del_rules {
	struct hinic5_mgmt_msg_head head;     /**< Command message head */
	u16 func_id;     /**< Function ID */
	u8 type;     /**< Type */
	u8 rsvusrdata;     /**< User data */
	u32 index_start;     /**< Index start position */
	u32 index_num;     /**< Index count */
};

/**
 * @brief Structure for flushing TCAM rules
 * @details This structure contains management message head and function ID two members, used for flushing TCAM rules.
 */
struct nic_cmd_flush_tcam_rules {
	struct hinic5_mgmt_msg_head head;     /**< Command message head */
	u16 func_id;     /**< Function ID */
	u16 rsvd;     /**< Reserved field */
};

/**
 * @brief Input structure for allocating TCAM block
 * @details This structure is used for TCAM block allocation input parameters, including head information, function ID, allocation flag, TCAM type, TCAM block index, and allocation block count, etc.
 */
struct nic_cmd_ctrl_tcam_block_in {
	struct hinic5_mgmt_msg_head head;     /**< Command message head */
	u16 func_id;     /**< Function ID */
	u8 alloc_en;     /**< 0: Free allocated tcam block, 1: Allocate new tcam block */
	u8 tcam_type;     /* 0: Allocate 16 size tcam block,
			   * 1: Allocate 0 size tcam block, others reserved
			   */
	u16 tcam_block_index;     /**< index */
	u16 alloc_block_num;     /* Driver sends to uP indicating the block size driver wants to allocate
				  * uP returns to driver interface, indicating the tcam block size uP supports allocating
				  */
};

/**
 * @brief Output structure for allocating TCAM block
 * @details This structure is used to store allocation TCAM block output information.
 */
struct nic_cmd_ctrl_tcam_block_out {
	struct hinic5_mgmt_msg_head head;     /**< Command message head */
	u16 func_id;     /**< Function ID */
	u8 alloc_en;     /**< 0: Free allocated tcam block, 1: Allocate new tcam block */
	u8 tcam_type;     /* 0: Allocate 16 size tcam block,
			   * 1: Allocate 0 size tcam block, others reserved
			   */
	u16 tcam_block_index;     /**< index */
	u16 mpu_alloc_block_size;     /* Driver sends to uP indicating the block size driver wants to allocate,
				       * uP returns to driver interface, indicating the tcam block size uP supports allocating
				       */
};

/**
 * @brief nic_cmd_set_tcam_enable
 * @details enable tcam
 */
struct nic_cmd_set_tcam_enable {
	struct hinic5_mgmt_msg_head head;     /**< Command message head */
	u16 func_id;     /**< Function ID */
	u8 tcam_enable;     /**< tcam enable */
	u8 rsvd1;     /**< Reserved field */
	u32 rsvd2;     /**< Reserved field */
};

/**
 * @brief Input structure for allocating TCAM block
 * @details This structure is used for TCAM block allocation input parameters, including head information, function ID, allocation flag, TCAM type, TCAM block index and allocation block count, etc.
 */
struct nic_cmd_dfx_fdir_tcam_block_table {
	struct hinic5_mgmt_msg_head head;     /**< Command message head */
	u8 tcam_type;     /**< TCAM type */
	u8 valid;     /**< Valid flag */
	u16 tcam_block_index;     /**< TCAM block index */
	u16 use_function_id;     /**< Used function ID */
	u16 rsvd;     /**< Reserved field */
};

struct hinic5_ppa_cfg_table_id_cmd {
	struct hinic5_mgmt_msg_head msg_head;     /**< Command message head */
	u16 rsvd0;     /**< Reserved field */
	u16 cmd;     /**< command */
	u16 table_id;     /**< table id */
	u16 rsvd1;     /**< Reserved field */
};

struct hinic5_ppa_cfg_ppa_en_cmd {
	struct hinic5_mgmt_msg_head msg_head;     /**< Command message head */
	u16 func_id;     /**< function id */
	u8 ppa_en;     /**< ppa enable */
	u8 rsvd;     /**< Reserved field */
};

struct hinic5_ppa_cfg_mode_cmd {
	struct hinic5_mgmt_msg_head msg_head;     /**< Command message head */
	u16 rsvd0;     /**< function id */
	u8 ppa_mode;     /**< ppa mode */
	u8 qpc_func_nums;     /**< qpc function numbers */
	u16 base_qpc_func_id;     /**< base qpc function id */
	u16 rsvd1;     /**< Reserved field */
};

struct hinic5_ppa_flush_en_cmd {
	struct hinic5_mgmt_msg_head msg_head;     /**< Command message head */
	u16 rsvd0;     /**< Reserved field */
	u8 flush_en;     /**< 0 flush done, 1 in flush operation */
	u8 rsvd1;     /**< Reserved field */
};

struct nic_cmd_set_fdir_status {
	struct hinic5_mgmt_msg_head head;     /**< Command message head */
	u16 func_id;     /**< function id */
	u16 index;     /**< index */
	u8 pkt_type_en;     /**< packet type enable */
	u8 pkt_type;     /**< packet type */
	u8 qid;     /**< queue id */
	u8 flag;     /**< packet drop flag */
};

struct hinic5_ppa_fdir_query_cmd {
	struct hinic5_mgmt_msg_head msg_head;     /**< Command message head */
	u32 index;     /**< index */
	u32 rsvd;     /**< Reserved field */
	u64 pkt_nums;     /**< packet type */
	u64 pkt_bytes;     /**< packet bytes */
};

struct hinic5_port_state {
	struct hinic5_mgmt_msg_head msg_head;     /**< Command message head */
	u16 func_id;     /**< function id */
	u16 rsvd1;     /**< Reserved field */
	u8 state;     /**< 0--disable, 1--enable */
	u8 rsvd2[3];     /**< Reserved field */
};

struct hinic5_cmd_pause_config {
	struct hinic5_mgmt_msg_head msg_head;     /**< Command message head */
	u8 port_id;     /**< port id */
	u8 opcode;     /**< operation code */
	u16 rsvd1;     /**< Reserved field */
	u8 auto_neg;     /**< auto negotiation */
	u8 rx_pause;     /**< receive pause */
	u8 tx_pause;     /**< send pause */
	u8 rsvd2[5];     /**< Reserved field */
};

struct hinic5_port_car_info {
	u32 cir;     /**< unit: kbps, range:[1,400*1000*1000], i.e. 1Kbps~400Gbps(400M*kbps) */
	u32 xir;     /**< unit: kbps, range:[1,400*1000*1000], i.e. 1Kbps~400Gbps(400M*kbps) */
	u32 cbs;     /**< unit: Byte, range:[1,320*1000*1000], i.e. 1byte~2560Mbit */
	u32 xbs;     /**< unit: Byte, range:[1,320*1000*1000], i.e. 1byte~2560Mbit */
};

/**
 * @brief hinic5_cmd_set_port_car
 * @details nic set car rate limit command structure (1825)
 */
struct hinic5_cmd_set_port_car {
	struct hinic5_mgmt_msg_head msg_head;     /**< Command message head */
	u8 port_id;     /**< port id */
	u8 opcode;     /**< 0--set car profile, 1--set car state, 2--get car profile */
	u8 state;     /**< 0--disable, 1--enable */
	u8 level;     /**< limit level */
	struct hinic5_port_car_info car;     /**< car info */
};

struct hinic5_cmd_set_car_option {
	u8 type;     /**< 0:port, 1:func, 2:vnic group*/
	u8 port_id;
	u16 func_id;
	u8 car_enable;
	u8 opcode;     /**< 0--set car profile, 1--get car profile */
	u8 pkt_type;
	u8 car_alg_type;
};

/**
 * @brief hinic5_cmd_set_car
 * @details nic set car rate limit command structure (1872)
 */
struct hinic5_cmd_set_car {
	struct hinic5_mgmt_msg_head msg_head;     /**< Command message head */
	struct hinic5_cmd_set_car_option option;
	struct hinic5_port_car_info car;     /**< car info */
};

/**
 * @brief hinic5_car_profile
 * @details nic set car rate limit command structure (1872)
 */
struct hinic5_car_profile {
	struct hinic5_mgmt_msg_head msg_head;     /**< Command message head */
	u16 car_id;     /**< car id */
	u8 level;     /**< limit level */
	u8 rsvd;     /**< Reserved field */
	u32 profile[4];     /**< car profile */
};

#define NIC_DCB_TC_MAX 0x8     /**< Maximum traffic class (TC) for NIC DCB */

/**
 * @brief hinic5_cmd_ets_cfg
 * @details nic configure ets command structure
 */
struct hinic5_cmd_ets_cfg {
	struct hinic5_mgmt_msg_head head;     /**< Command message head */
	u8 port_id;     /**< port id */
	u8 op_code;     /**< 1 - set, 0 - get */
	u8 cfg_bitmap;     /* bit0 - cos_tc, bit1 - tc_bw, bit2 - cos_prio,
			    * bit3 - cos_bw, bit4 - tc_prio
			    */
	u8 rsvd;     /**< Reserved field */
	u8 cos_tc[NIC_DCB_COS_MAX];
	u8 tc_bw[NIC_DCB_TC_MAX];
	u8 cos_prio[NIC_DCB_COS_MAX];     /**< 0 - DWRR, 1 - STRICT */
	u8 cos_bw[NIC_DCB_COS_MAX];
	u8 tc_prio[NIC_DCB_TC_MAX];     /**< 0 - DWRR, 1 - STRICT */
};

struct hinic5_cmd_set_pfc {
	struct hinic5_mgmt_msg_head head;     /**< Command message head */
	u8 port_id;     /**< port id */
	u8 op_code;     /**< 0：get 1: set pfc_en  2: set pfc_bitmap 3: set all */
	u8 pfc_en;     /**< pfc_en and pfc_bitmap must be set simultaneously */
	u8 pfc_bitmap;     /**< pfc bitmap */
	u8 rsvd[4];     /**< Reserved field */
};

/**
 * @brief hinic5_cmd_set_dcb_state
 * @details nic set dcb state command structure
 */
struct hinic5_cmd_set_dcb_state {
	struct hinic5_mgmt_msg_head head;     /**< Command message head */
	u16 func_id;     /**< port id */
	u8 op_code;     /**< 0 - get dcb state, 1 - set dcb state */
	u8 state;     /**< 0 - disable, 1 - enable dcb */
	u8 port_state;     /**< 0 - disable, 1 - enable dcb */
	u8 rsvd[7];     /**< Reserved field */
};

struct hinic5_cmd_qos_port_cfg {
	struct hinic5_mgmt_msg_head head;     /**< Command message head */
	u8 port_id;     /**< port id */
	u8 op_code;     /**< 0 - get, 1 - set */
	u8 cfg_bitmap;     /**< bit0 - trust, bit1 - dft_cos */
	u8 rsvd0;     /**< Reserved field */
	u8 trust;     /**< trust state */
	u8 dft_cos;     /**< dft cos */
	u8 rsvd1[18];     /**< Reserved field */
};

struct hinic5_cmd_qos_map_cfg {
	struct hinic5_mgmt_msg_head head;     /**< Command message head */
	u8 op_code;     /**< operation code */
	u8 cfg_bitmap;     /**< bit0 - pcp2cos, bit1 - dscp2cos */
	u16 rsvd0;     /**< Reserved field */
	u8 pcp2cos[8];     /**< Must configure all 8 together */
	u8 dscp2cos[64];     /* When configuring dscp2cos, if cos value is set to 0xFF, MPU will ignore this dscp priority configuration
			      * Allows configuring multiple dscp to cos mappings at once
			      */
	u32 rsvd1[4];     /**< Reserved field */
};

/**
 * @brief hinic5_cmd_qos_extend_cfg
 * @details nic configure qos command extended structure
 */
struct hinic5_cmd_qos_extend_cfg {
	struct hinic5_mgmt_msg_head head;     /**< Command message head */
	u8 port_id;     /**< port id */
	u8 op_code;     /**< bit0: 1-set tc rate limit, 0-get tc rate limit */
	u16 rsvd0;     /**< Reserved field */
	u16 port_speed;     /**< Port speed, unit Gbps */
	u16 rsvd1;     /**< Reserved field */
	u32 rate_limit[NIC_DCB_COS_MAX];     /**< TC rate limit value, unit Mbps */
	u32 port_cir; /**< Port cir value, unit Mbps  */
	u32 rsvd2[115];     /**< Reserved field */
};

/**
 * @brief hinic5_force_pkt_drop
 * @details nic force pkt drop command structure
 */
struct hinic5_force_pkt_drop {
	struct hinic5_mgmt_msg_head msg_head;     /**< Command message head */
	u8 port;     /**< port id */
	u8 rsvd1[3];     /**< Reserved field */
};

/**
 * @brief nic_cmd_pause_inquiry_cfg
 * @details pfc storm detection configuration
 */
struct nic_cmd_pause_inquiry_cfg {
	struct hinic5_mgmt_msg_head head;     /**< Command message head */
	u32 valid;     /**< valid */
	u32 type;     /**< 1: set, 2: get */
	u32 rx_inquiry_pause_drop_pkts_en;     /**< rx drop packet enable */
	u32 rx_inquiry_pause_period_ms;     /**< rx pause detection period default 200ms */
	u32 rx_inquiry_pause_times;     /**< rx pause detection times default 1 */
	u32 rx_inquiry_pause_frame_thd;     /* rx pause detection threshold
					     * default PAUSE_FRAME_THD_10G/25G/40G/100
					     */
	u32 rx_inquiry_tx_total_pkts;     /**< rx pause detection tx packet total */
	u32 tx_inquiry_pause_en;     /**< tx pause detection enable */
	u32 tx_inquiry_pause_period_ms;     /**< tx pause detection period default 200ms */
	u32 tx_inquiry_pause_times;     /**< tx pause detection times default 5 */
	u32 tx_inquiry_pause_frame_thd;     /**< tx pause detection threshold */
	u32 tx_inquiry_rx_total_pkts;     /**< tx pause detection rx packet total */
	u32 rsvd[4];     /**< Reserved field */
};

struct nic_bios_cfg {
	u32 signature;     /**< Signature, used to verify FLASH content validity */
	u8 pxe_en;     /**< PXE enable: 0 - disable 1 - enable */
	u8 extend_mode;
	u8 rsvd0[2];     /**< Reserved field */
	u8 pxe_vlan_en;     /**< PXE VLAN enable: 0 - disable 1 - enable */
	u8 pxe_vlan_pri;     /**< PXE VLAN priority: 0-7 */
	u16 pxe_vlan_id;     /**< PXE VLAN ID 1-4094 */
	u32 service_mode;     /**< Reference CHIPIF_SERVICE_MODE_x macro */
	u32 pf_bw;     /**< PF rate, percentage 0-100 */
	u8 speed;     /**< enum of port speed */
	u8 auto_neg;     /**< Auto-negotiation switch 0 - field invalid 1 - on 2 - off */
	u8 lanes;     /**< lane num */
	u8 fec;     /**< FEC mode, reference enum mag_cmd_port_fec */
	u8 auto_adapt;     /**< Auto-adapt mode configuration 0 - invalid config 1 - on 2 - off */
	u8 func_valid;     /**< Indicates whether func_id is valid; 0 - invalid, other - valid */
	u8 func_id;     /**< This member is meaningful only when func_valid is not 0 */
	u8 sriov_en;     /**< SRIOV-EN: 0 - invalid config, 1 - on, 2 - off */
};

struct nic_cmd_bios_cfg {
	struct hinic5_mgmt_msg_head head;     /**< Command message head */
	u32 op_code;     /**< Operation Code: Bit0[0: read 1:write, BIT1-6: cfg_mask */
	struct nic_bios_cfg bios_cfg;     /**< BIOS configuration */
};

/**
 * @brief Structure for storing semi-offload bond func link status information
 * @details Semi-offload bond create/update/delete will send link messages to non-slave funcs
 */
struct hinic5_bond_link_info {
	struct hinic5_mgmt_msg_head head;     /**< Management message head information */
	u8 bond_en;     /**< Bond enable status 0:disable 1:enable */
	u8 port_id;     /**< port id */
	u8 link_status;     /**< Bond non-slave device link status 0:down 1:up */
	u8 rsvd[13];     /**< Reserved field */
};

/**
 * @brief Internal parse information structure when PN threshold exceeded interrupt occurs
 * @details Contains threshold, SC index, AN and other information
 */
struct macsec_pn_expired_report_info {
	u64 sci[32];     /**< SCI of SC corresponding to threshold exceeded event */
	u8 an[32];     /**< AN number of SA corresponding to threshold exceeded event */
	u8 pn_expired_size;     /**< SA threshold */
	u8 reserved[7];     /**< Reserved field */
};

/**
 * @brief MACsec PN threshold report message structure
 * @details When PN threshold exceeded interrupt occurs, report message structure to driver
 */
struct macsec_pn_expired_report_cmd {
	struct hinic5_mgmt_msg_head head;     /**< Management message head information */
	struct macsec_pn_expired_report_info info;     /**< Threshold exceeded related structure information */
	u64 reserved;     /**< Reserved field */
};

/**
 * @brief Structure for deleting bond
 * @details This structure contains all information needed for deleting bond
 */
struct hinic5_cmd_delete_bond {
	struct hinic5_mgmt_msg_head head;     /**< Command message head */
	u32 bond_id;     /**< Bond ID */
	u32 rsvd[2];     /**< Reserved field */
};

/**
 * @brief Structure for storing bond device open/close information
 * @details This structure contains bond device open/close information, including bond device number, open/close flag, and reserved fields.
 */
struct hinic5_open_close_bond_info {
	u32 bond_id;     /**< Bond device number */
	u32 open_close_flag;     /**< Open/close bond flag: 1 is open, 0 is close */
	u32 rsvd[2];     /**< Reserved field */
};

/**
 * @brief Structure for storing MPU bond message interface related information
 * @details This structure contains management message head information and MPU bond open or close related information
 */
struct hinic5_cmd_open_close_bond {
	struct hinic5_mgmt_msg_head head;     /**< Command message head */
	struct hinic5_open_close_bond_info open_close_bond_info;     /* Store MPU bond open or close
								      * related information
								      */
};

/**
 * @brief LACPDU port related fields
 * @details This structure is used to describe port related parameters in LACPDU (Link Aggregation Control Protocol Data Unit).
 */
struct lacp_port_params {
	u16 port_number;     /**< Port number */
	u16 port_priority;     /**< Port priority */
	u16 key;     /**< Key */
	u16 system_priority;     /**< System priority */
	u8 system[ETH_ALEN];     /**< System MAC address */
	u8 port_state;     /**< Port state */
	u8 rsvd;     /**< Reserved field */
};

/**
 * @brief Structure for storing LACP (Link Aggregation Control Protocol) port information
 * @details This structure contains multiple members, each with its specific meaning and purpose.
 */
struct lacp_port_info {
	u32 selected;     /**< Indicates whether this port is selected */
	u32 aggregator_port_id;     /**< Used aggregator port ID */
	struct lacp_port_params actor;     /**< Actor port parameters */
	struct lacp_port_params partner;     /**< Partner port parameters */
	u64 tx_lacp_pkts;     /**< Transmitted LACP packets count */
	u64 rx_lacp_pkts;     /**< Received LACP packets count */
	u64 rx_8023ad_drop;     /**< Dropped 802.3ad packets count */
	u64 tx_8023ad_drop;     /**< Transmitted 802.3ad packets count */
	u64 unknown_pkt_drop;     /**< Dropped unknown packets count */
	u64 rx_marker_pkts;     /**< Received marker packets count */
	u64 tx_marker_pkts;     /**< Transmitted marker packets count */
};

#define BOND_MAX_PORT_NUM 4     /**< Bond supports maximum port number */
#define BOND_MAX_HOST_NUM 4     /**< Bond supports maximum host number */

/**
 * @brief Structure for storing bond status information
 * @details This structure contains various bond status information, such as bond_id, link status, slave port status, port count, etc., and also contains lacp information for each port, and the count of times each host successfully and failed to report lacp negotiation results, etc.
 */
struct hinic5_bond_status_info {
	struct hinic5_mgmt_msg_head head;     /**< Command message head */
	u32 bond_id;     /**< Bond id */
	u32 bon_mmi_status;     /**< This bond sub-device link status */
	u32 active_bitmap;     /**< This bond sub-device slave port status */
	u32 port_count;     /**< This bond sub-device count */
	struct lacp_port_info port_info[BOND_MAX_PORT_NUM];     /**< Each port lacp information */
	u64 success_report_cnt[BOND_MAX_HOST_NUM];     /* Count of times each host successfully reported lacp negotiation result */
	u64 fail_report_cnt[BOND_MAX_HOST_NUM];     /* Count of times each host failed to report lacp negotiation result */
	u64 poll_timeout;     /**< Poll timeout */
	u64 fast_periodic_timeout;     /**< Fast periodic timeout */
	u64 slow_periodic_timeout;     /**< Slow periodic timeout */
	u64 short_timeout;     /**< Short timeout */
	u64 long_timeout;     /**< Long timeout */
	u64 aggregate_wait_timeout;     /**< Aggregate wait timeout */
	u64 tx_period_timeout;     /**< Transmit period timeout */
	u64 rx_marker_timer;     /**< RX marker timer */
	u8 bond_mode;     /**< Bond mode */
	u8 arp_dual_en;     /**< ARP dual transmit enable flag */
	u8 rsvd[6];     /**< Reserved field */
};

/**
 * @brief Structure for storing bond active report information
 * @details This structure contains bond active report related information, such as management message head information, bond device ID, bond sub-device link status, bond sub-device slave port status, etc.
 */
struct hinic5_bond_active_report_info {
	struct hinic5_mgmt_msg_head head;     /**< Command message head */
	u32 bond_id;     /**< Bond ID */
	u32 bon_mmi_status;     /**< Bond sub-device link status */
	u32 active_bitmap;     /**< Bond sub-device slave port status */
	u8 rsvd[16];     /**< Reserved field */
};

#define DFX_SM_TBL_BUF_MAX 768     /**< Define DFX allocated SM table maximum as 768B */
#define MAC_TBL_RD_TYPE_MAC_INFO 0     /**< Identifier for getting MAC table content data type */
#define MAC_TBL_RD_TYPE_MAC_RES_STAT 1     /**< Identifier for getting MAC resource statistics data type */

/**
 * @brief MAC table parameters
 * @details This structure is used to store MAC table parameters, including tbl_index, cnt and total_cnt.
 */
struct mac_table_arg {
	u32 tbl_index;     /**< MAC table index */
	u32 cnt;     /**< Count */
	u32 total_cnt;     /**< Total count */
	u8 mac_tbl_rd_type;     /**< 0-Read MAC content, 1-Read MAC table resource statistics */
	u8 rsvd[3];     /**< Reserved field */
};

/**
 * @brief VLAN circuit table parameters
 * @details This structure is used to store VLAN circuit table parameters, including er_id and vlan_id.
 */
struct vlan_elb_table_arg {
	u32 er_id;     /**< er ID */
	u32 vlan_id;     /**< VLAN ID */
};

/**
 * @brief VLAN filter parameters (VLAN Filter1 Table)
 * @details This structure is used to store VLAN filter parameters, including tbl_index and func_id.
 */
struct vlan_filter_arg {
	u32 tbl_index;     /**< VLAN Filter1 table index */
	u32 func_id;     /**< Function ID */
};

/**
 * @brief VLAN filter parameters (VLAN Filter2 Table)
 * @details This structure is used to store VLAN filter parameters, including vlan_id.
 */
struct vlan_filter2_arg {
	u32 vlan_id;     /**< VLAN ID */
};

/**
 * @brief Multicast circuit table parameters
 * @details This structure is used to store multicast circuit table parameters, including mc_id.
 */
struct mc_elb_arg {
	u32 mc_id;     /**< Multicast ID */
};

/**
 * @brief Function table parameters
 * @details This structure is used to store function table parameters, including func_id.
 */
struct func_tbl_arg {
	u32 func_id;     /**< Function ID */
};

/**
 * @brief Port table parameters
 * @details This structure is used to store port table parameters, including port_id.
 */
struct port_tbl_arg {
	u32 port_id;     /**< Port ID */
};

/**
 * @brief This structure is used to store FDIR IO table parameters, including tbl_index, cnt and total_cnt.
 * @details This structure is used to store port table parameters, including port_id.
 */
struct fdir_io_table_arg {
	u32 tbl_index;     /**< FDIR IO table index */
	u32 cnt;     /**< Count */
	u32 total_cnt;     /**< Total count */
};

/**
 * @brief FlexQ table parameters
 * @details This structure is used to store FlexQ table parameters, including tbl_index, cnt, total_cnt, left_cnt_die0 and left_cnt_die1.
 */
struct flexq_table_arg {
	u32 tbl_index;     /**< FlexQ table index */
	u32 cnt;     /**< Count */
	u32 total_cnt;     /**< Total count */
	u16 left_cnt_die0;     /**< Remaining count DIE0 */
	u16 left_cnt_die1;     /**< Remaining count DIE1 */
};

/**
 * @brief Define a union for storing various types of parameters
 * @details This union contains multiple structures, each representing a different parameter type. These parameter types include MAC table parameters, VLAN circuit table parameters, VLAN filter parameters, multicast circuit table parameters, function table parameters, port table parameters, FDIR IO table parameters, and FlexQ table parameters. Each parameter type has its specific member variables, such as tbl_index, cnt, total_cnt, etc.
 */
typedef union {
	struct mac_table_arg mac_table_arg;
	struct vlan_elb_table_arg vlan_elb_table_arg;
	struct vlan_filter_arg vlan_filter_arg;
	struct vlan_filter2_arg vlan_filter2_arg;
	struct mc_elb_arg mc_elb_arg;
	struct func_tbl_arg func_tbl_arg;
	struct port_tbl_arg port_tbl_arg;
	struct fdir_io_table_arg fdir_io_table_arg;
	struct flexq_table_arg flexq_table_arg;
	u32 args[4];     /**< Parameter array */
} sm_tbl_args;

/**
 * @brief Network interface controller command data analysis table structure
 * @details This structure is used to store network interface controller command data analysis table related information
 */
struct nic_cmd_dfx_sm_table {
	struct hinic5_mgmt_msg_head msg_head;     /**< Command message head */
	u32 tbl_type;     /**< Table type, used to identify table purpose */
	sm_tbl_args args;     /**< Table parameters, used to pass table related parameters */
	u8 tbl_buf[DFX_SM_TBL_BUF_MAX];     /**< Table buffer, used to store table data */
};

#define MAC_TBL_UC_CNT_FUNC_RD_NUM 256     /**< Single command reads maximum 256 Function unicast statistics */

/**
 * @brief MAC table entry shared data resource structure (used to convert nic_cmd_dfx_sm_table structure tbl_buf data)
 * @details This structure is used to store unicast, multicast, shared resource, unicast exclusive resource usage
 */
typedef struct nic_cmd_dfx_mac_res_stats_info {
	u16 uc_mac_cnt;                                     /**< Unicast table resource usage statistics */
	u16 mc_mac_cnt;                                     /**< Multicast table resource usage statistics */
	u16 share_mac_res_cur_cnt;                          /* Current shared resource pool usage statistics */
	u16 share_mac_res_total;                            /**< Shared resource pool total size */
	u16 func_uc_mac_cnt[MAC_TBL_UC_CNT_FUNC_RD_NUM];    /* Func granularity unicast table resource usage statistics */
	u8 rsvd[248];                                       /**< Reserved field */
} nic_cmd_dfx_mac_res_stats_info_s;

/**
 * @brief mpu_lt_info
 * @details nic liner table info
 */
struct mpu_lt_info {
	u8 node;     /**< node id */
	u8 inst;     /**< instance id */
	u8 entry_size;     /**< entry size */
	u8 sml_table_id;     /**< sml table id */
	u32 lt_index;     /**< liner table index */
	u32 offset;     /**< offset */
	u32 len;     /**< length */
};

struct nic_mpu_lt_opera {
	struct hinic5_mgmt_msg_head msg_head;     /**< Command message head */
	struct mpu_lt_info net_lt_cmd;
	u8 data[100];     /**< data */
};

struct hinic5_veb_set {
	struct hinic5_mgmt_msg_head msg_head;   /**< Command message head */

	u16 opcode;      /**< Operation type: 0=query, 1=configure */
	u16 set_status;  /**< Configuration request value: 0=off, 1=on */
	u16 cur_status;  /**< Current status: 0=off, 1=on, 2=error */
	u16 rsvd0;       /**< Reserved field */
	u32 rsvd[30];    /**< Reserved field */
};

/**
 * @brief nic_cmd_capture_info
 * @details ucode capture cfg info
 */
struct nic_cmd_capture_info {
	struct hinic5_mgmt_msg_head msg_head;     /**< Command message head */
	u32 op_type;     /**< operation type */
	u32 func_port;     /**< function port */
	u32 is_en_trx;     /**< Also used as tx_rx */
	u32 offset_cos;     /**< Also used as cos */
	u32 data_vlan;     /**< Also used as vlan */
};

struct nic_cmd_vhd_config {
	struct hinic5_mgmt_msg_head head;     /**< Command message head */
	u16 func_id;     /**< function id */
	u8 vhd_type;     /**< vhd type */
	u8 virtio_small_enable;     /**< 0: mergeable mode, 1: small mode */
};

#define TC_ACL_KEY_BYTE 44     /**< 320 bits + 2 byte pad align to 4 byte */

/**
 * @brief struct hinic5_tc_action_info
 * @details info about tc action
 */
struct hinic5_tc_action_info {
	u16 action_flag;     /**< action flag */
	u16 output;     /**< output */
	u8 flow_queue;     /**< flow queue */
	u8 vxlan_tbl_index;     /**< vxlan table index */
	u16 vlan_tag;     /**< vlan tag */
	u32 flow_mark;     /**< flow mark */
	u16 vlan_sel;     /**< type of vlan frame */
	u16 count_id;     /**< count id */
};

/**
 * @brief struct hinic5_tc_cfg_info
 * @details info about add/del tc flower rule
 */
struct hinic5_tc_cfg_info {
	struct hinic5_mgmt_msg_head head;     /**< Command message head */
	u8 key_tcam_mem[TC_ACL_KEY_BYTE];     /**< tcam key mem */
	u8 mask_tcam_mem[TC_ACL_KEY_BYTE];     /**< tcam mask mem */
	struct hinic5_tc_action_info action;     /**< action info */
	u16 opcode;     /**< 0:del, 1:add */
	u16 index;     /**< index id */
	u8 group_vld;     /**< tcam group vld */
	u8 group_id;     /**< tcam group id */
	u16 rsvd;     /**< Reserved field */
};

#define ACL_LCAM_BITMAP_LEN 32     /**< 320 bits + 2 byte pad align to 4 byte */

/**
 * @brief struct hinic5_tc_flush_info
 * @details info about add/del tc flower rule
 */
struct hinic5_tc_flush_info {
	struct hinic5_mgmt_msg_head head;     /**< Command message head */
	u64 active_bitmap[ACL_LCAM_BITMAP_LEN];     /**< active bitmap */
};

/**
 * @brief struct hinic5_tc_vxlan_hdr_info
 * @details info about tc vxlan header
 */
struct hinic5_tc_vxlan_hdr_info {
	u8 dmac[6];     /**< destination mac */
	u8 smac[6];     /**< source mac */
	u16 vlan;     /**< vlan tag */
	u8 tos;     /**< type of service */
	u8 rsvd0;     /**< Reserved field */
	u8 sip[4];     /**< source ip */
	u8 dip[4];     /**< destination ip */
	u16 sport;     /**< source port */
	u16 rsvd1;     /**< Reserved field */
	u32 vni;     /**< bit[0:23]: vni, bit[24:31]: rsvd */
};

/**
 * @brief struct hinic5_tc_vxlan_tbl_cfg_info
 * @details info about add/get/del tunnel encap vxlan table entry
 */
struct hinic5_tc_vxlan_tbl_cfg_info {
	struct hinic5_mgmt_msg_head head;     /**< Command message head */
	struct hinic5_tc_vxlan_hdr_info vxlan_hdr;     /**< vxlan header */
	u16 index;     /**< index id */
	u16 opcode;     /**< 0:del, 1:add, 2:get */
	u32 rsvd;     /**< Reserved field */
};

/**
 * @brief struct hinic5_tc_move_info
 * @details pfe tcam rule delete command structure
 */
struct hinic5_tc_move_info {
	struct hinic5_mgmt_msg_head head;     /**< Command message head */
	u32 old_index;     /**< old index */
	u32 new_index;     /**< new index */
	u32 len;     /**< length */
};

/**
 * @brief struct hinic5_tc_pfe_cfg_profile_info
 * @details pfe profile config from register
 */
struct hinic5_tc_pfe_cfg_profile_info {
	struct hinic5_mgmt_msg_head head;     /**< Command message head */
	u32 reg_value;     /**< register value */
	u32 opcode;     /**< 0: select profile 1: 3-2 shift 2: 3-1-2 shift */
	u32 rsvd;     /**< Reserved field */
};

#define PFE_ACL_AGING_BLOCK_NUM 128

/**
 * @brief struct hinic5_tc_aging_info
 * @details info about pfe tc aging table
 */
struct hinic5_tc_aging_info {
	struct hinic5_mgmt_msg_head head;     /**< Command message head */
	u16 addr;     /**< address */
	u16 opcode;     /**< 0:get, 1:set, 2:status */
	u32 entry_h[PFE_ACL_AGING_BLOCK_NUM];     /**< high 32 entry */
	u32 entry_l[PFE_ACL_AGING_BLOCK_NUM];     /**< lower 32 entry */
	u16 status;     /**< pfe aging table enable status, 0:disable; 1:enable */
	u16 rsvd;     /**< Reserved field */
};

#define HTN_CNT_SIZE 8

/**
 * @brief struct hinic5_tc_pfe_cnt_info
 * @details pfe count info
 */
struct hinic5_tc_pfe_cnt_info {
	struct hinic5_mgmt_msg_head head;     /**< Command message head */
	u32 htn_cnt[HTN_CNT_SIZE];     /**< HTN count */
	u16 mode;     /**< 0:tx, 1:rx */
	u16 opcode;     /**< 0:get, 1:reset */
	u32 count_id;     /**< count id */
};

/* VF available vport count resources */
#define MAX_NIC_COUNT_ID 24

/**
 * @brief struct hinic5_nic_vport_cnt_info
 * @details nic vport count info
 */
struct hinic5_nic_vport_cnt_info {
	struct hinic5_mgmt_msg_head head;     /**< Command message head */
	struct hinic5_vport_stats stats;     /**< vport statistics */
	u32 cnt_res[MAX_NIC_COUNT_ID];     /**< func id for allocating vport count resources */
	u32 cur_cnt;     /**< Current number of occupied resources */
	u32 func_id;     /**< func id to configure or query */
	u32 index;     /**< chip index corresponding to func id */
	u32 opcode;     /**< See nic_vport_cnt_op_e */
	u32 rsv1;     /**< Reserved field */
	u64 rsv2[192];     /**< Reserved field */
};

/**
 * @brief struct hinic5_tc_pfe_cfg_reg_info
 * @details pfe config from register
 */
struct hinic5_tc_pfe_cfg_reg_info {
	struct hinic5_mgmt_msg_head head;     /**< Command message head */
	u32 reg_value;     /**< register value */
	u32 reg_value2;     /**< register value */
	u32 rsvd;     /**< Reserved field */
};

#define TC_XY_KEY_SIZE 11

/**
 * @brief struct hinic5_tc_tcam_info
 * @details info about tcam info
 */
struct hinic5_tc_tcam_info {
	struct hinic5_mgmt_msg_head head;     /**< Command message head */
	u32 key_x[TC_XY_KEY_SIZE];     /**< tcam key_x info */
	u32 key_y[TC_XY_KEY_SIZE];     /**< tcam key_y info */
	struct hinic5_tc_action_info action;     /**< action info */
	u16 opcode;     /**< 0:del, 1:add, 2:group, 3:get */
	u16 index;     /**< index id */
	u8 group_cnt;     /**< group cnt */
	u8 rsvd[3];     /**< Reserved field */
};

#define PFE_VTEP_TBL_IP_SIZE 4
#define PFE_VTEP_TBL_IP_NUM 8

struct pfe_vtep_ip {
	u32 is_ipv6;     /**< 0: ipv4, 1: ipv6 */
	u32 ip_addr[PFE_VTEP_TBL_IP_SIZE];     /* ip_addr[0]: IPv6 DIP[127:96] or IPv4 DIP[31:0]
						* ip_addr[1]: IPv6 DIP[95:64] or IPv4 need set to 0
						* ip_addr[2]: IPv6 DIP[63:32] or IPv4 need set to 0
						* ip_addr[3]: IPv6 DIP[31:0] or IPv4 need set to 0
						*/
};

/**
 * @brief struct hinic5_tc_pfe_vtep_ip_cmd
 * @details PFE vtep table configuration
 */
struct hinic5_tc_pfe_vtep_ip_cmd {
	struct hinic5_mgmt_msg_head head;     /**< Command message head */
	struct pfe_vtep_ip dip[PFE_VTEP_TBL_IP_NUM];     /**< destination ip */
	u16 num;     /**< num of ip in dip table */
	u16 opcode;     /**< 0: del, 1: add, 2: query */
	u32 rsvd;     /**< Reserved field */
};

#define DEFAULT_ACTION_REG_NUM 9     /**< Number of registers involved in default ACTION (TX: 2, RX: 1, each ACTION: 3 registers) */

/**
 * @brief struct hinic5_tc_default_action_info
 * @details info about pfe default action
 */
struct hinic5_tc_default_action_info {
	struct hinic5_mgmt_msg_head head;     /**< Command message head */
	u8 opcode;     /**< action type: 0:drop; 1:upcall; 2:show; 3:output to port */
	u8 addr;     /* default action reg addr:
		      * 0:tx default action1; 1:tx default action2; 2:rx default action
		      */
	u16 index;     /**< func index */
	u32 action[DEFAULT_ACTION_REG_NUM];     /**< default action info */
};

/**
 * @brief struct hinic5_tc_pfe_tcam_freq_info
 * @details pfe tcam_freq info
 */
struct hinic5_tc_pfe_tcam_freq_info {
	struct hinic5_mgmt_msg_head head;     /**< Command message head */
	u32 tcam_sel;     /**< TCAM_CLK_SEL */
	u8 mode;     /**< 1:500MHz, 2:250MHz, 3:125MHz */
	u8 opcode;     /**< 0:get, 1:set */
	u16 rsvd;     /**< Reserved field */
};

/**
 * @brief struct hinic5_tc_tcam_clock_gating_cfg_info
 * @details info about tcam clock gating
 */
struct hinic5_tc_tcam_clock_gating_cfg_info {
	struct hinic5_mgmt_msg_head head;     /**< Command message head */
	u8 opcode;     /**< 0: get, 1: set */
	u8 status;     /**< 0: clock off, 1: clock on */
	u16 rsvd;     /**< Reserved field */
};

#define MAX_CEQ_PER_FUNC 0x20

/**
 * @brief Structure for setting NIC interrupt control
 * @details Contains information needed for setting NIC interrupt control
 */
struct mig_nic_set_ceq_ctrl {
	struct hinic5_mgmt_msg_head head;     /**< Command message head */
	u16 func_id;     /**< func id */
	u8 ceq_num;     /**< Number of CEQ controls */
	u8 rsvd;     /**< Reserved field */
	u32 ceq_ctrl0[MAX_CEQ_PER_FUNC];     /* CEQ controller 0 array
					      * Each element corresponds to a CEQ controller
					      */
	u32 ceq_ctrl1[MAX_CEQ_PER_FUNC];     /* CEQ controller 1 array
					      * Each element corresponds to a CEQ controller
					      */
};

#define MAX_INTR_NUM 0x80     /**< Maximum interrupt number 128 */

/**
 * @brief Structure for NIC MSI-X interrupt info migration
 * @details Contains management message head, func id, interrupt number, MSI-X control register operation and MSI-X control register 0 and 4 values.
 */
struct mig_nic_msix_info_rw {
	struct hinic5_mgmt_msg_head head;     /**< Command message head */
	u16 func_id;     /**< func id */
	u8 intr_num;     /**< Interrupt number */
	u8 msi_ctl_csr_op;     /* MSI-X control register operation
				* Identifies the type of MSI-X control register operation
				*/
	u32 msix_ctrl0[MAX_INTR_NUM];     /* MSI-X control register 0 values
					   * One value per interrupt
					   */
	u32 msix_ctrl4[MAX_INTR_NUM];     /* MSI-X control register 1 values
					   * One value per interrupt
					   */
};

#define MIG_FUNC_TBL_SIZE 0x50     /**< TBL size = (64 + 16(rsvd)) */
#define MIG_VAT_TBL_SIZE 0x10     /**< vat size: 0x10 */

/**
 * @brief Structure for storing NIC function and virtual address table information
 * @details Contains management message head, func id, opcode, function usage flag, function table and virtual address table.
 */
struct mig_nic_func_vat_tbl {
	struct hinic5_mgmt_msg_head head;     /**< Command message head */
	u16 func_id;     /**< func id */
	u8 opcode;     /**< Operation code */
	u8 func_used;     /**< Function usage flag */
	u8 func_tbl[MIG_FUNC_TBL_SIZE];     /**< func table */
	u8 vat_tbl[MIG_VAT_TBL_SIZE];     /**< Virtual address table */
	u8 rsvd[4];     /**< Reserved field */
};

#define MIG_FAST_MSG_VF_PAGE_NUM 4

/**
 * @brief Structure for storing NIC VF information
 * @details Contains VF information such as number of send queues, receive queues, command queues, etc.
 */
struct mig_nic_vf_info {
	u8 sq_num;     /**< Number of send queues */
	u8 rq_num;     /**< Number of receive queues */
	u8 cmdq_num;     /**< Number of command queues */
	u8 cmdq_depth;     /**< Command queue depth */
	u32 rq_depth;     /**< Receive queue depth */
	u32 sq_depth;     /**< Send queue depth */
	u32 sq_ci_base_addr_h;     /**< High bits of send queue completion pointer base address */
	u32 sq_ci_base_addr_l;     /**< Low bits of send queue completion pointer base address */
	u16 bat_size;     /**< Batch size */
	u8 valid;     /**< Valid flag */
	u8 fast_msg_en;
	u8 fast_msg_page_num;
	u8 rsvd[3];
	u64 fast_msg_page_addr[MIG_FAST_MSG_VF_PAGE_NUM];
};

/**
 * @brief Structure for storing NIC function configuration information
 * @details Contains NIC management message head, func id, reserved field and VF information.
 */
struct mig_nic_func_cfg {
	struct hinic5_mgmt_msg_head head;     /**< Command message head */
	u16 func_id;     /**< func id */
	u16 rsvd;     /**< Reserved field */
	struct mig_nic_vf_info vf_info;     /**< VF information */
};

/**
 * @brief Structure for checking if mailbox is empty
 * @details Used to check if the NIC mailbox is empty for subsequent operations.
 */
struct mig_nic_chk_mbx_empty {
	struct hinic5_mgmt_msg_head head;     /**< Command message head */
	u16 func_id;     /**< func id */
	u8 bme;     /**< Flag indicating if mailbox is empty */
	u8 is_func_used;     /**< Flag indicating if func is in use */
	u8 cmdq_num;     /**< get cmdq num for stop cmdq */
	u8 rsvd[3];     /**< Reserved field */
};

/**
 * @brief Structure for representing NIC vport state for migration
 * @details Contains vport state information such as management message head, func id, state, etc.
 */
struct mig_nic_vport_state {
	struct hinic5_mgmt_msg_head msg_head;     /**< Command message head */
	u16 func_id;     /**< func id */
	u16 rsvd1;     /**< Reserved field */
	u8 state;     /**< 0--disable, 1--enable */
	u8 rsvd2[3];     /**< Reserved field */
};

#define SQ_CI_ATTR_SIZE 0x14     /**< SQ CI address length */
#define SQ_CI_INDIR_TBL_SIZE 0x20     /**< SQ CI indirect table size */
#define MAX_CI_TBL_NUM 0x20     /**< mailbox max 2kb, one sq ci(attr + tbl) 52B, 32 *52 = 1664B < 2kb */

/**
 * @brief Structure for storing single NIC send queue control information
 * @details Contains sq_ci_tbl and sq_ci_attr for storing send queue control table and attributes respectively.
 */
struct mig_nic_single_sq_ci {
	u8 sq_ci_tbl[SQ_CI_INDIR_TBL_SIZE];     /**< sq ci table */
	u8 sq_ci_attr[SQ_CI_ATTR_SIZE];     /**< sq ci address table */
};

/**
 * @brief NIC structure for storing network interface information
 * @details Contains NIC basic information and service queue information
 */
struct mig_nic_sq_ci {
	struct hinic5_mgmt_msg_head msg_head;     /**< Command message head */
	u16 func_id;     /**< Function ID for identifying NIC function */
	u8 opcode;     /**< Operation code for identifying NIC operation type */
	u8 curr_sq_id;     /* Current service queue ID
			    * Identifies the service queue currently in use
			    */
	u8 round_queue_num;     /* Number of round queues
				 * Identifies the number of round queues for the NIC
				 */
	u8 rsvd[3];     /**< Reserved field */
	struct mig_nic_single_sq_ci sq_ci[MAX_CI_TBL_NUM];     /**< Single sq ci information */
};

#define RSS_INDIR_TBL_SIZE 0x200     /**< RSS indirect table size */
#define RSS_KEY_SIZE 0x28     /**< RSS key size */

/**
 * @brief Structure for NIC Receive Side Scaling (RSS)
 * @details Contains RSS related parameters for configuring NIC RSS functionality.
 */
struct mig_nic_rss_tbl {
	u8 rss_enable;     /**< RSS enable/disable flag */
	u8 rss_hash_engine;     /**< RSS hash engine type */
	u16 rsvd;     /**< Reserved field */
	u32 rss_ctx;     /**< RSS context */
	u8 rss_indri_tbl[RSS_INDIR_TBL_SIZE];     /**< RSS indirect table */
	u8 rss_key[RSS_KEY_SIZE];     /**< RSS key */
};

/**
 * @brief Structure for NIC configuration with management message head, func id, opcode, reserved fields and RSS table
 * @details Used for NIC configuration including management message head, func id, opcode, reserved fields and RSS table.
 */
struct mig_nic_cfg_rss_tbl {
	struct mgmt_msg_head msg_head;     /**< Command message head */
	u16 func_id;     /**< func id */
	u8 opcode;     /**< Operation code */
	u8 rsvd;     /**< Reserved field */
	struct mig_nic_rss_tbl rss_tbl;     /**< RSS table */
};

#define MAX_CMDQ_NUM 0x4     /**< Maximum cmdq number */
#define ENHANCED_CMDQ_CTX_SIZE 0x30     /**< Enhanced cmdq context size is 48 */

/**
 * @brief Structure for storing NIC temporary configuration command queue context
 * @details Contains management message head, func id, command queue number, reserved fields and command queue context
 */
struct mig_nic_tmp_cfg_cmdq_ctx {
	struct mgmt_msg_head msg_head;     /**< Command message head */
	u16 func_id;     /**< func id */
	u8 cmdq_num;     /**< cmdq number */
	u8 rsvd;     /**< Reserved field */
	u8 cmdq_ctx[MAX_CMDQ_NUM * ENHANCED_CMDQ_CTX_SIZE];     /**< cmdq context */
};

/**
 * @brief NIC migration queue stop info structure
 * @details Used to describe NIC migration queue stop related information.
 */
struct nic_mig_sq_stop {
	struct hinic5_mgmt_msg_head msg_head;     /**< Command message head */
	u16 func_id;     /**< func id */
	u8 is_stop;     /**< Whether to stop */
	u8 sq_num;     /**< sq queue number */
	u8 rsvd[4];     /**< Reserved field */
};

struct mig_nic_fast_msg_addr {
	struct mgmt_msg_head head;     /**< Command message head */
	u16 func_id;     /**< func id */
	u8 opcode;     /**< Operation code */
	u8 page_num;     /**< page num */
	u32 rsvd;     /**< Reserved field */
	u64 page_addr[MIG_FAST_MSG_VF_PAGE_NUM];     /**< page addr */
};

/**
 * @brief struct hinic5_cmd_set_pcie_flr_mgmt
 * @details NIC set pcie flr command structure
 */
struct hinic5_cmd_set_pcie_flr_mgmt {
	struct hinic5_mgmt_msg_head msg_head;     /**< Command message head */
	u16 func_id;     /**< func id */
	u16 rsvd1;     /**< Reserved field */
};

struct hinic5_cmd_lro_cfg {
	struct hinic5_mgmt_msg_head msg_head;     /**< Command message head */
	u16 func_id;     /**< func id */
	u8 data;     /**< data to be set or get */
	u8 data_type;     /**< data type: See lro_cfg_operate_type enum definition */
	u8 opcode;     /**< 0: get, 1: set */
	u8 rsvd1[3];     /**< Reserved field */
};

#define NIC_DCB_UP_MAX 0x8     /**< Maximum user priority (UP) for NIC DCB */

/**
 * @brief hinic5_dcb_state
 * @details nic dcb state command structure
 */
struct hinic5_dcb_state {
	u8 dcb_on;     /**< dcb on or off */
	u8 default_cos;     /**< default cos */
	u8 trust;     /**< trust state */
	u8 rsvd1;     /**< Reserved field */
	u8 pcp2cos[NIC_DCB_UP_MAX];     /**< pcp to cos */
	u8 dscp2cos[64];     /**< dscp to cos */
	u32 rsvd2[7];     /**< Reserved field */
};

/**
 * @brief hinic5_cmd_vf_dcb_state
 * @details nic vf dcb state command structure
 */
struct hinic5_cmd_vf_dcb_state {
	struct hinic5_mgmt_msg_head msg_head;     /**< Command message head */
	struct hinic5_dcb_state state;     /**< dcb state */
};

struct hinic5_cmd_port_info {
	struct hinic5_mgmt_msg_head msg_head;     /**< Command message head */
	u8 port_id;
	u8 rsvd1[3];     /**< Reserved field */
	u8 port_type;
	u8 autoneg_cap;
	u8 autoneg_state;
	u8 duplex;
	u8 speed;
	u8 fec;
	u16 rsvd2;     /**< Reserved field */
	u32 rsvd3[4];     /**< Reserved field */
};

/**
 * @brief nic_cmd_bond_active_report_info
 * @details Async message notification structure sent to host after lacp negotiation result update
 */
struct nic_cmd_bond_active_report_info {
	struct mgmt_msg_head head;     /**< Command message head */
	u32 bond_id;
	u32 bon_mmi_status;     /**< Bond sub-device link status */
	u32 active_bitmap;     /**< Bond sub-device slave port status */
	u8 rsvd[16];     /**< Reserved field */
};

/**
 * @brief nic_cmd_tx_pause_notice
 * @details pfc/pause storm tx exception report
 */
struct nic_cmd_tx_pause_notice {
	struct hinic5_mgmt_msg_head head;     /**< Command message head */
	u32 tx_pause_except;     /**< 1: exception, 0: normal */
	u32 except_level;     /**< Exception level */
	u32 rsvd;     /**< Reserved field */
};

#pragma pack(4)
typedef struct fault_msg_s {
	struct mgmt_msg_head msg_head;     /**< Command message head */
	u8 num;     /**< Number of custom packets to send */
	u8 rsvd[3];     /**< Reserved field */
	u16 real_size;
	u8 mode;     /**< 0: read, 1: write */
	u8 type;     /**< 0: send notification later, 1: send notification immediately */
	u8 data[0];     /**< Size specified by real_size */
} fault_msg_t;
#pragma pack()

#define TCAM_FLOW_KEY_SIZE 44     /**< TCAM key size is 44B */

typedef struct {
	u32 qid : 10;     /* If flag==1, fdir_qid represents group id;
			   * If flag==0, fdir_qid represents qid
			   */
	u32 flag : 1;
	u32 rsvd : 21;     /**< Reserved field */
} qid_htn_s;

typedef union {
	qid_htn_s qid_htn;
	u32 qid;
} qid_u;

/**
 * @brief Structure for storing TCAM lookup result
 * @details Contains Flow Director compound destination information (qid/group + flag) and reserved field.
 */
struct tcam_result {
	qid_u fdir_info;
	u32 rsvd;     /**< Reserved field */
};

/**
 * @brief Structure for storing TCAM flow key x and y values
 * @details TCAM flow key is a data structure for flow table lookup, where x and y values are the two components of the flow key.
 */
struct tcam_key_x_y {
	u8 x[TCAM_FLOW_KEY_SIZE];     /**< x value, size is TCAM_FLOW_KEY_SIZE */
	u8 y[TCAM_FLOW_KEY_SIZE];     /**< y value, size is TCAM_FLOW_KEY_SIZE */
};

/**
 * @brief Structure for storing NIC TCAM configuration rules
 * @details Contains TCAM configuration rule index, data and key for storing and managing TCAM configuration rules in NIC.
 */
struct nic_tcam_cfg_rule {
	u32 index;     /**< Rule index */
	struct tcam_result data;     /**< Rule data */
	struct tcam_key_x_y key;     /**< Rule key */
};

/**
 * @brief TCAM configuration rule
 * @details Contains TCAM rule configuration information such as rule key, mask, action, etc.
 */
struct nic_cmd_fdir_add_rule {
	struct hinic5_mgmt_msg_head head;     /**< Command message head */
	u16 func_id;     /**< Func ID */
	u8 type;     /**< Rule type */
	u8 usrdata;     /**< User data */
	struct nic_tcam_cfg_rule rule;     /**< Configuration table */
};

/**
 * @brief Structure for NIC command filter get rule
 * @details Used to store NIC fdir get rule related information.
 */
struct nic_cmd_fdir_get_rule {
	struct hinic5_mgmt_msg_head head;     /**< Command message head */
	u32 index;     /**< Index field */
	u8 valid;     /**< Valid field */
	u8 type;     /**< Type field */
	u16 rsvd;     /**< Reserved field */
	struct tcam_key_x_y key;     /**< TCAM key field */
	struct tcam_result data;     /**< TCAM result field */
	u64 packet_count;     /**< Packet count field */
	u64 byte_count;     /**< Byte count field */
};

#define NIC_TCAM_BLOCK_LARGE_NUM 256     /**< Maximum TCAM BLOCK number is 256 */
#define NIC_TCAM_BLOCK_LARGE_SIZE 16     /**< Maximum block size is 16 */
#define TCAM_RULE_FDIR_TYPE 0     /**< TCAM rule type, FDIR type value is 0 */
#define TCAM_RULE_PPA_TYPE 1     /**< TCAM rule type, PPA type value is 1 */

/**
 * @brief Structure for getting TCAM block rules
 * @details Used to get TCAM block rules, including TCAM block type, TCAM table type, TCAM block index, valid array, TCAM key array and TCAM result array.
 */
struct nic_cmd_fdir_get_block_rules {
	struct hinic5_mgmt_msg_head head;     /**< Command message head */
	u8 tcam_block_type;     /**< TCAM block type, currently only NIC_TCAM_BLOCK_TYPE_LARGE */
	u8 tcam_table_type;     /* TCAM rule type
				 * TCAM_RULE_PPA_TYPE or TCAM_RULE_FDIR_TYPE
				 */
	u16 tcam_block_index;     /**< TCAM block index */
	u8 valid[NIC_TCAM_BLOCK_LARGE_SIZE];     /**< Valid array */
	struct tcam_key_x_y key[NIC_TCAM_BLOCK_LARGE_SIZE];     /**< TCAM key array */
	struct tcam_result data[NIC_TCAM_BLOCK_LARGE_SIZE];     /**< TCAM result array */
};

struct hinic5_rate_xir_xbs {
	u32 cir;     /**< unit: kbps */
	u32 pir;     /**< unit: kbps */
	u32 cbs;     /**< unit: Byte */
	u32 pbs;     /**< unit: Byte */
};

/**
 * @brief NIC tx MQM rate configuration
 * @details Used to set and get func MQM rate limit parameters and set func mapping table.
 */
struct hinic5_cmd_tx_limit_rate {
	struct hinic5_mgmt_msg_head msg_head;     /**< Command message head */
	u16 func_id;     /**< func ID */
	u8 op_code;     /**< Operation type: 0 - default; 1 - get; 2 - set; 3 - map */
	u8 vnicgrp_flag;     /**< vnicgrp operation flag: 0 - vnic; 1 - vnic group */
	u32 vnicgrp_id;     /**< vnic group ID */
	u32 vnic_id;     /**< vnic ID */
	u8 limit_type;     /**< Rate limit type: 0 - pps; 1 - bps */
	u8 rsvd1[3];     /**< Reserved field */
	struct hinic5_rate_xir_xbs rate_para;     /**< rate_cfg */
	u32 rsvd2[64];     /**< Reserved field */
};

#define HINIC5_TX_SET_PROMISC_SKIP 0     /**< Set promiscuous mode for unknown unicast packets */
#define HINIC5_TX_GET_PROMISC_SKIP 1     /**< Get promiscuous mode for unknown unicast packets */

/**
 * @brief Set promiscuous mode for unknown unicast packets
 * @details This structure is used to enable/disable forwarding unknown unicast packets to promiscuous PF
 */
struct hinic5_tx_promisc_cfg {
	struct hinic5_mgmt_msg_head head;     /**< Command message head */
	u8 port_id;     /**< Network port id */
	u8 promisc_skip_en;     /**< 0: disable forwarding 1: enable forwarding */
	u8 opcode;     /**< 0: set 1: get */
	u8 rsvd;     /**< Reserved field */
};

#define HINIC5_ARP_PKT_MAX_LEN 512

/**
 * @brief Structure for passing ARP packet info to MPU
 * @details Used to pass ARP or ND packets that need to be sent by MPU
 */
struct hinic5_arp_pkt_info {
	struct hinic5_mgmt_msg_head head;     /**< Command message head */
	u16 func_id;     /**< func ID */
	u16 pkt_length;     /**< Packet length */
	u16 origin_queue_id;     /**< Queue id where driver sent the packet */
	u8  rsvd[2];     /**< Reserved field */
	u32 rsvd1[4];     /**< Reserved field */
	u8 pkt_buf[HINIC5_ARP_PKT_MAX_LEN];     /**< Packet buffer */
};

/**
 * @brief Structure for passing Bond configuration to MPU
 * @details Used to pass offload Bond configuration to MPU
 */
struct hinic5_cmd_cfg_bond {
	struct hinic5_mgmt_msg_head head;     /**< Command message head */
	u16 func_id;
	u8 opcode;     /**< operation code: 1 set arp status, 0 get arp status */
	u8 arp_en;     /**< ARP dual-send enable */
	u32 rsvd;     /**< Reserved field */
};

#endif /* HINIC5_NIC_CMD_STRUCTS_H */

